### ISSUE TITLE
Exact half-width variant?

### ISSUE THREAD

**Issue by be5invis** [fabrizioschiavi/pragmatapro#10]
I'm wondering whether Pragmata Pro could have an exact half-width variant (which means that all glyphs are 1/2 em wide) to make it compatible to CJK characters (including 中文 and にほんご). The current width of characters is 1060/2048 em which is a bit wider than 1/2em.

**Comment by fabrizioschiavi** [comment]
Very interesting solution! Thanks for proposing!
Unfortunately it seems "impossible" do do at this point (more than 10000 glyphs designed)
It means to redesign all, spacing issues, TrueType hinting to rebuild enterely
Damn! If only I had come before this idea...

**Comment by be5invis** [comment]
Hmmm i think move all glyphs leftward by 18emu and shrink the width of glyphs to 1024emu will produce an acceptable result. Hints can be generated by *ttfautohint* since Chinese and Japanese users will turn on their antialiazation because of the complex strokes of Kanjis.

**Comment by fabrizioschiavi** [comment]
Could you send me please some screenshots of what you see? It can be very useful to me. Thank you!

**Comment by be5invis** [comment]
I reduced both side bearings by 18emu to make all glyphs exactly 1024emu wide.
And I think the result is okay...

![capitals](http://ww2.sinaimg.cn/large/798f7769gw1eubx192e8bj21kw0duten.jpg)
![lowercases](http://ww2.sinaimg.cn/large/798f7769gw1eubx1hw316j21kw0duq8s.jpg)

**Comment by fabrizioschiavi** [comment]
Good! 
Can you let me see a sample coding Chinese or Japanese text using PragmataPro with and without this your modification, please?
Just to have a more clear idea.
Many thanks!!

**Comment by be5invis** [comment]
The PragmataPro's glyphs are slightly wider than 0.5em makes Latin characters and Kanjis not aligned...
![.](http://ww4.sinaimg.cn/mw1024/798f7769gw1euc75sv134j20qy072mye.jpg)

Meanwhile when an exact-halfwidth font (like M+ 1mn or Source Han Sans HW) is used, all characters are aligned well.
![.](http://ww3.sinaimg.cn/mw1024/798f7769gw1euc76fm18ij20po072q40.jpg)

**Comment by fabrizioschiavi** [comment]
I'm working at this enhancement and I think to found the right way to change ALL the glyphs without spending all my life. This issue can be fixed!
Added as priority for v_0.822
![screen shot 2015-07-24 at 16 10 43](https://cloud.githubusercontent.com/assets/1576663/8876217/9c969230-321e-11e5-8db6-78d14c5d6809.png)

**Comment by be5invis** [comment]
Thanks.

**Comment by fabrizioschiavi** [comment]
Since now PragmataPro (0.822) has now half-width glyphs. It's been hard to keep high the quality of hinting reducing more than 10000 glyphs but I'm satisfied but this improvement.
Please read more [here](http://www.fsd.it/2016/03/14/pragmatapro-0822-the-silent-revolution/)
Thanks again @be5invis
