### ISSUE TITLE
Option to use all 4 variants (explicit font naming)

### ISSUE THREAD

**Issue by danielmt** [fabrizioschiavi/pragmatapro#101]
Right now, it's impossible to use/test the 4 font variants, because there's just PragmataPro and PragmataPro Mono for either "option" (with/without ligatures). The font names should be explicit about this.

**Comment by fabrizioschiavi** [comment]
This is already fixed for the next release (0.827) in progress. Thank you!

**Comment by danielmt** [comment]
Is there any ETA on the next release?

**Comment by fabrizioschiavi** [comment]
≈ End of June

**Comment by fabrizioschiavi** [comment]
[Fixed](https://github.com/fabrizioschiavi/pragmatapro/issues/78#issuecomment-419494289) 😄
