### ISSUE TITLE
Aliased pound sign (#) renders poorly

### ISSUE THREAD

**Issue by 9999years** [fabrizioschiavi/pragmatapro#103]
Pragmata Pro’s pound sign (`#`) renders pretty poorly when it’s aliased (see below) at most sizes. I don’t know how easy this is to fix but it’s something I notice pretty often.

![pragmata-pro-hash-small](https://user-images.githubusercontent.com/15312184/42403235-c15a45c2-814d-11e8-9cc0-eab4ac1c9199.png)

[Bigger image (4× scale)](https://user-images.githubusercontent.com/15312184/42403221-ab0c8c1c-814d-11e8-9df3-c4bb07298bcd.png)

**Comment by fabrizioschiavi** [comment]
Fixed since .827

**Comment by 9999years** [comment]
New pound sign looks great! Thanks Fabrizio!

![# in Pragmata Pro v0.827](https://user-images.githubusercontent.com/15312184/45260821-270ba480-b3bf-11e8-8376-773c7df2d411.png)
