### ISSUE TITLE
Regular+Italic download only included TTF files, not OTF

### ISSUE THREAD

**Issue by klardotsh** [fabrizioschiavi/pragmatapro#104]
Not sure if this is by design? My terminal can't use TTF ligatures (from what I understand), only OTF, so unfortunately the font isn't fully usable without those files.

**Comment by klardotsh** [comment]
Nvm. Discovered through Googling that:

1. The lack of OTFs is by design
2. `kitty` does support TTF ligatures
3. `kitty` does _not_ like PragmataPro in general right now, and _that's_ the real reason the font didn't render correctly.

**Comment by jspiro** [comment]
Incidentally, what are the reasons for not generating OTFs?

**Comment by fabrizioschiavi** [comment]
[This](https://superuser.com/questions/96390/difference-between-otf-open-type-or-ttf-true-type-font-formats/545024#545024) is the main reason. Anyway I'll generate OTFs since the next release. Times are changed
