### ISSUE TITLE
U+2B31 and U+2B32 are inverted

### ISSUE THREAD

**Issue by slice** [fabrizioschiavi/pragmatapro#105]
* ⬱ (`THREE LEFTWARDS ARROWS`) U+2B31
* ⬲ (`LEFT ARROW WITH CIRCLED PLUS`) U+2B32

These codepoints are inverted:

![image](https://user-images.githubusercontent.com/4206232/44188835-b8476e00-a0d4-11e8-8b95-6347bf7866cb.png)

And because PragmataPro is the only font with this glyph on my system, this ends up happening system wide...

**Comment by fabrizioschiavi** [comment]
Ops! I'll fix it now. Thank you!!

**Comment by slice** [comment]
Thanks for the quick fix! 😄
