### ISSUE TITLE
Regression: Windows does not recognize PragmataPro Mono (0.827) as fixed-width font anymore.

### ISSUE THREAD

**Issue by graycrow** [fabrizioschiavi/pragmatapro#106]
The previous version of PragmataPro Mono 0.826 was recognized by Windows as fixed width font, so it was possible to set it as custom console font (by adding it to the `HKLM\Software\Microsoft\WindowsNT\CurrentVersion\Console\TrueTypeFont` registry key) and Visual Studio, for example, highlighted the font in the Options window (Fonts and Colors - bold type indicates fixed-width fonts).

Now, in version 0.827, its not true anymore. And if it's not an issue in Visual Studio (it will let you use any font anyway), not being able to use PragmataPro on Windows console is serious drawback for me, so I reverted PragmataPro Mono to the previous version.

[Tested in Windows 8.1]

**Comment by fabrizioschiavi** [comment]
Could you try to download again the font files?

**Comment by graycrow** [comment]
Just downloaded. It works now in Windows console and recognized as fixed-width by Visual Studio as well.
Thank you, that was fast!

**Comment by jordwalke** [comment]
Did you update something to fix this? Did it get pushed to MyFonts?
