### ISSUE TITLE
Latest version not honored by Xcode on macOS

### ISSUE THREAD

**Issue by wookiee** [fabrizioschiavi/pragmatapro#107]
- Works fine in SublimeText
- [Here's a video](https://mw-dropshare.s3.amazonaws.com/Screen-Recording-2018-09-06-12-13-01.mp4) of switching between several fonts (some free, some built-in, some commercial), and what happens when I select PragmataPro. 
    - Xcode simply ignores the font and loads its default fallback font (SFMono) instead.

**Comment by graycrow** [comment]
Try to re-download the fonts. I had a similar issue but in Windows (bug #106) and @fabrizioschiavi was quick to fix it.

**Comment by fabrizioschiavi** [comment]
Anyway it’s really strange this font replacing. I have to investigate

**Comment by graycrow** [comment]
@fabrizioschiavi, the fonts I downloaded after your advice have the same size as previous ones, but slightly different content. So, I though that you fixed something, no? Just in case, this is the diff for PragmataPro_Mono_R_0827.ttf (position | older version | newer version):
```
00000043: 8C 8F
000000A2: 90 E8
000000A3: 8C BF
00000103: D1 D2
00009EEB: 06 09
0015B835: F5 F4
0015B836: 6B BA
0015B837: 1A AC
0015B84E: A0 F8
0015B84F: 30 63
0016AAAB: 00 01
```

**Comment by fabrizioschiavi** [comment]
@graycrow I just forgot to enable this on the font setting 😄 
![screen shot 2018-09-10 at 14 53 32](https://user-images.githubusercontent.com/1576663/45298641-6a722a00-b509-11e8-8f68-d1644fb34c22.png)

@wookiee could you try to re-download the font files? 
I tried with Xcode too and it seems ok now. Please confirm

**Comment by wookiee** [comment]
In any case, it works now! Thanks!

**Comment by Porges** [comment]
@wookiee Mono is a true monospace and has no ligatures, the non-Mono versions are set to monospace dimensions but have ligatures so some characters take up more than one 'space'.
