### ISSUE TITLE
myfonts.com missing update to 0.827

### ISSUE THREAD

**Issue by danielmt** [fabrizioschiavi/pragmatapro#108]
Went to myfonts.com to grab latest version and still has 0.826 :(

**Comment by fabrizioschiavi** [comment]
My Fonts updates takes always some days more. Patience

**Comment by wismill** [comment]
Update still not there. Waiting patiently ;-)

**Comment by wismill** [comment]
Update available!

**Comment by fabrizioschiavi** [comment]
🎉 !
