### ISSUE TITLE
Semi-bold version?

### ISSUE THREAD

**Issue by jibsen** [fabrizioschiavi/pragmatapro#11]
One of the few things that I like less about this font is the bold version. I think it is perhaps a bit too bold to be easy to read. I guess part of the reason is so it matches the aliased look.

As an example, here are screenshots from Total Commander using a NC color theme. To me, the regular version is a bit too "thin" for this color combination. The bold is so bold that it is a bit hard to read. The last screenshot is Consolas Bold for comparison, I think it looks good here:

![tc_bold_compare](https://cloud.githubusercontent.com/assets/1367512/8896343/15461472-33f9-11e5-9088-d91ac3f9f5c5.png)

I don't know how hard it would be to add a semi-bold version? just for anti-aliased use of course.

**Comment by fabrizioschiavi** [comment]
Thanks @jibsen to let me know your point of view.
 I think PragmataPro has a good differentiation between Regular and Bold
The critical moment is around 14pt (on Windows) where hinting makes it look very similar Regular and Bold creating confusion. Reducing the thickness of the stems of the Bold would **coincide**, so it can be consider as a counterproductive operation
