### ISSUE TITLE
Uppercase italic L appears slightly shorter than other letters

### ISSUE THREAD

**Issue by jibsen** [fabrizioschiavi/pragmatapro#110]
I noticed that the L in italic PragmataPro Mono 0.827 appears to be not quite as high as the other characters:

![uppercase_l-or8-z](https://user-images.githubusercontent.com/1367512/45232356-6c50a900-b2cf-11e8-9edd-4bb4af56dd6c.png)

Not quite sure if this was the case in earlier versions, but didn't notice it before now.

**Comment by fabrizioschiavi** [comment]
Too bad 😞 
Too much characters to look at and in a multi-level. I'll fix it soon.
Thanks @jibsen

**Comment by fabrizioschiavi** [comment]
Try to re-download the font files. Please let me know. Thanks!

**Comment by jibsen** [comment]
Looks right now, thanks!
