### ISSUE TITLE
Some of programs on Windows always used Italic style from mono-fonts family 

### ISSUE THREAD

**Issue by mvs3d** [fabrizioschiavi/pragmatapro#111]
Hi Fabrizio, thank you for great product!

I got strange issue with latest  (0.827) version. Some of my programs which using regular mono-style fonts has been switched to Italic (both fonts with ligatures and without). When i choose Bold style - working well (Italic style is dissapear), but checking/un-checking "Italic" option has no result (always used Italic style). 

At result I've switched back to 0.826 version.

My system is Window 7, programs with this issue - ConEnu https://conemu.github.io/ and KiTTY http://www.9bis.net/kitty/

Let me known if you need more detailed info from me.

**Comment by fabrizioschiavi** [comment]
I'm investigating about this strange issue. Thanks for letting me know it!

**Comment by fabrizioschiavi** [comment]
Thank you @mvs3d !
Could you re-download the font files and let me know if it’s ok now, please?

**Comment by mvs3d** [comment]
Hi @fabrizioschiavi!
Thank you for the update. I've download and tried switch to using to 0.827 font, and it's OK in ConEnu and KiTTY (not always Italic style), but i have another issue there: https://github.com/fabrizioschiavi/pragmatapro/issues/113

I have issue with PhpStorm also (with old and new 0.827 versions) with broken fonts:.
![phptorm](https://user-images.githubusercontent.com/5299867/45374381-003db000-b603-11e8-9954-9b14193a54df.png)

**Comment by fabrizioschiavi** [comment]
😮

**Comment by mvs3d** [comment]
Yeah :) I'm again switched back to 0.826..

**Comment by r03** [comment]
I have the same in gvim but only if the encoding is not utf-8

**Comment by mvs3d** [comment]
Hi Fabrizio, I'll like to say I'm installed 0.827 version into my new PC (running on Windows 10) and no any issues with this version there. So, maybe this is was a  local glitch on my previous PC.
