### ISSUE TITLE
Rendering of the box drawing symbols on Windows 7

### ISSUE THREAD

**Issue by graycrow** [fabrizioschiavi/pragmatapro#113]
On my Windows 7 console (cmd.exe) rendering of the box drawing characters is not perfect (pls. note the gaps between lines). On Windows 8.1 the same font is rendered ok.  I'm not sure if it's Windows 7 issue, font issue or my particular setup issue. I had the previous version of the font installed on this Windows 7 system before 0.827 and it was rendered without gaps. Unfortunately I uninstalled the previous version before installing 0.827 and I don't remember which version it was, 0.826 or earlier.

Windows 7:
![image](https://user-images.githubusercontent.com/1478788/45369411-1b4df700-b5e6-11e8-9ee7-89ab7bca423e.png)

Windows 8.1:
![image](https://user-images.githubusercontent.com/1478788/45369423-2739b900-b5e6-11e8-8884-fd1c757cb994.png)

[Edit] All standard console fonts on Windows 7 (Consolas and Lucida Console) are rendered without gaps.

**Comment by fabrizioschiavi** [comment]
I'll fix it soon (I hope)

**Comment by graycrow** [comment]
@fabrizioschiavi, I just downloaded it (5 minutes before I posted this), but the downloaded archive is exactly the same as the one I downloaded before, same size and date, same content, no difference. And no change in rendering, obviously.

**Comment by fabrizioschiavi** [comment]
Sorry, my bad. Could you try now please?

**Comment by fabrizioschiavi** [comment]
🎉
