### ISSUE TITLE
Characters like ⌘⌥ in Regular Font have the wrong size

### ISSUE THREAD

**Issue by petrubear** [fabrizioschiavi/pragmatapro#114]
Hi, I just noticed that characters like ⌘⌥ are shown in a different size in my editor (Sublime Text, Visual Studio Code, IntelliJ) on the regular font, they look fine in Bold, Im using PragmataPro Liga.

![screen shot 2018-09-11 at 7 16 49 pm](https://user-images.githubusercontent.com/3639210/45394634-4725a880-b5f7-11e8-88db-023640e421b7.png)

**Comment by fabrizioschiavi** [comment]
Thanks for letting me know, I'll fix it

**Comment by fabrizioschiavi** [comment]
`⌘` `⌥` are now corrected in every weights.
Thanks again for your help!
