### ISSUE TITLE
Bash ligatures

### ISSUE THREAD

**Issue by adrianparvino** [fabrizioschiavi/pragmatapro#115]
It would be cool to have some ligatures for Bash, considering that `#{` already has ligatures.

Off the top of my head, I can name the following that I would appreciate having ligatures for.
- [ ] `$(`
- [ ] `$((`
- [ ] `${`
- [ ] `((`
- [ ] `))`

**Comment by fabrizioschiavi** [comment]
How do you imagine the design of these ligatures?

**Comment by Porges** [comment]
`((` and `))` would be difficult because they come up normally in unbalanced situations: `((int)x + 1) * 2`

**Comment by adrianparvino** [comment]
@Porges FWIW, there are ligatures for `[[` and `]]`, despite them being unbalanced sometimes.

@fabrizioschiavi I'm thinking similar to the design of `#{`.

**Comment by fabrizioschiavi** [comment]
I agree with @Porges because spacing a bit can cause unbalancing situations.
`[[` and `]]` was removed since version 0.828 just for this reason (see #119) . 
`#{` it's ok for the weird 'nature' of `#`

**Comment by adrianparvino** [comment]
Aww. :( Thanks anyway!
