### ISSUE TITLE
boolean kerning causes issues in Microsoft Word

### ISSUE THREAD

**Issue by arcfide** [fabrizioschiavi/pragmatapro#118]
In the following picture, the two lines of text are the same, but one has boolean in it and the other has bool'ean in it. 

![sketch](https://user-images.githubusercontent.com/1235230/46269741-098ab000-c511-11e8-884f-c5cb0831bbe9.png)

This is happening in MS Word. I am not able to find any other editor with which to try this. It does not occur in Notepad because kerning does not seem to happen in Notepad for the reserved keywords.

**Comment by fabrizioschiavi** [comment]
I'll investigate on it. Thank you!

**Comment by fabrizioschiavi** [comment]
@arcfide can you try if the issue is still active also using [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) 0.829, please?

**Comment by arcfide** [comment]
I can confirm that this does not seem replicable anymore with the latest version of the font! Thank you.
