### ISSUE TITLE
Ugly brackets case

### ISSUE THREAD

**Issue by arcfide** [fabrizioschiavi/pragmatapro#119]
Here's an example of an ugly bracket kerning using ligatures:

![sketch](https://user-images.githubusercontent.com/1235230/46481799-139bff80-c7ec-11e8-844e-d7fa4fc8a599.png)

**Comment by fabrizioschiavi** [comment]
Thanks! I'll remove this ligature in the next release.

**Comment by fabrizioschiavi** [comment]
Fixed since version 0.828. Thanks!
