### ISSUE TITLE
How to get updates?

### ISSUE THREAD

**Issue by rocha** [fabrizioschiavi/pragmatapro#12]
I bought PragmataPro a while ago from FontShop.com. The latest version I have is 0.812. What is the process to get a newer version?

**Comment by fabrizioschiavi** [comment]
According with FontShop, you must receive an update notification via email.
Please check your spam folder
I'll check with @fontshop if there are troubles with updates
Thanks!

**Comment by rocha** [comment]
Thanks @fabrizioschiavi. I'll check with them.
