### ISSUE TITLE
Shrug broken

### ISSUE THREAD

**Issue by LoganDark** [fabrizioschiavi/pragmatapro#120]
(in comment)
![image](https://user-images.githubusercontent.com/4723091/47012103-53ba8680-d0f8-11e8-9a69-0e81589f4e23.png)
`¯\_(ツ)_/¯` should display like ![image](https://user-images.githubusercontent.com/4723091/47012121-5ae19480-d0f8-11e8-909c-5127447e85a5.png)

**Comment by fabrizioschiavi** [comment]
Ops! I'll fix it. Thank you!

**Comment by LoganDark** [comment]
Speaking of fixing it, how would I go about downloading a newer version of this font? I'm not sure which version I have, but I can't remember where I got it from since it was a while ago.

**Comment by fabrizioschiavi** [comment]
Simple: go to fsd.it > log in > my account > download
Anyway if your PragmataPro copy has this issue means you have latest version

**Comment by LoganDark** [comment]
Oh, okay, thanks.

The issue is that I don't remember what email and password I used (since I have very many), but knowing I have the latest version is good enough for now.

**Comment by fabrizioschiavi** [comment]
![Screen Shot 2019-08-04 at 14 41 55](https://user-images.githubusercontent.com/1576663/62423808-1a262c80-b6c6-11e9-9404-1be45e48322b.png)
