### ISSUE TITLE
u is displayed as μ

### ISSUE THREAD

**Issue by stefanfrede** [fabrizioschiavi/pragmatapro#122]
If I do a `ls -l` in the `Terminal.app` and the first letter of a file or folder is starting with `u` it is getting displayed as `μ`.

For example:
`-rw-r--r--   1 foo  bar      172 Oct 24  2017 μsrmngmnt.json`

**Comment by fabrizioschiavi** [comment]
Thanks for the notification. I'll fix it asap

**Comment by fabrizioschiavi** [comment]
μs issue was fixed since PragmataPro 0.828. Thanks for opened this issue!
