### ISSUE TITLE
θ and Θ hard to distinguish

### ISSUE THREAD

**Issue by vlopezj** [fabrizioschiavi/pragmatapro#128]
I find the uppercase and lowercase versions of theta hard to distinguish at a glance, specially at small sizes. Part of the issue is that they look as if they had the same width.

Perhaps the capital theta (Θ) could a bit wider, so that it *looks* at least as wide as the capital O? Or a bit rounder, like the 0? Or maybe there is some other way of making them more distinguishable.

Here is the character information from e-macs, and a close-up. I have included O, 0 and Q for comparison.

![screenshot_20181201_160610](https://user-images.githubusercontent.com/1593773/49329692-149aa480-f583-11e8-9bda-6a283a3193dc.png)
![screenshot_20181201_160627](https://user-images.githubusercontent.com/1593773/49329693-149aa480-f583-11e8-97c0-c457a98290d6.png)

**EDIT:** Another option is to make Θ more "squarish".

**Comment by fabrizioschiavi** [comment]
You've right. I'll fix this design asap. Thanks!

**Comment by fabrizioschiavi** [comment]
What do you think about this solution?
![theta-o-0](https://user-images.githubusercontent.com/1576663/53101838-d6ca6e00-352a-11e9-8d3a-78f6e2f84798.png)

**Comment by vlopezj** [comment]
It looks pretty good from here :+1:

Fabrizio Schiavi <notifications@github.com> skrev: (20 februari 2019 16:17:18 CET)

**Comment by fabrizioschiavi** [comment]
The fixed version for this issue is PragmataPro 0.828. Thanks for opened this issue!
