### ISSUE TITLE
What is going on here?

### ISSUE THREAD

**Issue by jordwalke** [fabrizioschiavi/pragmatapro#13]
I'm using this new Pull Request for Macvim which adds ligature support. Haskelig and Fira Code both work fine, but then Pragmata Pro has these issues where standard words like "back" are turned into back arrows.

The following line is supposed to say "callback"

<img width="211" alt="screen shot 2015-11-08 at 2 15 15 am" src="https://cloud.githubusercontent.com/assets/977348/11019792/d391e14c-85be-11e5-87e8-01b389aab4df.png">

Kind of bummed I had to buy it just to learn it doesn't work like the other ligature fonts.

**Comment by jordwalke** [comment]
Oh, even the mono version without ligatures is rendered like this.

**Comment by fabrizioschiavi** [comment]
I got it.  MacVim enabled not just "liga" OpenType features but also "dlig" (discretionary legatures). 
If it's hard to fixed by MacVim team I can disable "dlig" features in PragmataPro also if it sounds a bit incorrect to me :(

**Comment by jordwalke** [comment]
I think they ended up fixing their pull request to address the issue (this is all hot off the press - not in the main MacVim release yet - we're testing aggressively but things are looking hopeful).

**Comment by jordwalke** [comment]
I think this is resolved. I haven't seen any issues with it again. It must have been related to early implementations of MacVim's ligatures.
