### ISSUE TITLE
Confusion around support for ligatures

### ISSUE THREAD

**Issue by alextes** [fabrizioschiavi/pragmatapro#130]
First of all, this font, I love it!<3

Today I spent quite a bit of time figuring out whether to buy or not because it appeared the font did not support ligatures. In the end, I figured it out and bought with confidence, I think it may be possible to lower this barrier and that way help more people buy this awesome font.

I found the PragmataPro (non-Mono) in a dark corner, version .820 or so, with which the ligatures got wrong sizes in NeoVim but worked fine in non-terminal apps such as MacVim. After reading a whole bunch of issues, I noticed an issue where someone was referring to a Liga version which I couldn't seem to find on the shop page. [This image](https://www.fsd.it/wp-content/uploads/2015/12/PragmataPro_PragmataProMono_EssentialPragmataPro.png) especially confused me as it seemed to suggest that if you wanted ligatures, you have to use the regular version with the multi-width glyphs which I think is what gives some editors and terminals a hard time. Then after discovering a mention of Liga, I found [this image](https://github.com/fabrizioschiavi/pragmatapro/raw/master/useful_files/Handbook.png) which made it clear there is now a Mono version _with_ ligatures. If that first image was updated to include the Liga name, and perhaps also the shop page contained a section explicitly demonstrating the PragmataPro Mono Liga variant looking great in terminals then I think the decision may become more comfortable for a bunch of terminal fans like me.

The price is also a tad high. Perhaps a Mono+Ligatures _only_ version would also help get your font in more hands. Today I was happy to work at a company that lets me spend 250 bucks on art 😉 .

Thanks again for a fantastic font.

**Comment by fabrizioschiavi** [comment]
You’ve totally right. I’ll replace the image that create confusion. Thanks for letting me know this!

**Comment by alextes** [comment]
Want me to leave this open or can I close it?

**Comment by fabrizioschiavi** [comment]
Are this new picture more clear?

![PragmataPro_packs_structure](https://user-images.githubusercontent.com/1576663/55557804-f4265680-56ea-11e9-9e41-971b6fc81e9f.png)

**Comment by Porges** [comment]
@fabrizioschiavi shouldn't the ligatures fonts have "Liga" in the name?

**Comment by fabrizioschiavi** [comment]
You've right George! Thank you!!
![PragmataPro_packs_structure](https://user-images.githubusercontent.com/1576663/55618963-0d391100-5798-11e9-9e8a-86de86fd05c0.png)

**Comment by alextes** [comment]
Yes, this is exactly what would've reduced my decision time from ~1 hour to minutes! Great work @fabrizioschiavi 👌 .
