### ISSUE TITLE
Glyph for ģ could be better

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#131]
At the moment `ģ` looks like a “g with acute” but it could look more like a turned comma, to match the uppercase and the description of the character:

Example in Pragmata Pro:
![image](https://user-images.githubusercontent.com/12575/50494639-6a327600-0a89-11e9-9511-5b04f2dcaa13.png)

Example from Arial:
![image](https://user-images.githubusercontent.com/12575/50494661-89310800-0a89-11e9-800f-05e5795c6a88.png)

**Comment by Porges** [comment]
Idea of what it could look like:

![image](https://user-images.githubusercontent.com/12575/50494690-a82f9a00-0a89-11e9-8ad7-b9b3ef9092b3.png)

**Comment by fabrizioschiavi** [comment]
You've absolutely right! Thank you for this. I'll fix it soon

**Comment by fabrizioschiavi** [comment]
Fixed. Now `ģ` has a more correct design. Thanks again!
