### ISSUE TITLE
Ligature did not showed in my Visual Studio

### ISSUE THREAD

**Issue by Rizary** [fabrizioschiavi/pragmatapro#133]
Hi, 

I already change my fonts to Pragmata Pro Mono, but the ligature didn't show up in my Visual Studio.

Should I have additional step to make it available?

**Comment by Rizary** [comment]
nevermind, I think the error comes from VS

**Comment by Rizary** [comment]
I re-open, because when I try FiraCode, It works perfectly with the ligature. But with PragmataPro, it is not.

**Comment by graycrow** [comment]
Pragmata Pro Mono **Liga** is the font with ligatures, you probably using one without.

**Comment by Rizary** [comment]
@graycrow I need the ligature. Well, the Pragmata Pro Liga, works fine in VSCode and Visual Studio 2017.

**Comment by fabrizioschiavi** [comment]
I think you PragmataPro **Mono Liga** does what you looking for

**Comment by voronoipotato** [comment]
What ligature are you trying to use? Do any of them work? I'm currently trying to figure out how to use any of the StyleSets with vscode/visual studio.

**Comment by Rizary** [comment]
@voronoipotato 

I use the `Pragmata Pro Liga` for vscode and vs, it works for me.

but when I use `Pragmata Pro **Mono** Liga`, it doesn't.

**Comment by PharaohJoe** [comment]
The ligatures from both PragmataPro Mono Liga and PragmataPro Liga are not working for me in Visual Studio 2019

**Comment by akrsnr** [comment]
Still not working as well as in Jetbrain's IDEs

**Comment by fabrizioschiavi** [comment]
Have you tried with the new [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) 0.829? 
Please let me know if there are again issues using Visual Studio. Thank you!

**Comment by BeatScherrer** [comment]
don't forget that there's also this vscode setting:
```
  "editor.fontLigatures": true,
```

**Comment by tangentlin** [comment]
I have purchased today (March 6, 2023) `Essential PragmataPro` and installed on my Mac, I have also enabled Ligatures in VSCode, I cannot see the Ligature.  Do I need to have Pragmata Pro Mono to have the ligature feature?
