### ISSUE TITLE
Shop issue (invalid link)

### ISSUE THREAD

**Issue by corelon** [fabrizioschiavi/pragmatapro#135]
Hi,

I logged in my account without any issue. When I click on the link to download 0.827 I get a message that the link is invalid and I should go to the shop.
Any idea why?

Thanks in advance.

**Comment by fabrizioschiavi** [comment]
I forgot to rebuild the old IndieGoGo order at my site. Sorry. Now it must works. Please confirm. Thank you!

**Comment by corelon** [comment]
Just tested and the link works.
By the way the old/broken link is still there :)
Thank you for the help
