### ISSUE TITLE
Issue with space of -> ->> when using emacs

### ISSUE THREAD

**Issue by FieryCod** [fabrizioschiavi/pragmatapro#137]
First of all, thank you for your effort in making so fabulous font! It's a pleasure to read the code with PragmataPro! However lately this day I've found issue with space some ligatures take in Emacs buffer. For instance, the following ligatures take (in Emacs):
```
-> - only one character
->> - only two characters
```
while those should take 2, 3 respectively. This is pretty annoying when doing some lisp:
```
(-> abc
   def
   ghi
 )
``` 
As you can probably guess those `def` `ghi` are automatically indented to `>` while those should be indented to the first letter of the word. Just checked and it seems that for `Visual Studio Code` the ligatures take the correct space, so it seems to me that it's either somewhere in the script published within this repo or it's a "feature" of `prettify-symbols-mode`.

**Comment by fabrizioschiavi** [comment]
Very strange… I'll try to fix it. Thanks @FieryCod !

**Comment by FieryCod** [comment]
Thank you @fabrizioschiavi!

**Comment by fabrizioschiavi** [comment]
I'll check better your issue notification and I must correct you when you write:
```
-> - only one character
->> - only two characters
```
in reality:
```
-> two character: - and >
->>  three characters: -, >, and >
```

**Comment by FieryCod** [comment]
@fabrizioschiavi I can confirm that the issue no longer exists! Thank you so much!
