### ISSUE TITLE
Comonadic ligatures =>=, =<=, ->-, -<-

### ISSUE THREAD

**Issue by matux** [fabrizioschiavi/pragmatapro#138]
Love the font, been using it for quite awhile.

Hope these Haskell ligatures are doable, they are less common and not part of the stdlib, but they've become standard at the community level.

[->-](https://hackage.haskell.org/package/semigroupoids-5.3.2/docs/Data-Functor-Bind.html#v:-45--62--45-) and [-<-](https://hackage.haskell.org/package/semigroupoids-5.3.2/docs/Data-Functor-Bind.html#v:-45--62--45-) render quite well already, so I'm actually quite content the way they are now.

Main issue is [=>=](https://hoogle.haskell.org/?hoogle=%3D%3E%3D) and [=<=](https://hoogle.haskell.org/?hoogle=%3D%3C%3D). These are the [dual](https://en.wikipedia.org/wiki/Duality_(mathematics)) of the monadic Kleisli arrows [>=>](https://www.stackage.org/haddock/lts-13.15/base-4.12.0.0/Control-Monad.html#v:-62--61--62-) and [<=<](https://www.stackage.org/haddock/lts-13.15/base-4.12.0.0/Control-Monad.html#v:-62--61--62-). Trouble is, since greater than (`≥`) and less than (`≤`) are rendered besides the first equals sign, they turn the arrows into pretty much an illegible glitch.

![Image](https://cl.ly/54c17e6980a1/Image%202019-04-01%20at%209.30.02%20PM.png)

At the very least, would it be possible to avoid rendering `≤` and `≥` if there's a conflicting symbol besides it?

Thank you, Fabrizio. I've become truly fond of your font. I had never used a condensed font and it was a bit tough to get used to that in the beginning. Nowadays, I just can't imagine myself using any other font.

**Comment by fabrizioschiavi** [comment]
Thank you Matias for these ligature request and for supporting PragmataPro! I'll add =>=, =<=, ->-, -<- asap.

**Comment by fabrizioschiavi** [comment]
![Screen Shot 2019-08-04 at 19 54 42](https://user-images.githubusercontent.com/1576663/62427319-bca7d500-b6f1-11e9-9b27-4d51bc4ca69f.png)
Available since version 0.828
