### ISSUE TITLE
NixOS/Nix icon

### ISSUE THREAD

**Issue by sondr3** [fabrizioschiavi/pragmatapro#139]
I was wondering if it would be possible to add the icon for NixOS to PragmataPro? I see a few Linux distros are in the Private Use Area already, and I'd love it if it would be possible to also have the NixOS logo there too: https://nixos.org/logo/nixos-logo-only-hires.png.

Thanks for an amazing font!

**Comment by fabrizioschiavi** [comment]
PragamataPro uses the same [Nerd fonts](https://github.com/ryanoasis/nerd-fonts) position in Private Use Area. Probably is a good idea to request this logo in [Nerd fonts](https://github.com/ryanoasis/nerd-fonts) repository to avoid conflicts and keeping a sort of standard.
Thank you!
cc: @ryanoasis

**Comment by fabrizioschiavi** [comment]
No problem, I just found NixOS logo in Nerd fonts, it’s positioned at U+F313.
Just added to PragmataPro next release.

**Comment by fabrizioschiavi** [comment]
The most part of Nerd fonts into PragmataPro 0.828 was updated. Thanks!
