### ISSUE TITLE
Underlines in Terminal.app

### ISSUE THREAD

**Issue by olivertaylor** [fabrizioschiavi/pragmatapro#14]
This command should print the word 'Hello" underlined.

``echo -e '\033[4mHello'``

However, as you can see below, this doesn't work.

![pragmata_underline](https://cloud.githubusercontent.com/assets/1388093/11992257/3e596fb2-a9d8-11e5-9771-35b65f53c5aa.png)

I'd assume this is a terminal bug, but it works fine with other fonts.

**Comment by fabrizioschiavi** [comment]
Thanks for letting me know. I'll find why it doesn't work

**Comment by fabrizioschiavi** [comment]
In my Terminal it works
![screen shot 2015-12-31 at 13 38 35](https://cloud.githubusercontent.com/assets/1576663/12064473/f10af5a4-afc3-11e5-8443-9ac3132b74a4.png)
My Mac OS version is still 10.9.5, probably it doesn't work in more recent versions

**Comment by olivertaylor** [comment]
I’m on 10.11.2

**Comment by Shirk** [comment]
@olivertaylor - doesn't look like an issue with Pragmata but rather with the line spacing applied by Terminal.app. I'm on 10.11.4 and if I enter just your command I get `Hello` with underline and then a split second later the underline is overdrawn with the next prompt. But If I then press enter a few times the underline reappears.

It also works out-of-the-box on a recent version of iTerm2 so it looks pretty much like Terminal.app thing.

**Comment by olivertaylor** [comment]
Yeah. I came to the same conclusion.

**Comment by lloeki** [comment]
@Shirk This should really be `echo -e '\033[4mHello\033[0m'`
