### ISSUE TITLE
[TODO] and similar ligatures missing from MonoLiga-Italic

### ISSUE THREAD

**Issue by vectorstorm** [fabrizioschiavi/pragmatapro#141]
It seems that a number of recently added ligatures, such as [TODO] and [FIXME] and [WARNING] and similar haven't made it into all styles of the font.

As of release version 827, the ligatures ARE present within:
- PragmataProLiga-Regular
- PragmataProLiga-Italic
- PragmataProLiga-Bold
- PragmataProLiga-BoldItalic
- PragmataProMonoLiga-Regular

These ligatures are NOT present in:
- PragmataProMonoLiga-Italic
- PragmataProMonoLiga-Bold
- PragmataProMonoLiga-BoldItalic

Can these fun ligatures be added to the font styles where they're missing?  I make possibly too much use of the mono liga italic style, and I very much miss getting to use them.  :)

**Comment by fabrizioschiavi** [comment]
Thanks for letting me know. Just fixed for the version 0.828 soon available

**Comment by fabrizioschiavi** [comment]
Fixed. Thanks again
