### ISSUE TITLE
Add symbol for PHP concatenation .=

### ISSUE THREAD

**Issue by marioblokland** [fabrizioschiavi/pragmatapro#142]
Hi Fabrizio, 

I would like to have a ligature for the concatenation operation in PHP. Currently it looks like the following: `.=`

I would like to have it maybe as in Fira Code or similar: 

![Screenshot 2019-04-25 at 09 15 54](https://user-images.githubusercontent.com/17354785/56716482-ca38e080-673a-11e9-816c-3281f6addf2d.png)

Do you think that this would be possible?

**Comment by fabrizioschiavi** [comment]
Thanks Mario!
For me this ligature is `period centered` + `equal` and I always ignored it because can create misinterpretation.
Anyway if it's needful I can make an exception.

**Comment by wismill** [comment]
I would rather not have this. Same argument as #67 : _the ligatures should bear a close resemblance to the glyphs that comprise it_.

There are so many contexts where PragmataPro can be used that it should not take sides for a particular use. Maybe the OpenType features (stylistic sets?) could be used for specific demands?

**Comment by marioblokland** [comment]
Alright I understand. Thank you for your quick answer and explanation Fabrizio.
