### ISSUE TITLE
[WARN] [TODO] etc in iTerm

### ISSUE THREAD

**Issue by hojberg** [fabrizioschiavi/pragmatapro#143]
For some reason these seems to work in Terminal.app, but not iTerm on a mac. Other ligatures work fine.

**Comment by garand** [comment]
@hojberg Hey! I discovered this as well and brought it up to @gnachman. [Here is the GitLab ticket with the solution.](https://gitlab.com/gnachman/iterm2/issues/7461)

**Comment by gnachman** [comment]
Yeah, that's my bug, not PragmataPro's. For performance reasons, I don't consider letters as candidates for ligatures.

**Comment by hojberg** [comment]
Gotcha. Closing this then. Thank you :)
