### ISSUE TITLE
[| and |] for array brackets in OCaml/ReasonML

### ISSUE THREAD

**Issue by hoichi** [fabrizioschiavi/pragmatapro#144]
Hi Fabrizio! Could you please add `[|` and `|]` ligatures? I miss them working with ReasonML (and, occasionally, OCaml). They’re used for arrays (the usual brackets are for linked lists).

Obviously, the empty array literal, `[||]`, is better grouped like `[| |]` than `[ || ]`.

And thanks for your terrific work!

**Comment by fabrizioschiavi** [comment]
Thanks for proposed it but I think it is not a good choice because it can create issues like [this](https://github.com/fabrizioschiavi/pragmatapro/issues/119#issue-366824593)

**Comment by hoichi** [comment]
Well, I don’t know, Fira Code manages to support it somehow. Granted, it’s the only font I know of that has these ligatures, but it seems possible.

Besides, not sure the case with repeating brackets can apply here. Do you mean something like `[| 1, 2, [| 3, 4 |] |]`? Or some lone pipes? Neither is possible in OCaml/ReasonML, but maybe someone knows some languages where that danger does exist?
