### ISSUE TITLE
Multiple math symbols misaligment issues.

### ISSUE THREAD

**Issue by vblazhkun** [fabrizioschiavi/pragmatapro#146]
There are some misalignments while checking math rendering with Markus Kuhn's UTF8 demo file (marked with red circles).

![image](https://user-images.githubusercontent.com/7956686/62571469-1c40e480-b89a-11e9-84de-a779fc5b3468.png)

I am attaching the given test file for further improvements of the font.
[UTF-8-demo.txt](https://github.com/fabrizioschiavi/pragmatapro/files/3473883/UTF-8-demo.txt)

**Comment by fabrizioschiavi** [comment]
Thanks! I'll fix it soon

**Comment by fabrizioschiavi** [comment]
I think [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) 0.829 has no more this misalignment:

![Screenshot 2021-05-19 at 19 09 08](https://user-images.githubusercontent.com/1576663/118855246-de2d7d00-b8d5-11eb-818c-31f9c5a06e2c.png)
