### ISSUE TITLE
Macron placement in 0.828

### ISSUE THREAD

**Issue by mxpiotrowski** [fabrizioschiavi/pragmatapro#147]
Hi,

I just noticed that in the regular cuts (but not italic, bold, and bold italic) of PragmataPro and PragmataPro Mono 0.828, the macron is positioned incorrectly on most of the Latin letters with macrons that exist in precomposed form (i.e., ĀāĒēĪīŌōŪūȲȳḠḡ).  This is on MacOS 10.14.6.  (Surprisingly the characters are fine in Emacs…)

![Screen Shot 2019-08-07 at 16 42 17](https://user-images.githubusercontent.com/4598053/62632761-4beffb00-b933-11e9-8a74-b23588ce2c91.png)

Thanks and greetings

**Comment by fabrizioschiavi** [comment]
I know this but this request conflicts with #117 
I don’t know what is the correct solution to adopt 😞

**Comment by Porges** [comment]
Hmm, U+00AF (from #117) is meant to be spacing, not combining, U+0304 is the combining version?

**Comment by fabrizioschiavi** [comment]
This has sense @Porges ! I’ll fix it following your suggestion. Thanks!

**Comment by mxpiotrowski** [comment]
Thanks!

**Comment by wismill** [comment]
@Porges is right, the diacritical marks often come in pairs (combining, modifier). See the detail of each character at [corresponding Unicode charts](https://www.unicode.org/charts/PDF/U0300.pdf) for instance.

I've noticed that the dotted circle ◌ (U+25CC), which is used for demo of DM is also buggy: `◌̂ ◌̃ ◌̄`.

Also, it would be great if it could work on the [mathematical alphanumeric symbols](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols): 
```
U+0303 R̃ 𝐑̃ 𝑅̃ 𝑹̃ ℛ̃ 𝓡̃ 𝔕̃ 𝕽̃ 𝕉̃    r̃ 𝐫̃ 𝑟̃ 𝒓̃ 𝓇̃ 𝓻̃ 𝔯̃ 𝖗̃ 𝕣̃
U+0305 R̅ 𝐑̅ 𝑅̅ 𝑹̅ ℛ̅ 𝓡̅ 𝔕̅ 𝕽̅ 𝕉̅    r̅ 𝐫̅ 𝑟̅ 𝒓̅ 𝓇̅ 𝓻̅ 𝔯̅ 𝖗̅ 𝕣̅ 
```

Note that there [are](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) [lots](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks_Extended) [of](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks_for_Symbols) [combining](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks_Supplement) [marks](https://en.wikipedia.org/wiki/Combining_Half_Marks), some very useful in mathematics.

@fabrizioschiavi should we generate a test file with an exhaustive list of combinations?

**Comment by fabrizioschiavi** [comment]
A lot of new hard work… 😉
Thank you @wismill for your useful hints!

**Comment by wismill** [comment]
@fabrizioschiavi As the topic of this issue is the macron, it may be best to focus first on the combining marks dedicated to natural languages.

PragmataPro is amazing. Thanks for your hard work. Keep it up!

**Comment by Porges** [comment]
@fabrizioschiavi do you have a timeline for the release of 0.829? it would be great to have this fixed 🙂

**Comment by fabrizioschiavi** [comment]
You’ve right @Porges 😔 sorry for this delay. I’m very busy with other projects at the moment but this December I’ll continue to work at PragmataPro 0.829, so I hope to finish it at the start of the 2021

**Comment by fabrizioschiavi** [comment]
Hello people!
After a very hard work now all the _Mathematical Alphanumeric Symbols_ glyphs can be accented like other standard letters using _Combining Diacritical Marks_ set. Not only _macron_ positioning.
[PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) now pass also the _soft dotted_ proof 😄

![Screenshot 2021-05-19 at 18 20 58](https://user-images.githubusercontent.com/1576663/118849149-bdfabf80-b8cf-11eb-820a-6eabc648ca21.png)

Thank you to all for these smart suggestions!

**Comment by Porges** [comment]
Looks great!
