### ISSUE TITLE
Nota bene ligature request

### ISSUE THREAD

**Issue by krismolendyke** [fabrizioschiavi/pragmatapro#149]
Hello!

I am a recent customer and very happy with my purchase.  I'm also impressed with your continuous improvements and interactions here – thanks!

I would like to request a ligature for [nota bene](https://en.wikipedia.org/wiki/Nota_bene).  Perhaps it could join the others as in https://github.com/fabrizioschiavi/pragmatapro/issues/134#issuecomment-518024137?  There are some more interesting options discussed in [this StackOverflow question](https://tex.stackexchange.com/questions/483627/n-b-ligature-in-latex), too.  I read and write a lot of code with comments like `# NB Here be dragons` 😉 and it would be nice to see those be more easily distinguishable.  Thanks again!

**Comment by fabrizioschiavi** [comment]
Very interesting request!
I'll try to add at the next release. Thank you!

**Comment by fabrizioschiavi** [comment]
<img width="802" alt="Screenshot 2023-08-03 at 18 27 14" src="https://github.com/fabrizioschiavi/pragmatapro/assets/1576663/40c554f0-66c9-4a01-af63-1a0c33201100">
Do you like this unseen before Nota Bene symbol?

**Comment by krismolendyke** [comment]
I like it, thanks!

**Comment by fabrizioschiavi** [comment]
Added! Please re-download the font files from fsd.it

**Comment by yuretz** [comment]
That's awesome. Thank you @fabrizioschiavi! How do I type it in my editor?

**Comment by fabrizioschiavi** [comment]
The codepoint of Nota Bene symbol is `U+100010` but the ligature is to be defined.
What combination do you suggest? `NB!`? `NB:`?

**Comment by yuretz** [comment]
Thanks! I usually use it like `NB: some note`

**Comment by fabrizioschiavi** [comment]
So the ideal can be `NB:`: typing `:` two times to see `NB: some note` as result

**Comment by yuretz** [comment]
Well, typing colon two times would feel strange to me. Could colon be somehow incorporated in the symbol itself?
