### ISSUE TITLE
Are glyphs exactly double width?

### ISSUE THREAD

**Issue by jordwalke** [fabrizioschiavi/pragmatapro#15]
I saw the following issue with emacs' mac port, which occurs with other ligature programming fonts:
https://github.com/railwaycat/emacs-mac-port/issues/96

I believe that people building editors have to be careful to not disrupt layout of lines when ligatures are present. Wouldn't this automatically work itself out if `=>` was rendered as a single glyph that had double width, with the arrow glyphs centered perfectly? Is this how `pragmatapro` works right now? Should it?

**Comment by fabrizioschiavi** [comment]
Correct. 
PragmataPro has the most part of glyphs with the width 1060em, ligatures are 2120em (x2) and 3180em (x3). Unfortunately I found troubles with the contemporary antialiasing systems. Often the rasterization of the widths is almost random
Anyway I'll check if is possible to avoid these issues
Thanks!
