### ISSUE TITLE
New ligatures, e.g. # TODO aren't working in 0.828

### ISSUE THREAD

**Issue by TyLeRRR** [fabrizioschiavi/pragmatapro#150]
The new "hashtag" ligatures (# TODO) aren't working on macOS. No problems with square brackets ligatures. 

IDEs affected: Jetbrains Products, Neovim, iTerm2, Vim, VSCode, etc. 

System: macOS 10.14.5

Further info can be found in this [tweet](https://twitter.com/fabrizioschiavi/status/1159067875090546688) discussion.

Gladly provide more information.

**Comment by ahmedelgabri** [comment]
Wanted to add that this is also happening on macOS 10.14.6 & works fine only in textedit.app…

<img width="662" alt="Screen Shot 2019-08-09 at 20 29 04" src="https://user-images.githubusercontent.com/63876/62801187-7c779680-bae5-11e9-854b-0e2ad040e235.png">

**Comment by fabrizioschiavi** [comment]
Could you try to  delete the font cache, please?
If nothing happens could you send me the output of this command: `atsutil fonts -verify`
please?

**Comment by TyLeRRR** [comment]
Closed all applications. Cleared the font cache with `sudo atsutil databases -remove` and restarted Mac. 
**Result**: hashtag ligatures now working in TextEdit, partially in Jetbrains Products and don't work in iTerm2.

With _partially_ a mean following:
![pragmata_0828](https://user-images.githubusercontent.com/7289706/62820988-3534e880-bb6d-11e9-9930-77d8d5b9c2e5.gif)

The output of `atsutil fonts -verify` --> `2019-08-10 12:49:33.557 atsutil[859:30333] No inconsistencies found`.

**Comment by ahmedelgabri** [comment]
I did the same as @TyLeRRR & even restarted my laptop. Same as before, not working anywhere except textedit.app 

```
$  atsutil fonts -verify
2019-08-10 13:43:51.016 atsutil[2871:21405] No inconsistencies found
```

**Comment by fxfactorial** [comment]
Also tried and no results in emacs, did clear cache and reboot.

**Comment by DannyJJK** [comment]
> With _partially_ a mean following:
> ![pragmata_0828](https://user-images.githubusercontent.com/7289706/62820988-3534e880-bb6d-11e9-9930-77d8d5b9c2e5.gif)

This looks like it's an issue to do with the syntax highlighting, it works for me in GoLand.

Doesn't work in VS Code, but works in Terminal.app and TextEdit.app. I'm incredibly happy with this font though and I really appreciate all the work going into it, I know these issues are complicated

**Comment by Porges** [comment]
I think it is the syntax highlighting, notice that the `#` is coloured different to the `TODO`? they're probably in different text spans and the ligature can't cross them

**Comment by vladimir-poleh** [comment]
It's not a font issue. JetBrains products and some other editors use special highlighting for the TODO comments that breaks this ligature.

**Comment by fabrizioschiavi** [comment]
Thank you Vladimir!!

**Comment by nomasprime** [comment]
Doesn't work in iTerm.

@fabrizioschiavi think this issue needs reopening until a solution can be found.

**Comment by nomasprime** [comment]
@fabrizioschiavi tried this https://gitlab.com/gnachman/iterm2/issues/7461

`[]` ligatures work but `#` ones don't.

**Comment by preachermanx** [comment]
This is still an issue for me in VSCode does anyone have a workaround?
