### ISSUE TITLE
This font is

### ISSUE THREAD

**Issue by cata0309** [fabrizioschiavi/pragmatapro#152]
Awesome ! 
This is not a typical issue so you can close it after you read it !
Thank you for your amazing work ! I recently found a discussion about your hard start from indiegogo in 2011, I want you to know that I support you and encourage you do continue your work ! It's a great font and you made a tremendous amount of work to get the font at its current state.
Thank you !

**Comment by fabrizioschiavi** [comment]
This is the best issue ever 😃 ! 
Thank you really much @cata0309 !
