### ISSUE TITLE
Licensing Clarification

### ISSUE THREAD

**Issue by admiralbumblebee** [fabrizioschiavi/pragmatapro#154]
Currently the website license does not seem specify if this license is applicable for desktop usage. Given that this may be part of the development (for some languages), this is potentially an important distinction.

If the website license is purchased, can this be used for a single dest desktop? If not, please specify.

**Comment by fabrizioschiavi** [comment]
Sorry for the delay in reply. TTF files of web site pack are technically not usable as desktop font. Thanks for asking
