### ISSUE TITLE
Ligatures cause small font size in Windows Terminal

### ISSUE THREAD

**Issue by bts** [fabrizioschiavi/pragmatapro#155]
In the [new Windows Terminal](https://github.com/microsoft/terminal), ligatures in PragmataPro are rendered with a very small font size/line height. I'm not sure whether this is a PragmataPro issue or a Terminal issue, but Windows Terminal does not have any issues with other ligature-enabled fonts like Fira Code.

I am currently using PragmataPro 0.822.

![ligature](https://user-images.githubusercontent.com/5743/66842496-5e8d3e80-ef39-11e9-8571-df78ef2c2f0c.png)

Thank you for the awesome font. I really enjoy PragmataPro.

**Comment by vladimir-poleh** [comment]
I can't confirm this behavior for the Windows Terminal version 0.6.2951.0.

**Comment by bts** [comment]
Using the latest version of PragmataPro this is no longer an issue for me. Thanks!
