### ISSUE TITLE
Wrong glyph і (U+0456) in Mono Bold of 0.828

### ISSUE THREAD

**Issue by amerlyq** [fabrizioschiavi/pragmatapro#156]
Regression(critical): characters U+0456 and U+0458 are wrong in Bold Mono (both liga/non-liga).

ALSO:(non-critical): Similar problem with U+012f.
And U+0296 is incomprehensibly h-mirrored in both mono/non-mono Bold.

There were some other glitches with italics but I temporarily give up :)
Visually comparing overlayed charsets rendered in different styles and searching glitches is harsh :(

**Comment by fabrizioschiavi** [comment]
You've perfectly right 😲 
I'll fix soon. Thank you!

**Comment by VincentKueszter** [comment]
Have you considered integrating an image diff tool into your workflow to check for such regressions?

**Comment by amerlyq** [comment]
@fabrizioschiavi I would really appreciate if you could update 0.828 with only "U+0456" symbol swapped to correct one and postpone other changes to 0.829 as label says.

Because waiting half a year for 0.829 is not an interesting agenda at all: it's unnerving when browsing the filesystem and emboldened names under cursor abruptly change outline. In the first place filemanager cursor is where you focus the attention the most, even in half-sleeping state:
![20191205_184911_808x128](https://user-images.githubusercontent.com/5730096/70256168-ad649100-1790-11ea-9ee8-f87219bebf54.png)

@VincentKueszter it's actually interesting idea and some time in the past I even implemented it for another purpose -- comparing quality of scanned books when converted to .djvu. And what saddened me the most at that time was tediousness to detect and classify defects even if they are present. Focusing too much on diff is rather draining. 

However, in the fonts business it may be worth a try -- because you can render fonts in the same way each time. Still for testing you must write convenience scripts to split image char grid into cells and compare each cell separately for difference -- to report only changes instead of verifying each char manually.  But it will only detect regressions between versions:
* It won't find problems which are already present in font typeface. 
* And you won't be able to compare different typefaces like bold/italic between themselves to find mistakes of transferring. 

Still it's worth a try -- if somebody has energy to write such scripts or knows some existing soft sufficiently able to do so.

**Comment by fabrizioschiavi** [comment]
Fixed!
Thank you @amerlyq to letting me know this issue!
