### ISSUE TITLE
Emacs settings

### ISSUE THREAD

**Issue by meem-zay** [fabrizioschiavi/pragmatapro#157]
Hi,

Can you please share a complete Emacs settings to use PragmataPro Mono Liga font.

&mdash; 
_Emacs Newbie_

**Comment by fabrizioschiavi** [comment]
**Quick solution** 
Copy and paste this code `(set-frame-font "PragmataPro Liga 14" nil t)` on an empty file you'll name `.emacs` and put it in your user folder.
`14` is the point size, you can change the number to increase or reduce the point size
