### ISSUE TITLE
Are there any arrows aligned to box drawings?

### ISSUE THREAD

**Issue by amerlyq** [fabrizioschiavi/pragmatapro#159]
Take for example `─→a`.
In, let say *some*, Qt applications horizontal line and arrow are aligned for PragmataPro.
But in terminal with PragmataPro Mono... they are never aligned *sigh*.

I see the point of arrow being slightly below box center -- to be aligned on the baseline of actual text and point to the center of the letter. 
Therefore in theory arrows and drawings *must* never align at all.
And still I deeply regret there are no arrows in box drawing set.
Or... are there?

**Comment by fabrizioschiavi** [comment]
Unicode Box Drawing set desn't include any arrows. 
In the example `─→a` ,  `─` has the priority and the following glyphs like `→` are automatically aligned to `─`. If you try to digit `→a` you can note that arrow is already aligned to lowercases (the default position).
I'll investigate how to improve this situation avoiding absurd conflicts

![PragmataPro-Box-drawing-calt-w](https://user-images.githubusercontent.com/1576663/69946281-a1a47080-14eb-11ea-8a4f-47428f934d6e.png)

**Comment by amerlyq** [comment]
I think the keyword here is 

> in terminal with PragmataPro Mono

Because... auto alignement on priority char expects support from GUI app, right?
It seems like "st" doesn't support it, at least in its full meaning:
![20191202_192629_789x259](https://user-images.githubusercontent.com/5730096/69980832-b14aa600-1539-11ea-891a-b5dfe1ba1bad.png)

The only thing I noticed -- is after pressing space after each term, horizontal line of box drawings slightly elongates, but arrow vertical alignment remains the same.

**Comment by fabrizioschiavi** [comment]
Since [v_0.829](https://fsd.it/shop/fonts/pragmatapro/) this issue was fixed.
No more vertical misalignments

![Screenshot 2021-05-19 at 18 36 27](https://user-images.githubusercontent.com/1576663/118850817-6f4e2500-b8d1-11eb-8740-20710e5ec895.png)

Thank you @amerlyq !
