### ISSUE TITLE
Slight gap in drawings

### ISSUE THREAD

**Issue by amerlyq** [fabrizioschiavi/pragmatapro#160]
It's not much notable but still slightly irritates when you look at it in your prompt 12 hours each day contiguously month after month.
Drawings gap appeared and disappeared between PragmataPro versions, becoming more or less of the issue.
And I feel like with 0.828 it had become bigger. Again.

On some font sizes the gap is less visible, but on others -- it gapes.
Look for aliased and antialiased examples, notice two gaps -- vertical and less visible horizontal one:

![20191202_015806_1205x224](https://user-images.githubusercontent.com/5730096/69922789-f58d6600-14a7-11ea-9a44-466b2a735335.png)
![20191202_015808_1205x224](https://user-images.githubusercontent.com/5730096/69922790-f58d6600-14a7-11ea-8495-bfce17d93560.png)
![20191202_015810_1205x224](https://user-images.githubusercontent.com/5730096/69922791-f625fc80-14a7-11ea-99a7-354f10b433bd.png)

**Comment by fabrizioschiavi** [comment]
I'll improve this soon, if possible

**Comment by fabrizioschiavi** [comment]
Much probably there are no more slight gaps (coming from Nerd symbols) since v_0.829.
Please confirm it. Thank you!
