### ISSUE TITLE
Named stylistic sets

### ISSUE THREAD

**Issue by Tekl** [fabrizioschiavi/pragmatapro#163]
Instead of just numbering the style sets you could give them names like in the Fonts Hasklig or Source Code Pro.

![image](https://user-images.githubusercontent.com/3667947/72533881-308c0300-3876-11ea-9e1c-c61896fd35e6.png)

**Comment by fabrizioschiavi** [comment]
I’ll add this new improvement with pleasure (finally OpenType supports this kind of naming!!)

**Comment by pindab0ter** [comment]
Awesome! Can't wait!

**Comment by fabrizioschiavi** [comment]
This is the Stylistic Set panel of [PragmataPro](https://fsd.it/shop/fonts/pragmatapro/) since v_0.829

![Screenshot 2021-05-19 at 17 38 49](https://user-images.githubusercontent.com/1576663/118842213-49bd1d80-b8c9-11eb-9516-ef97e89ed033.png)

Thank you!!
