### ISSUE TITLE
Fix inconsistent behaviour of # and [] ligatures or remove them

### ISSUE THREAD

**Issue by nomasprime** [fabrizioschiavi/pragmatapro#164]
The current situation is that even if the terminal supports them the editor might not and even then they break in between different syntaxes.

For example in NeoVim: # ligatures don't work; [] ligatures work when editing a Markdown file; [] ligatures don't work in Ruby.

Unless all the edge cases can be fixed the # and [] ligatures should be removed. The only other option is for the user to disable ALL ligatures which effectively renders them redundant.

**Comment by nomasprime** [comment]
iTerm's been especially [updated](https://gitlab.com/gnachman/iterm2/issues/7461) to render ligatures with spaces in them, thanks @gnachman.

Unfortunately `# …` ligatures don't render in Terminal or TextEdit either.

Issue's two weeks old now. Paid font, so hopefully there's some support?

**Comment by fabrizioschiavi** [comment]
I just designed a font and a font is not a complex file. I can investigate on these IDE issues but I can’t change their codes. 
I use Terminal and TextEdit almost every day but I never seen this kind of issue
![Screenshot 2020-02-12 at 22 14 00](https://user-images.githubusercontent.com/1576663/74377876-1990f000-4de5-11ea-8061-803f100cc044.png)
Could you share a screenshot of this issue, please? Thanks

**Comment by nomasprime** [comment]
Tried again and it's started working, possibly a caching issue.

Hopefully iTerm will support soon (see link in my previous comment).
