### ISSUE TITLE
Creative Commons license symbols

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#167]
Would you be able to add the Creative Commons license symbols that are new in Unicode 13.0?

There are 6 symbols [here](https://www.unicode.org/charts/PDF/U1F100.pdf) (I also highlighted the copy-left icon):
![image](https://user-images.githubusercontent.com/12575/79802409-05083f80-83b4-11ea-9431-5743627801d1.png)

The 7th is the circled equals (U+229C) which should be harmonious with the ones above.

**Comment by fabrizioschiavi** [comment]
Yes, absolutely. Thanks George!

**Comment by fabrizioschiavi** [comment]
Added and available since v_0.829
