### ISSUE TITLE
Move checkbox ligatures out of SS12.

### ISSUE THREAD

**Issue by phyllisstein** [fabrizioschiavi/pragmatapro#168]
The checklist ligatures are a really delightful way of leveraging and enriching how thoughtful PragmataPro is about code-related text, and the glyphs are gorgeous. Thank you, @fabrizioschiavi, for the work you put into them.

I do have one or two thoughts about their implementation, though. For one thing, locating this feature in `ss12` means that enabling it brings a number of unexpected ligatures along for the ride. In particular, the playing-card ligatures paint with a fairly broad brush. As soon as I enabled `ss12` in VSCode, I noticed that several bits of data in my `settings.json` file were being rendered in surprising and unexpected ways. I pulled the a couple cases I saw into TextEdit:

<img width="752" alt="TextEdit 2020-04-25 at 21 53 27@2x" src="https://user-images.githubusercontent.com/2207980/80296016-b1944980-8745-11ea-991a-11bc3a7da24f.png">

<img width="752" alt="TextEdit 2020-04-25 at 21 51 46@2x" src="https://user-images.githubusercontent.com/2207980/80296033-cb359100-8745-11ea-8fb5-03eb2ed0249f.png">

It’s a little counterintuitive. I initially joined @Tekl, in #89, in the suspicion that [it might be a bug](https://github.com/fabrizioschiavi/pragmatapro/issues/89#issuecomment-575238383). Only after some time and effort at “troubleshooting” did I trip over [`Handbook.rtf`](https://github.com/fabrizioschiavi/pragmatapro/blob/master/useful_files/Handbook.rtf) and work out what was happening.

It would be great if these substitutions could be moved to another feature set. One fairly obvious path could be to give them an `ss13` all their own. Frankly, though, from my point of view as a heavy user of the ligaturized font, I can’t think of many cases, outside of the intended Markdown-task use case, where character combinations like `- [ ]` appear in my code. From where I’m sitting, they’d be right at home in `calt`.

I have precisely zero insight into the forces and constraints you need to manage when organizing this stuff. That said, I suspect the checkboxes are actually _more_ disruptive in their current feature set than in a more general one, given that the playing cards, the whole-word substitutions, and the `fi`/`fl` ligatures capture such a wide range of character combinations.

Last, and least useful, quibble. The character combinations in PragmataPro’s definitions of task items are limited by their incompatibilty with common parser and renderer tools. [GitHub-Flavored Markdown](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists#creating-task-lists) and [Pandoc](https://pandoc.org/MANUAL.html#non-pandoc-extensions#extension-task_lists) both use `- [x]` to signal completion. From what I can tell, Org Mode does roughly the same by default.

By way of a for-instance, when you pass this list through GFM:

```markdown
- [ ] Do the thing.
- [-] Doing the thing.
- [v] Did the thing.
- [x] Not doing the thing.
```

...the way the renderer sees it turns out to be pretty groady:

<img width="758" alt="CleanShot 2020-04-25 at 22 52 30@2x" src="https://user-images.githubusercontent.com/2207980/80296280-7a269c80-8747-11ea-9d60-f3a86eca1279.png">

I can see perfectly solid arguments for refusing to pin your implementation, which is richer and lovelier anyway, to some ill-defined subset of all the plain-text markup tools in existence, each with its own slightly discordant design for this particular pattern. But, and again from a user’s limited perspective, the day-to-day usefulness of the feature is limited by the knowledge that PragmataPro would render `- [x]` to signal a canceled task only for GitHub to turn around and render it as a job well done.

Thanks so much, again, for the work you’ve already put into this. It’s yet another of the many charming details that make this typeface such a delight.

**Comment by fabrizioschiavi** [comment]
I’ll check this soon. Thank you!
