### ISSUE TITLE
Some accents too close when using 0.822  - 16px Windows

### ISSUE THREAD

**Issue by rnetocombr** [fabrizioschiavi/pragmatapro#17]
Pragmata Pro 0.822

Windows 8.1
Sublime Text 3
Font-size: 16px
Resolution: 1600x900

Tilde is fine in 15px:
![15](https://cloud.githubusercontent.com/assets/1286199/13828771/19169f3e-eba2-11e5-8f74-db879cd19ef0.png)

Tilde is too close in 16px:
![16](https://cloud.githubusercontent.com/assets/1286199/13828772/191b63d4-eba2-11e5-8146-cbe17e0d9632.png)

**Comment by fabrizioschiavi** [comment]
I'll fix this issue
Thanks Rui!
