### ISSUE TITLE
Better distinguish small (ß) and capital (ẞ) eszett

### ISSUE THREAD

**Issue by jfrankenau** [fabrizioschiavi/pragmatapro#172]
Looking at the [list of all characters](https://www.fsd.it/pragmatapro/All_chars.png) I find the lowercase (U+00DF) and uppercase (U+1E9E) variant of the German eszett (sharp s) hard to discern. I would propose to reduce the [capital eszett](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E) a bit in height (going wider I guess is not possible) and also make the top flat as it is done by other typefaces. See  be5invis/Iosevka#212 for a similar discussion on this topic.

**Comment by fabrizioschiavi** [comment]
Thank you for this improvement request! I'll work on it soon

**Comment by fabrizioschiavi** [comment]
Can I consider fixed with this design?

![Screenshot 2021-05-19 at 13 59 27](https://user-images.githubusercontent.com/1576663/118809101-77df3500-b8aa-11eb-9b92-c72c16a74eaa.png)

**Comment by jfrankenau** [comment]
Yes, that looks good. Thank you!
