### ISSUE TITLE
Make the En dash wider

### ISSUE THREAD

**Issue by jfrankenau** [fabrizioschiavi/pragmatapro#173]
I find it difficult to distinguish the Hyphen-minus (U+002D) from the En dash (U+2013). I would prefer to have it about halfway between the Hyphen-minus and the Em dash (U+2014) in length. One could consider to instead or also reduce the Hyphen-minus in length. As these three glyphs are commonly used they should be easily distinguishable.

**Comment by fabrizioschiavi** [comment]
Good idea, I’ll do it. Thanks!

**Comment by fabrizioschiavi** [comment]
Fixed, since [v_0.829](https://fsd.it/shop/fonts/pragmatapro/)

![Screenshot 2021-05-19 at 18 10 07](https://user-images.githubusercontent.com/1576663/118847006-9145a880-b8cd-11eb-82f0-4822fd58abd9.png)
