### ISSUE TITLE
Symbol Sizes Small PragmataPro Mono

### ISSUE THREAD

**Issue by TheSecEng** [fabrizioschiavi/pragmatapro#175]
I understand Mono fonts, however I think symbols are a bit to small in the mono versions.

Size 14 and the cmd symbol is so small that it is hard to distinguish 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/32599364/83426950-f6bf3180-a3fd-11ea-9af6-f6acb7aa6b7e.png">

Size 12 (Which is what I normally work in) and it is nearly impossible.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/32599364/83427035-1191a600-a3fe-11ea-8ddd-f7e42dfbde92.png">

Although the cmd symbol was used for the example, this is something across almost all symbols

⌘
⌥
⌃
⇧
→
←
↑
↓


the list continues.

**Comment by fabrizioschiavi** [comment]
I understand you very well, indeed I created the modular version.
I would like to improve readability of these symbols but the space available is very limited and I think to obtain already the best possible. 
![Screenshot 2020-06-01 at 18 07 12](https://user-images.githubusercontent.com/1576663/83428699-305e5f80-a433-11ea-82a6-0d6fa3b39a08.png)
Anyway I'll work on these symbols

**Comment by TheSecEng** [comment]
Modular version?

**Comment by fabrizioschiavi** [comment]
The fonts named `Pragmata Pro` are the modular version

**Comment by fabrizioschiavi** [comment]
New ⌘ since v_0.829

![Screenshot 2021-05-19 at 17 27 08](https://user-images.githubusercontent.com/1576663/118840470-b800e080-b8c7-11eb-85ae-af52b54c1d4f.png)
