### ISSUE TITLE
Graphics for legacy computing should always be single-width even in non-mono font

### ISSUE THREAD

**Issue by thomcc** [fabrizioschiavi/pragmatapro#176]
As it is they're mostly double-width in the non-mono font, but if you look at any actual, well, graphics from legacy computing or text art done in that style using those characters it won't look right in the non-mono font, since inevitably they'll have other characters, and will have been drawn assuming a mono font.

If you look at the example on the [unscii page](http://pelulamu.net/unscii/) for example:

PragmataPro (non-mono):

<img width="891" alt="Screen Shot 2020-07-09 at 5 25 51 PM" src="https://user-images.githubusercontent.com/860665/87103258-5ed91280-c209-11ea-8d35-6f302adeb50d.png">

PragmataPro Mono (has some issues but much much better):

<img width="636" alt="Screen Shot 2020-07-09 at 5 26 10 PM" src="https://user-images.githubusercontent.com/860665/87103308-8203c200-c209-11ea-86bd-541fdf8eb757.png">

Reference (unscii16):

<img width="638" alt="Screen Shot 2020-07-09 at 5 23 09 PM" src="https://user-images.githubusercontent.com/860665/87103294-7a441d80-c209-11ea-8e2b-3041fe9c1387.png">

---

It's hard for me to imagine the 1st is desirable to anyone, and it seems to defeat the point of the legacy characters somewhat... Well, one of the points of them.

Anyway thanks for the great font.

**Comment by fabrizioschiavi** [comment]
Oh wow! I'll fix it soon. Thanks to letting me know

**Comment by fabrizioschiavi** [comment]
Fixed since version [0.829](https://fsd.it/shop/fonts/pragmatapro/). 
This a sample of the modular version of PragmataPro. Thanks for your contribution!

![Screenshot 2021-05-19 at 16 36 41](https://user-images.githubusercontent.com/1576663/118832179-b1bb3600-b8c0-11eb-8c17-0a7c84faa427.png)
