### ISSUE TITLE
Some legacy computing graphic characters refer to wrong glyphs

### ISSUE THREAD

**Issue by thomcc** [fabrizioschiavi/pragmatapro#177]
In https://github.com/fabrizioschiavi/pragmatapro/issues/176 (filing as a separate issue because it's very much unrelated to the other) I mentioned that there seemed to be some weird rendering issues with even the Mono version of PragmataPro.

Actually, I think many of these are because some of the characters don't seem right between https://raw.githubusercontent.com/fabrizioschiavi/pragmatapro/master/useful_files/All_chars.png and https://www.unicode.org/charts/PDF/U1FB00.pdf

For example, see 1FBB0 and 1FBC0 in Pragmata:

<img width="100" alt="Screen Shot 2020-07-09 at 5 42 30 PM" src="https://user-images.githubusercontent.com/860665/87104032-9779eb80-c20b-11ea-8d75-492ba88786ff.png">

vs Unicode 13.0

<img width="108" alt="Screen Shot 2020-07-09 at 5 41 32 PM" src="https://user-images.githubusercontent.com/860665/87104055-a06abd00-c20b-11ea-8688-47f2dcc9a49a.png">

There are several others too I think.

I guess perhaps this changed between Unicode 13 draft and release? Unfortunate...

**Comment by fabrizioschiavi** [comment]
I'll fix it soon. Thanks to letting me know

**Comment by fabrizioschiavi** [comment]
Fixed since version [0.829](https://fsd.it/shop/fonts/pragmatapro/). Thanks again!
