### ISSUE TITLE
Add support for #[ ligature

### ISSUE THREAD

**Issue by cata0309** [fabrizioschiavi/pragmatapro#179]
![image](https://user-images.githubusercontent.com/35623921/87879388-11238d80-c9f3-11ea-99e2-e2dbd77e68a1.png)
This is a picture of Fira Code ligature

**Comment by fabrizioschiavi** [comment]
Ok, thanks

**Comment by fabrizioschiavi** [comment]
Added and available since version [0.829](https://fsd.it/shop/fonts/pragmatapro/). Thanks again!

![PragmataPro-0829-ligatures-dark](https://user-images.githubusercontent.com/1576663/118829528-7c154d80-b8be-11eb-8bee-c885bf063186.png)
