### ISSUE TITLE
Font size increases too much between size 10 & 11 on Windows.

### ISSUE THREAD

**Issue by IceMan81** [fabrizioschiavi/pragmatapro#18]
@fabrizioschiavi 
I find that the font size increases a lot when going from size 10 to size 11 on Windows. Size 11 looks too big compared to size 10. I'll add screenshots when I'm back in front of my windows machine.

This jump reflects itself at other sizes in my java applications. Wish the size transitions were a little more moderate.

**Comment by fabrizioschiavi** [comment]
This update is been a very revolution for me: more than 10000 glyphs are been scaled and it's been hard to keep control on all these glyphs at every point size Mac/PC/Linux
I'll fix it surely. Thanks for letting me know!

**Comment by IceMan81** [comment]
@fabrizioschiavi I completely understand and did not mean for it to be a criticism of your work. I don't think this font size issue is specific to this update. This is something I've struggled with on Windows for sometime and thought "why not have a conversation with Fabrizio regarding this".

Thanks for responding. As always, appreciate your efforts.

**Comment by fabrizioschiavi** [comment]
I always appreciated your feedbacks @IceMan81 and believe me I'll do all possible to find the right solution also this time. Thank you!

**Comment by SimWhite** [comment]
I'm really sorry but is there any updates?

**Comment by fabrizioschiavi** [comment]
I'm completing the update. This week I'll release it. Thanks for the patience

**Comment by IceMan81** [comment]
@fabrizioschiavi Were there any font size related changes in this release?

**Comment by SimWhite** [comment]
I didn't see any changes too.

**Comment by fabrizioschiavi** [comment]
I verified with more attention at this case and I found the source of the problem.

A preamble:
10 pt PC = 13.33 pt Mac
11 pt PC = 14.67 pt Mac
14 pt Mac = 10.5 pt PC

After the scaling of all the glyphs, unfortunately the heights fallen in a alignment point that does not allow it to be changed without altering the real one

To increase the height of 10pt I must add 1 pixel to the top of the glyphs at 13pt Mac
Please see by yourself if is possible seeing the following screenshot
![13mac](https://cloud.githubusercontent.com/assets/1576663/18555538/87522486-7b68-11e6-8203-b4719669c984.png)
We are already above the line-height of the grid

I suggest you to set up PragmataPro using **10.5** to obtain the right scaling effect and to taking advantage of the perfect hinting of 14 pt Mac

**Comment by IceMan81** [comment]
Seems to work on Sublime, but don't know what the equivalent would be for Intellij on Windows. Windows font size is not a 1:1 with Java font size and hence Intellij font size. Also, some editors/command line tools like mintty only allows integer font sizes.

**Comment by rnetocombr** [comment]
I agree with @IceMan81, many editors / applications use integer font sizes. We should remember that PragmataPro is used in other activities beside code editing (terminal emulator, log viewers, etc).

Cheers!

**Comment by fabrizioschiavi** [comment]
So @IceMan81 @rnetocombr what do you suggest me to do?
