### ISSUE TITLE
Visual studio no ligatures for <- and ->

### ISSUE THREAD

**Issue by AndreasDM** [fabrizioschiavi/pragmatapro#182]
With `pragmata pro mono liga` the symbols `~>` and `<~` renders correctly with ligatures but `->` and `<-` don't seem to render with ligatures.

![2020-08-19-145027_140x127_scrot](https://user-images.githubusercontent.com/12885048/90636759-5ffb5780-e22b-11ea-93da-4e4e3093ff4b.png)

**Comment by fabrizioschiavi** [comment]
It seems to be a [Visual Studio issue](https://developercommunity.visualstudio.com/idea/591741/font-ligatures-not-working.html)

**Comment by fabrizioschiavi** [comment]
On Mac it works perfectly

![Screenshot 2021-05-19 at 16 29 51](https://user-images.githubusercontent.com/1576663/118831092-c519d180-b8bf-11eb-9029-632d34ce732b.png)


Do you confirm that it works also in Windows?

**Comment by AndreasDM** [comment]
Still not working, similar to [https://github.com/tonsky/FiraCode/issues/259](https://github.com/tonsky/FiraCode/issues/259)
Not sure what there is to do about this though.

**Comment by Porges** [comment]
Yeah, this is entirely Visual Studio’s fault.
