### ISSUE TITLE
Missaligned *= and /= ligatures

### ISSUE THREAD

**Issue by cata0309** [fabrizioschiavi/pragmatapro#183]
Hello, Fabrizio ! I am using PragmataPro Mono Liga in CLion(Intellij IDEA Based IDE) and this happens:
( It happens on small sizes too, I made a screenshot at size 100 to see the issue better)
![image](https://user-images.githubusercontent.com/35623921/91766643-92219780-ebe3-11ea-8a3d-22c46c8672a5.png)
Let me know what you think. In the images that describe the supported ligatures the `*` and `/` are centered vertically on the equal sign

**Comment by fabrizioschiavi** [comment]
Thanks for letting me see this misalignment. I'll fix it asap

**Comment by fabrizioschiavi** [comment]
Fixed it since v_0.829

![Screenshot 2021-05-19 at 19 27 40](https://user-images.githubusercontent.com/1576663/118857479-60b73c00-b8d8-11eb-8303-210576285f62.png)
