### ISSUE TITLE
Wrong glyph for U+2BFF (HELLSCHREIBER PAUSE SYMBOL)

### ISSUE THREAD

**Issue by spixi** [fabrizioschiavi/pragmatapro#184]
The glyph for U+2BFF (HELLSCHREIBER PAUSE SYMBOL) is wrong. This can be observed here: https://www.fileformat.info/info/unicode/char/2bff/fontsupport.htm
![2BFF](https://user-images.githubusercontent.com/3192596/93334454-43037580-f825-11ea-8773-e226a0749e3c.PNG)

The correct glyph should look like below:
![hell-pause-character](https://user-images.githubusercontent.com/3192596/93334788-c755f880-f825-11ea-8499-b8488dfa9ba8.jpg)

**Comment by fabrizioschiavi** [comment]
Thank you @spixi , I'll fix it soon

**Comment by fabrizioschiavi** [comment]
Fixed since version [0.829](https://fsd.it/shop/fonts/pragmatapro/). Thanks again!

![Screenshot 2021-05-19 at 16 20 47](https://user-images.githubusercontent.com/1576663/118829217-35bfee80-b8be-11eb-8ca0-cdc0afa8ad35.png)
