### ISSUE TITLE
<|> ligature

### ISSUE THREAD

**Issue by aidangilmore** [fabrizioschiavi/pragmatapro#187]
I know you're very busy, but if you can find the time, I would love to see a ligature for [`<|>`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Applicative.html#v:-60--124--62-) in Haskell. A similar character sequence is used in the popular Haskell Servant library with [`:<|>`](https://hackage.haskell.org/package/servant-0.18/docs/Servant-API.html#v::-60--124--62-) which I think would be covered by the creation of a `<|>` ligature.

Thank you very much for your hard work, your typeface has been an absolute treat for the several years I've been using it.

**Comment by fabrizioschiavi** [comment]
Thank you very much for your kind words! I'll work on your suggestions. Thanks again!

**Comment by fabrizioschiavi** [comment]
Added and available since version [0.829](https://fsd.it/shop/fonts/pragmatapro/)

![Screenshot 2021-05-19 at 16 10 46](https://user-images.githubusercontent.com/1576663/118827573-cac1e800-b8bc-11eb-8543-5e34808ad64b.png)

**Comment by aidangilmore** [comment]
Beautiful! Thank you very much!
