### ISSUE TITLE
PragmataPro Mono 0.822 appears to be higher than previous version

### ISSUE THREAD

**Issue by jibsen** [fabrizioschiavi/pragmatapro#19]
This screenshot compares my terminal window using PragmataPro Mono 0.821 vs. 0.822:
![ppro_height](https://cloud.githubusercontent.com/assets/1367512/13839182/6a32b9bc-ec19-11e5-9dbf-2211b28174dd.gif)
It looks like the new version is roughly one pixel higher, making the lines feel a little cramped.

**Comment by jibsen** [comment]
I've tried to investigate this a little further. It seems to work fine in editors (Atom, Sublime), and other consoles, I am only seeing the difference above in Cmder/Conemu.

I am using size 15 in Cmder, which matches size 10 in editors.

**Comment by fabrizioschiavi** [comment]
This update is been a very revolution for me: more than 10000 glyphs are been scaled and it's been hard to keep control on all these glyphs at every point size Mac/PC/Linux
I'll fix it surely, if possible. Thanks for letting me know!

**Comment by antanst** [comment]
The new, higher version looks better to me and more close to the intended design of the font (how the font looks on paper).

**Comment by jibsen** [comment]
@fabrizioschiavi is probably the one to say what the intended look is, but if you consider the screenshots on the [homepage](http://www.fsd.it/shop/fonts/pragmatapro), I believe they look more like the old version.

Check for instance the distance between the top and middle versus the middle and bottom horizontal lines in letters like 'a', 'g', '6', '9'. In the old version they are about the same distance apart, as they are in the screenshots on the homepage.

If the intended look is the new version, then something is wrong on Windows, because here it looks like the old version in Sublime Text, Atom, and Vim.

That being said, I think it may be an issue with the way Cmder interprets the font size. Perhaps 15 is between two sizes and somehow results in scaling the upper half of the characters. I would love to be able to get the same font size in my terminal as in my editors though.

**Comment by jibsen** [comment]
Btw, @fabrizioschiavi don't worry too much about this, it is a minor annoyance to me. I just wanted to report it so you knew there was something different.
