### ISSUE TITLE
∈ (U+2208, element of) and ∉ (U+2209, not an element of) don't match

### ISSUE THREAD

**Issue by malob** [fabrizioschiavi/pragmatapro#192]
In PragmataPro ∉ (U+2209, not an element of) is the same style and size as ∊ (U+220A, small element of).

**Comment by fabrizioschiavi** [comment]
Thanks @malob ! I’ll fix it soon

**Comment by malob** [comment]
Thanks! Also ∊ (U+220A) and ∍ (U+220D) don't match stylistically. The former appears slightly slanted.

**Comment by fabrizioschiavi** [comment]
Fixed since version [0.829](https://fsd.it/shop/fonts/pragmatapro/)

![Screenshot 2021-05-19 at 16 16 29](https://user-images.githubusercontent.com/1576663/118828541-a581a980-b8bd-11eb-80e8-8061f4020a08.png)
