### ISSUE TITLE
Upgrade my font

### ISSUE THREAD

**Issue by tlkahn** [fabrizioschiavi/pragmatapro#199]
Hi, I would like to upgrade from Essential PragmataPro to full version of PragmataPro. I have added it to the cart. Can you help me to adjust the price by deducting my paid amount? I remember someone asked it before. It'll be better to have the upgrade option on the website. My account email is joshgy@gmail.com.

Could you help? Thanks a lot!

**Comment by fabrizioschiavi** [comment]
Absoutely yes, I just wrote you in private.
