### ISSUE TITLE
Request to patch font for IntelliJ

### ISSUE THREAD

**Issue by smeevil** [fabrizioschiavi/pragmatapro#20]
Hi there,

Recently the IntelliJ line of editors is able to use ligatures as well.
Examples are the Hasklig and FiraCode font.

Due to a bug in the JDK there is a small patch required to make this work until the editors are ready to use Java 9.

As far as I can find out they are talking about ``` "replacing 'DFLT' tag with 'zyyy' tag in GSUB subtable,```.
The full tread can be found here : https://youtrack.jetbrains.com/issue/IDEA-127539

Looking forward to use this font (with ligatures) in IntelliJ :D

Gerard

**Comment by fabrizioschiavi** [comment]
Thank you @smeevil  for your suggestion! I'll change it and I'll let you try if it works, if you agree

**Comment by smeevil** [comment]
Yep, Just let me know when you have something that i can test for you :)

**Comment by IceMan81** [comment]
@fabrizioschiavi I would be more than happy to test this.

**Comment by i-am-the-slime** [comment]
@fabrizioschiavi Me too! (this way, I have it earlier!)

**Comment by smeevil** [comment]
Thank you for the quick support @fabrizioschiavi !

Version PragmataPro-Regular0.823 works like a charm, and more importantly, I have not spotted any render artefacts or slowdown in auto completion popup windows in IntelliJ with the ligatures, which where there using the other fonts. 

You can close the issue if you like.

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/0z0P3H121I2y2i2X0E44/Image%202016-04-05%20at%201.22.52%20PM.png?v=f426befc)

**Comment by IceMan81** [comment]
@fabrizioschiavi 0.823 is pretty cool! With 0.822 ligatures did not work in the code editor in Intellij, but it used to somewhat work in the Intellij console. With 0.823, it works in the editor in most places. See screenshot of an example, where I expect it to work but doesn't. 

![image](https://cloud.githubusercontent.com/assets/1093778/14296469/317f2eb4-fb2f-11e5-8a69-1fb10a568186.png)

**Comment by smeevil** [comment]
It seems it is not working in the console, but this is more a choice that is made by IntelliJ and not by the font. 

Regarding your screenshot, i cannot replicate that. see attached image 

![img](https://s3.amazonaws.com/f.cl.ly/items/221d1p1Q2d1n100A3l0o/Image%202016-04-06%20at%201.31.55%20PM.png?v=d45d9456)

**Comment by fabrizioschiavi** [comment]
Thank you @smeevil for let me know this issue and its solutions!
To everyone interested in the temporary working version of PragmataPro for IntelliJ, [contact](http://www.fsd.it/contact-me/) me directly waiting for the official v_0.823. 
Thank you to all :smiley:

**Comment by IceMan81** [comment]
@smeevil what OS are you on? My screenshot is from Windows. Wrt console, it used to work before with PragmataPro and I think other fonts work on the console. IntelliJ provides an option to enable ligatures on console just like the option for the editor. See the console font settings.

**Comment by i-am-the-slime** [comment]
It works really well in the new IntelliJ EAP. Can we expect a new version any time soon (including bold and italic :))?

**Comment by IceMan81** [comment]
:). I think we have all been asking Fabrizio the same question!!
