### ISSUE TITLE
Wrong alignment of curly brackets

### ISSUE THREAD

**Issue by muld3r** [fabrizioschiavi/pragmatapro#201]
Thank's a lot for an update of your great font!

Thre is a minor issue with curly brackets:
![image](https://user-images.githubusercontent.com/24359738/118706025-318dc580-b819-11eb-9bf1-5bf3d76ec21b.png)

Font Version: PragmataPro 0.829

This issue is reproducible at least with Emacs, cmder, IntelliJ.

**Comment by fabrizioschiavi** [comment]
Please re-download the font files from fsd.it and let me know if the issue is still active. Thank you!

**Comment by jibsen** [comment]
The curly braces appear to be slightly too close compared to the others:
![pragmata_curly_close](https://user-images.githubusercontent.com/1367512/118864924-bb549600-b8e0-11eb-8199-e285fa091d33.png)

**Comment by svipas** [comment]
@jibsen @fabrizioschiavi But maybe this is intentionally left to have smaller spacing?

**Comment by fabrizioschiavi** [comment]
I'll improve if possible. Thanks!
