### ISSUE TITLE
bad shape without antialiasing in version 0.829

### ISSUE THREAD

**Issue by jxy** [fabrizioschiavi/pragmatapro#202]
Here is an example with pixel size 20, without antialiasing, PragmataPro Regular
![PragmataPro-Regular-20](https://user-images.githubusercontent.com/89739/118723803-756dd400-b7f3-11eb-9fe6-d6857e1d8531.png)
and PragmataPro Mono Regular
![PragmataProMono-Regular-20](https://user-images.githubusercontent.com/89739/118723807-76066a80-b7f3-11eb-8007-db87201a7239.png)
the letter `l` rendered too thin, `{` have different heights, and `}` in PragmataPro Mono shows up bad.  This is rendered with fontconfig 2.13.93 and freetype 2.10.4

Version 0.828 works fine.  I guess the revamped glyphs do not have proper bitmaps?

**Comment by fabrizioschiavi** [comment]
Unfortunately my fonteditor change something hard to find in the latest releases. 
Anyway, try to download and install the font files again please. I think to have fixed this issue minutes ago.
Please confirm. Thanks!

**Comment by jxy** [comment]
Perfect now! Thanks.
