### ISSUE TITLE
Mono Liga version is missing ss13 and checkboxes

### ISSUE THREAD

**Issue by LevitatingOrange** [fabrizioschiavi/pragmatapro#203]
Hello,

first of all, I want to say that I love these fonts and want to thank you for your continued effort to improve the fonts. I have two questions regarding the newest release (love the new ss13), both regarding the Mono variant *with* ligatures. 

1. The font file for *Pragmata Pro Mono Liga Regular* does not contain the stylistic set 13:
  Running `otfinfo -f PragmataPro_Mono_R_liga_0829.ttf` gives the following output:
  ```
  aalt	Access All Alternates
  c2sc	Small Capitals From Capitals
  ccmp	Glyph Composition/Decomposition
  cv01	Character Variants 1
  cv02	Character Variants 2
  cv03	Character Variants 3
  dnom	Denominators
  frac	Fractions
  hwid	Half Widths
  mark	Mark Positioning
  mkmk	Mark to Mark Positioning
  sinf	Scientific Inferiors
  ss03	Stylistic Set 3
  ss04	Stylistic Set 4
  ss05	Stylistic Set 5
  ss06	Stylistic Set 6
  ss07	Stylistic Set 7
  ss08	Stylistic Set 8
  ss09	Stylistic Set 9
  ss10	Stylistic Set 10
  ss11	Stylistic Set 11
  ss12	Stylistic Set 12
  sups	Superscript
  vert	Vertical Writing
  ```
  Note the missing ss13. All other cuts contains the new set. For example, for *Pragmata Pro Mono Liga Bold* `otfinfo -f PragmataPro_Mono_B_liga_0829.ttf` produces ss13. 

2. The checkboxes do not seem to be enabled for any cut of *Pragmata Pro Mono Liga*. This might be intentional? I am not sure if the constant width disallows these kinds of ligatures, though I want to mention that other new ligatures, like the new `>λ=` do work.

Thanks again for your hard work!

**Comment by fabrizioschiavi** [comment]
Hi, thanks to letting me know this!
I just fixed `ss13` issue.
You can re-download the font files from fsd.it and confirm it please?
I'll add checkboxes as ligatures in Mono versions soon.
Thanks again!

**Comment by fabrizioschiavi** [comment]
Checkboxes ligatures just added!

**Comment by LevitatingOrange** [comment]
Thank you for your swift response! I now can enjoy the glorious new git trees! Checkboxes seem to work too, though there I have small problem with them: I am on Linux (so using Freetype 2 for rasterization) and the checkboxes get squished when using the Mono variant:
![pp_mono_liga](https://user-images.githubusercontent.com/4560504/118902980-06899b80-b917-11eb-8b23-befdddd3ec2d.png)
but not when using the standard variant:
![pp_liga](https://user-images.githubusercontent.com/4560504/118902983-07bac880-b917-11eb-8115-db183d313609.png)
Maybe something todo with the fixed width of the mono variant?

**Comment by benjamin-rood** [comment]
@LevitatingOrange Hi, I am trying to make use of the new ligatures so I can see glorious git trees, too! Also on linux, how do you enable them system-wide?

**Comment by levifig** [comment]
Sorry to ping on this older thread, but I'm having the same problem.
I just bought and downloaded the fonts today and SS13 is missing from my package as well... :o
I do get SS14, just no SS13...
```
❯ otfinfo -f PragmataProR_liga_0829.otf
aalt	Access All Alternates
c2sc	Small Capitals From Capitals
calt	Contextual Alternates
ccmp	Glyph Composition/Decomposition
cv01	Character Variants 1
cv02	Character Variants 2
cv03	Character Variants 3
dnom	Denominators
frac	Fractions
fwid	Full Widths
hwid	Half Widths
mark	Mark Positioning
mkmk	Mark to Mark Positioning
sinf	Scientific Inferiors
ss03	Stylistic Set 3
ss04	Stylistic Set 4
ss05	Stylistic Set 5
ss06	Stylistic Set 6
ss07	Stylistic Set 7
ss08	Stylistic Set 8
ss09	Stylistic Set 9
ss10	Stylistic Set 10
ss11	Stylistic Set 11
ss12	Stylistic Set 12
ss14	Stylistic Set 14
sups	Superscript
vert	Vertical Writing```

PS: In my case, this is true on the TTF and OTF, Mono or regular, and in every style... No SS13 on any of them.

**Comment by fabrizioschiavi** [comment]
@levifig don't worry: SS13 means [Git Tree feature](https://fsd.it/wp-content/uploads/PragmataPro-command-line-git-tree.png). 
In version 0.829 was removed because this feature is enabled by default.
Sorry for the mess.

**Comment by levifig** [comment]
> @levifig don't worry: SS13 means [Git Tree feature](https://fsd.it/wp-content/uploads/PragmataPro-command-line-git-tree.png). In version 0.829 was removed because this feature is enabled by default. Sorry for the mess.

That makes sense, thank you. They don't seem to be displaying too well for me, but I'll try in a different TE before I consider it a "bug"... :)

But, for what is worth, I think I'm missing the checkboxes though...
