### ISSUE TITLE
Windows 10 & 0.829: unavailable for use Regular, Bold (from PragmataPro Liga), Regular  (from PragmataPro Mono Liga)

### ISSUE THREAD

**Issue by mvs3d** [fabrizioschiavi/pragmatapro#204]
Hello Fabrizio! I have been using PragmataPro for many years, and I first encountered a strange problem after installing the new font version (0.829).

After installing it, some font styles from PragmataPro Liga and PragmataPro Mono Liga became unavailable for selection, and as a result I can't use the ligatures.

This is an example of font selection in Notepad:

![image](https://user-images.githubusercontent.com/5299867/118808759-e1673f80-b8ba-11eb-8c65-d43b6e6e098f.png)

Sorry for the Russian in the screenshot, but I think you can see here that for PragmataPro Liga is not available Regular and Bold types.

This is very strange, because on system settings I found those types is installed:

![image](https://user-images.githubusercontent.com/5299867/118809197-59ce0080-b8bb-11eb-8f29-1fa0b89168b7.png)

I tried completely uninstalling the PragmataPro fonts from the system and reinstalling them, including using Widows safe mode, but the result is the same.

I also tried to install the previous version (0.828), there is no problem with it.

So, I just have no idea what else can I try to do. I have Windows 10 Pro version with all latest updates.

**Comment by fabrizioschiavi** [comment]
Oh wow!
Can you try to download and install again the font files, please?
Please let me know if was fixed with this new version. Thank you!!

**Comment by mvs3d** [comment]
Wow, it's all good now! If any changes were made on your side, it worked. As for me, after I submitted this issue I installed the another update: Windows 10, version 21H1.

**Comment by fabrizioschiavi** [comment]
Perfect! Thank you again to let me know this terrible issue!
All the best
