### ISSUE TITLE
Ligature =/ vs shell assign path

### ISSUE THREAD

**Issue by amerlyq** [fabrizioschiavi/pragmatapro#206]
New mono ligature "=/" is breaking shell experience in terminal
```
export JAVA_HOME=/some/path

myvar=/home/user
```
What I see on the screen is read as "var is not equal to path, stripped of leading slash".
Too much confusing.

What was original usecase when "=/" was added ?

**Comment by fabrizioschiavi** [comment]
Oh wow! This is a very bad issue. 
Sorry I must fix it asap. Thank you!

**Comment by amerlyq** [comment]
But only revert "=/" -- don't touch new "!=" ligature with below dot, it's really nice :)

**Comment by fabrizioschiavi** [comment]
I just fixed this issue.
Please download again the font files. 
Thank you for your help!
