### ISSUE TITLE
emacs prettify symbols snippet missing for v0.829

### ISSUE THREAD

**Issue by eigengrau** [fabrizioschiavi/pragmatapro#208]
Nice work on v0.829! I have noticed that some glyphs in the private use area have been moved or removed, so that prettify-symbols-mode in Emacs produces odd results. It looks like U+E990 and U+E991 are now gone from the PUA, probably because these glyphs are already part of the general punctuation block. Some other ligatures seem to have been moved within the PUA (smiley faces, some Haskell operators).

**Comment by jams2** [comment]
@eigengrau not a fix but what's working for me now is using https://github.com/mickeynp/ligature.el (note the caveats about Emacs versions), with the following config cobbled together from the issues/docs there:

```
(use-package ligature
  :load-path "~/.emacs.d/ligature.el"
  :config
  (defun my-ligature-mode-hook ()
    (ligature-mode))
  (setq pragmata-ligatures
	'("[ERROR]" "[DEBUG]" "[INFO]" "[WARN]" "[WARNING]"
	  "[ERR]" "[FATAL]" "[TRACE]" "[FIXME]" "[TODO]"
	  "[BUG]" "[NOTE]" "[HACK]" "[MARK]"
	  "# ERROR" "# DEBUG" "# INFO" "# WARN" "# WARNING"
	  "# ERR" "# FATAL" "# TRACE" "# FIXME" "# TODO"
	  "# BUG" "# NOTE" "# HACK" "# MARK"
	  "// ERROR" "// DEBUG" "// INFO" "// WARN" "// WARNING"
	  "// ERR" "// FATAL" "// TRACE" "// FIXME" "// TODO"
	  "// BUG" "// NOTE" "// HACK" "// MARK"
	  "!!" "!=" "!==" "!!!" "!≡" "!≡≡" "!>" "!=<" "#("
	  "#_" "#{" "#?" "#>" "##" "#_(" "%=" "%>" "%>%" "%<%"
	  "&%" "&&" "&*" "&+" "&-" "&/" "&=" "&&&" "&>" "$>"
	  "***" "*=" "*/" "*>" "++" "+++" "+=" "+>" "++=" "--"
	  "-<" "-<<" "-=" "->" "->>" "---" "-->" "-+-" "-\\/"
	  "-|>" "-<|" ".." "..." "..<" ".>" ".~" ".=" "/*" "//"
	  "/>" "/=" "/==" "///" "/**" ":::" "::" ":=" ":≡" ":>"
	  ":=>" ":(" ":-(" ":)" ":-)" ":/" ":\\" ":3" ":D" ":P"
	  ":>:" ":<:" "<$>" "<*" "<*>" "<+>" "<-" "<<" "<<<" "<<="
	  "<=" "<=>" "<>" "<|>" "<<-" "<|" "<=<" "<~" "<~~" "<<~"
	  "<$" "<+" "<!>" "<@>" "<#>" "<%>" "<^>" "<&>" "<?>" "<.>"
	  "</>" "<\\>" "<\">" "<:>" "<~>" "<**>" "<<^" "<!" "<@"
	  "<#" "<%" "<^" "<&" "<?" "<." "</" "<\\" "<\"" "<:" "<->"
	  "<!--" "<--" "<~<" "<==>" "<|-" "<<|" "<-<" "<-->" "<<=="
	  "<==" "=<<" "==" "===" "==>" "=>" "=~" "=>>" "=/=" "=~="
	  "==>>" "≡≡" "≡≡≡" "≡:≡" ">-" ">=" ">>" ">>-" ">>=" ">>>"
	  ">=>" ">>^" ">>|" ">!=" ">->" "??" "?~" "?=" "?>" "???"
	  "?." "^=" "^." "^?" "^.." "^<<" "^>>" "^>" "\\\\" "\\>"
	  "\\/-" "@>" "|=" "||" "|>" "|||" "|+|" "|->" "|-->" "|=>"
	  "|==>" "|>-" "|<<" "||>" "|>>" "|-" "||-" "~=" "~>" "~~>"
	  "~>>" "[[" "]]" "\">" "_|_"))
  (ligature-set-ligatures 't pragmata-ligatures)
  :hook
  ((python-mode-hook . my-ligature-mode-hook)
   ...
))
```

**Comment by fabrizioschiavi** [comment]
I'm not ignoring this request. I'll work on it soon. 
Thank you also to @jams2 for this patch! Is it works?

**Comment by jams2** [comment]
@fabrizioschiavi this is the output I get with the above settings:

![2021-05-21_14-05](https://user-images.githubusercontent.com/29293125/119141926-c7a23580-ba3d-11eb-98c8-6f86bb0d82a7.png)

The !=< ligature seems odd.

There is also some odd behaviour when moving the cursor forward and backwords over the ERROR (etc.) symbols:

![2021-05-21_14-05_1](https://user-images.githubusercontent.com/29293125/119142126-033cff80-ba3e-11eb-90be-5a8008002388.png)

To be honest I haven't really had time to try to understand how font rendering works in Emacs so someone more knowledgeable than I may have some insights.

**Comment by fabrizioschiavi** [comment]
@jams2 could you donwnload and install again the font files and let me know if it works, please? Thank you!

**Comment by jams2** [comment]
Hi @fabrizioschiavi , the result is the same.

**Comment by holmesmr** [comment]
Worth noting that using `ligature.el` initially appeared to work for me on Mac, but would consistently and predictably lead to extremely weird cases where Emacs would go into an infinite loop while ding-ing the bell constantly while doing regular editing involving ligatures.

**Comment by x-ji** [comment]
Still doesn't seem to work ATM. Using the otf font also didn't work. Guess we need new mappings. At the moment I'm reverting back o 0.828.

**Comment by fabrizioschiavi** [comment]
I've just added [pragmatapro-prettify-symbols-v0.829.el](https://github.com/fabrizioschiavi/pragmatapro/blob/master/emacs_snippets/pragmatapro-prettify-symbols-v0.829.el)
Please let me know if it works properly. Thanks!

**Comment by x-ji** [comment]
Thanks for the update 👍 . Unfortunately this list seems to result in unmatched parentheses in my Emacs for some reason and prevents it from starting up... I think some parentheses character in the list might need to be escaped. I wonder if anybody else has the same issue when they tried to use it?

**Comment by x-ji** [comment]
There is one place where an escape is needed. I'll make a PR.

**Comment by x-ji** [comment]
Still, some combinations don't seem to be rendered as ligature. I wonder if it's related to https://github.com/fabrizioschiavi/pragmatapro/issues/220

**Comment by jams2** [comment]
@x-ji https://github.com/fabrizioschiavi/pragmatapro/pull/222

**Comment by x-ji** [comment]
lol beat me by a few minutes 😄

**Comment by jams2** [comment]
> lol beat me by a few minutes smile

I had fixed it on my machine but forgot to open a PR :sweat_smile:
