### ISSUE TITLE
Font issues on Windows when font size is less than 24

### ISSUE THREAD

**Issue by andreimaxim** [fabrizioschiavi/pragmatapro#209]
I've been using Linux for a while now and due to some work requirements I need to run Windows on my machine. I've been a virtual machine to run my programming tools and I've been very happy with Pragmata Pro. However, I've spent some time using Windows + WSL2 to streamline my workflow and I've noticed some weird things that I can't explain.

I bought Pragmata Pro Regular v0.829 from the FSD store a while ago and I figured that the problem was caused by the IDE trying to force the bold and italic styles so I bought those two styles (currently v0.828) from the MyFonts store (for some reason I couldn't buy it from the FSD store because of a VAT error, but that's another story)

This is how the font looks like on Windows, using the JetBrains IDEA IDE with the font size set to 24:

![pragmata-pro-24](https://user-images.githubusercontent.com/256/118931297-7ddb2180-b94f-11eb-98cc-92097143c4d2.png)

Obviously, this is too big to work with so I normally set it to something like 16 or 18 (this is 18):

![pragmata-pro-18-windows](https://user-images.githubusercontent.com/256/118931545-d7435080-b94f-11eb-976f-5ece0711a54a.png)

As a comparison, this is the same piece of code in the same IDE but on Linux, also size 18:

![pragmata-pro-18-linux](https://user-images.githubusercontent.com/256/118933656-22f6f980-b952-11eb-93b0-7a97f128b0b7.png)

Note that the editor is actually using two weights (Regular and Bold) for certain parts of the code and I feel like the bold on Linux might be a tad too bold for my taste. However, the Windows version looks really bad, beginning with the regular style, which is too thin, to the italic style which has a very weird lower case E and other artifacts.

Is it a Windows thing? If so, are there any tips or tricks to make Pragmata Pro look better on Windows? I've tried MacType but it looked like I was exchanging one set of problems for others.

Thanks!

**Comment by andreimaxim** [comment]
@fabrizioschiavi yes! The regular font (which is what I bought from the FSD store) is very much improved!

![image](https://user-images.githubusercontent.com/256/119007610-0ed6ea80-b99a-11eb-8e1a-244962bd430f.png)

Now there's still the issue with the italic, but unfortunately I bought italic and bold from the MyFonts store. I'm guessing there isn't a way to migrate from MyFonts to FSD, is there?

**Comment by fabrizioschiavi** [comment]
Good to know it works as expected!
You can migrate to fsd.it, please create an account and I'll create an order at €0 of what puchased at myfonts.com
