### ISSUE TITLE
myfonts.com missing update to 0.829

### ISSUE THREAD

**Issue by wismill** [fabrizioschiavi/pragmatapro#210]
Hello, the version 0.829 is not on MyFonts.com. Could you publish it there?

**Comment by fabrizioschiavi** [comment]
I sent the update request at MyFonts team 6 days ago. 
I just requested again a minute ago

**Comment by wismill** [comment]
Thanks! I can’t wait!

**Comment by jek291** [comment]
I'm still waiting for it to get updated on MyFonts.

**Comment by fabrizioschiavi** [comment]
MyFonts team let me know that the file size of PragmataPro Regular is too big (3.2Mb). It seems that this is blocking the update procedure. Feedbacks are very slow so I suggest you to create an account at [fsd.it](https://fsd.it/) and send me your MyFonts receipt so I can make you download the new font files without file size limitations. Sorry

**Comment by wismill** [comment]
I confirm this is the best way. Thanks Fabrizio!
