### ISSUE TITLE
[0.829] Latin small letter lambda with stroke appears without bar in bold, italic, and bold italic versions

### ISSUE THREAD

**Issue by javbit** [fabrizioschiavi/pragmatapro#211]
Top row is Greek small letter lambda (which is as expected). Bottom row is Latin small letter lambda with stroke. Notice that:
- In both bold variants, the stem's ends are vertically cut instead of horizontally like the base glyph.
- In all non-regular variants, the stroke is missing.

![lambda-matrix](https://user-images.githubusercontent.com/5223708/119058453-0a0f3800-b994-11eb-979b-0e23d54419b9.png)

![In emacs](https://user-images.githubusercontent.com/5223708/119058867-ccf77580-b994-11eb-8a58-954694d27488.png)

**Comment by fabrizioschiavi** [comment]
I just fixed it. Please download again the font files from your account at fsd.it.
Thank you for letting me know this issue!

![Screenshot 2021-05-21 at 14 23 50](https://user-images.githubusercontent.com/1576663/119136640-37192480-ba40-11eb-89e9-bf95b4e1097b.png)

**Comment by javbit** [comment]
Thank you for fixing this so quickly!
