### ISSUE TITLE
Git tree ligatures conflict with the use of pipes in shell

### ISSUE THREAD

**Issue by eigengrau** [fabrizioschiavi/pragmatapro#213]
Currently, some Git tree ligatures are triggered even where they are undesirable. E.g., the character sequence `|/` will be ligated in a pipeline using an absolute path, such as:

```
produce-data|/path/to/binary --process-data
```

I wonder if it would make sense (or whether it is possible) to only ligate `|/` when it is followed by a space or another “tree-drawing” character.

Similarly, the sequence `/|` will be ligated in `ls /some/dir/|do-stuff`.

A trickier (perhaps unsolvable?) problem with the general use of the Git tree stylistic set in the terminal is the use of backslash escapes, as in `echo hello \| world`. Though this one seems fairly artificial and perhaps such cases are uncommon enough to be ignored.

**Comment by fabrizioschiavi** [comment]
If a genius can find a solution to this conflict is very welcome but at the moment the only way to avoid this issue is to disable the OpenType feature `ss13`

**Comment by eigengrau** [comment]
> If a genius can find a solution to this conflict is very welcome but at the moment the only way to avoid this issue is to disable the OpenType feature ss13

Yes, I agree that the issue with backslash escapes is probably not avoidable. As for the other issue (regular pipes): is it possible to exclude the ligatures unless there is one of either whitespace, backslash, or a pipe symbol, to the left/right? I think this way, the ligatures would still work with `git log --tree`.

**Comment by fabrizioschiavi** [comment]
I think to found the solution with this latest release. 
**Now git tree ligatures are activated by default and works fine in almost every IDE.** 
Could you download the font files again and tell me if the issue disappeared also with you. 
Thank you @eigengrau for your hint!

**Comment by bdeshi** [comment]
@fabrizioschiavi can this be disabled by default? random pipe-slash combinations started looking weird now.

![image](https://user-images.githubusercontent.com/3525376/129965703-b68351e8-110f-4c6b-8093-ec7bcaf8fe9d.png)
