### ISSUE TITLE
=/ ligature is problematic in .829

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#215]
I have code that has things like `x=/path/to/something` and this renders strangely:

![image](https://user-images.githubusercontent.com/12575/119741749-75985e80-beda-11eb-9d45-af8cbd307706.png)

I think the `=/` ligature should probably go away. I’m not sure of any languages that use this (most that use slashes are `/=`).

**Comment by fabrizioschiavi** [comment]
Thanks @Porges. It's been already removed. Download the font files again please

**Comment by Porges** [comment]
@fabrizioschiavi that was quick, thanks!
