### ISSUE TITLE
>= and <= ligatures in 0.829

### ISSUE THREAD

**Issue by hoichi** [fabrizioschiavi/pragmatapro#216]
`>=` and `<=` used to look like greater or equal and less or equal signs. But in v 0.829 they look like this:
![image](https://user-images.githubusercontent.com/3592345/120294111-8e37b880-c2ce-11eb-85a0-2bcc8418bde9.png)

Maybe these new glyphs make sense for some languages, but not for the majority of languages (starting with JavaScript).

Iosevka, just for comparison:
![image](https://user-images.githubusercontent.com/3592345/120294271-b45d5880-c2ce-11eb-8018-4891b5f7a649.png)

**Comment by fabrizioschiavi** [comment]
Fixed. Download the font files again please. Thank you!

**Comment by hoichi** [comment]
Confirmed. Grazie mille!
