### ISSUE TITLE
U+EAB4 and U+EAB7 not aligned in 11pt size in linux

### ISSUE THREAD

**Issue by blahgeek** [fabrizioschiavi/pragmatapro#219]
OS: archlinux
software: emacs

![2021-08-03_23-25_1](https://user-images.githubusercontent.com/1308450/128042567-69bd8ad1-c615-46ab-89e9-192af9857c11.png)
![2021-08-03_23-24](https://user-images.githubusercontent.com/1308450/128042554-6b8afb2c-607e-45e6-b37a-d85ca0e5878e.png)
![2021-08-03_23-25](https://user-images.githubusercontent.com/1308450/128042564-ef3e0283-7566-4724-b76a-317693001719.png)

**Comment by fabrizioschiavi** [comment]
I'll fix it. Thank you!

**Comment by fabrizioschiavi** [comment]
Fixed in version .830
Please re-download the font files from fsd.it
