### ISSUE TITLE
Some ligatures missing in 0.829

### ISSUE THREAD

**Issue by blahgeek** [fabrizioschiavi/pragmatapro#220]
It seems that some ligatures are missing in version 0.829 (compared to 0.828). To name a few: `!!`, `||`, `***`, `*=`, `::`, ... Is this expected?

If these ligatures are removed on purpose for some reason, is it possible to still include the glyphs? In that way, for example, emacs users can still use "prettify-symbols" to use them when needed.

**Comment by fabrizioschiavi** [comment]
These ligatures are now replaced by GPOS positioning coordinates. 
Practically the result is exactly the same of version 0.828 but it require less loading time than before

**Comment by blahgeek** [comment]
Thanks for your reply!

(So those ligatures no longer work in emacs with `prettify-symbols` approach (as provided in "emacs_snippets"). But I can get it working using https://github.com/mickeynp/ligature.el)

Also, is it possible to have a list of such "GPOS-enabled" ligatures?

**Comment by fabrizioschiavi** [comment]
This is the list of GPOS-enabled ligatures, that must works everywhere without `prettify-symbols`:

```
!!!
!!
!>
#>
%>%
%>
%<%
&*
&>
***
*=
*/
...
..
..<
.>
.~
///
//
/*
/>
/**
:::
::
:>
:( 
:)
:-(
:-)
:/ 
:\
:3 
:D 
:P
:>:
:<:
<<<
<<
<!
<@ 
<^
<# 
<%
<!
<?
<.
</
<\
<"
<: 
>>>
>>
???
??
?~
?=
?>
^..
^.
^? 
^> 
\\
\>
@>
">
|||
||
_|
```
