### ISSUE TITLE
≤ (U+2264) and ⪇ (U+2A87) don't line up correctly

### ISSUE THREAD

**Issue by malob** [fabrizioschiavi/pragmatapro#224]
<img width="71" alt="image" src="https://user-images.githubusercontent.com/2914269/129400332-1e884689-e5c3-48be-a4c2-b02d45eb0594.png">

**Comment by fabrizioschiavi** [comment]
Thanks @malob ! I'll fix it

**Comment by fabrizioschiavi** [comment]
Fixed! Please re-download the font files from fsd.it
