### ISSUE TITLE
Question about "^^" -> "∀" ligature

### ISSUE THREAD

**Issue by andreypopp** [fabrizioschiavi/pragmatapro#226]
Hello,

I'm curious what's the reasoning for this ligature to exists? `^^` looks more like "catenation" and not "universal quantifier". Is there any way to disable that specific ligature?

Thanks!

**Comment by andreypopp** [comment]
> I like it anyway, probably I need to find a better character combo.

Yeah, me too! Unfortunately in most languages which uses universal quantifiers" (Coq, Agda, Idris) it is rather verbose — `forall`, `\forall` and so on.

**Comment by fabrizioschiavi** [comment]
Disabled in version .830
Please re-download the font files from fsd.it
