### ISSUE TITLE
Updates after 1.0

### ISSUE THREAD

**Issue by dead10ck** [fabrizioschiavi/pragmatapro#227]
Hi, this looks like a really beautiful font, and I'm considering purchasing. One thing that stood out to me on the font's web page is:

>All the updates until version 1.0 will be FREE — The actual version is 0.829

Does this mean that once a 1.0 is declared that all users will have to purchase another license to receive updates? Considering the hefty price tag, if this is the case, that would stop me from purchasing.

**Comment by fabrizioschiavi** [comment]
No, you will don't pay again for 1.0 version

**Comment by dead10ck** [comment]
Awesome, thanks so much for clarifying, that makes much more sense!
