### ISSUE TITLE
Puzzling ligature behavior with /| and /|/

### ISSUE THREAD

**Issue by xguerin** [fabrizioschiavi/pragmatapro#237]
Hello !

I have a small question regarding the behavior of the ligatures. When enabled, Kitty terminal combines `/`, `|` and `\` together into what looks like Kanji characters. I looks at the list of ligatures provided in the font and could not find those combinations.

Kitty allows to disable "general ligatures" and only keep the "calt" set, but that does not seem to make any difference.

Would there be a way to disable those ligatures? They end-up being a little annoying when typing regular expressions.

Thanks !

**Comment by lastsecondsave** [comment]
@fabrizioschiavi Just to clarify. This combinations look like git tree ligatures:

![image](https://user-images.githubusercontent.com/6729879/181516055-acc85da1-f9ff-4e6d-9d3b-cc691ed50044.png)

And these should be available in ss13 only. But they are active by default in 0.829. Is this indented? Thanks.

**Comment by fabrizioschiavi** [comment]
@lastsecondsave yes it was intended because I supposed `|` `\` `/` combinations was very rare

**Comment by lastsecondsave** [comment]
Thanks. I agree they are quire rare, but I see `\|` from time to time, mostly used to escape `|` in regexes. Just FYI.

**Comment by svipas** [comment]
I can agree, wanted to create a new ticket, but found this one. Just recently hit this one since we use it in regex. @fabrizioschiavi maybe it makes more sense this to be off by default, but under OpenType feature like `ss15` or something like that?

**Comment by fabrizioschiavi** [comment]
@svipas yes, it's just what I will do: `ss15`
Thanks for the suggestion!

**Comment by fabrizioschiavi** [comment]
@svipas yes I'll return back

**Comment by svipas** [comment]
@fabrizioschiavi One thing I discovered is that if you decide to use another number other than `ss13` you should update `handbook.png` as well. Just a reminder, because I like to look into that file to see what options do I have and sometimes I like to experiment 😅

**Comment by fabrizioschiavi** [comment]
Yeah! I'll keep it updated. Me too I'm feeling lost without `handbook.png`😀

**Comment by svipas** [comment]
@fabrizioschiavi @xguerin This one is fixed and could be closed, because in 0.830 it renders it properly.

<img width="38" alt="image" src="https://github.com/fabrizioschiavi/pragmatapro/assets/10441177/12a5c772-9680-4b29-8b52-2b592b15a524">

**Comment by xguerin** [comment]
Thanks!
