### ISSUE TITLE
BQN symbols questions

### ISSUE THREAD

**Issue by andreypopp** [fabrizioschiavi/pragmatapro#238]
Hi,

I'm using BQN now with Pragmata Pro and noticed `⟜⊸` are not aligned while it feels like they should be:

<img width="146" alt="Screenshot 2021-12-15 at 01 21 18" src="https://user-images.githubusercontent.com/30594/146088654-32642097-25f8-4702-9abe-9bde792e6444.png">

Also for `○∘` I've noticed that they render in an interesting way in bold (tested in kitty and macOS TextEdit.app):
<img width="406" alt="Screenshot 2021-12-15 at 01 23 13" src="https://user-images.githubusercontent.com/30594/146088876-51448ea2-66ac-49a1-85eb-213902c7db7d.png">

**Comment by fabrizioschiavi** [comment]
Thank you @andreypopp ! I'll fix it.

**Comment by fabrizioschiavi** [comment]
Fixed! Version .830
Please re-download the font files from fsd.it
