### ISSUE TITLE
Ligatures for >= and <= are glitching in Sublime Text

### ISSUE THREAD

**Issue by lastsecondsave** [fabrizioschiavi/pragmatapro#239]
They appear cropped:

![](https://user-images.githubusercontent.com/6729879/113787906-7597a000-976e-11eb-9cec-d7c677492a0a.png)

This is Sublime Text 4126 on Windows 10. The DPI is 200% but it's the same with any other value.

Other apps that support ligatures do render them correctly so I suppose it's Sublime's issue (reported at https://github.com/sublimehq/sublime_text/issues/4055). But at the same time it renders any other ligature correctly, apart from these two. May they can be tweaked somehow?

**Comment by fabrizioschiavi** [comment]
Sorry for my late response, I'll investigate about this. Thanks to letting me know it

**Comment by akhar** [comment]
<img width="192" alt="Screenshot 2022-04-14 at 19 45 38" src="https://user-images.githubusercontent.com/7146472/163456478-c121a410-2944-48d2-8f89-58366b1f2843.png">
@lastsecondsave How did you get that fancy ligatures? A have arrows in ST and WebStorm as well.

**Comment by fabrizioschiavi** [comment]
@akhar if you download the font files again from [my site](https://fsd.it/my-account/) you can see the old more/less-equal ligatures. Sorry for the mess. Thanks!

**Comment by akhar** [comment]
Version the same, but it works!
Thanks for amazing font!

**Comment by TerminalFi** [comment]
> They appear cropped:
> 
> 
> 
> ![](https://user-images.githubusercontent.com/6729879/113787906-7597a000-976e-11eb-9cec-d7c677492a0a.png)
> 
> 
> 
> This is Sublime Text 4126 on Windows 10. The DPI is 200% but it's the same with any other value.
> 
> 
> 
> Other apps that support ligatures do render them correctly so I suppose it's Sublime's issue (reported at https://github.com/sublimehq/sublime_text/issues/4055). But at the same time it renders any other ligature correctly, apart from these two. May they can be tweaked somehow?

This is likely a Sublime Text issue.

**Comment by lastsecondsave** [comment]
BTW for OpenType version of Pragmata these glyphs are rendered correctly. So if you have cropped characters, install otf files instead of ttf ones.
