### ISSUE TITLE
PragmataPro rendered as bold in IntelliJ IDEA 2016.1

### ISSUE THREAD

**Issue by tuscland** [fabrizioschiavi/pragmatapro#24]
Hello,

I don't know if this is a problem with the font itself or IDEA, so I'm posting here with the hope it could lead to a solution.

The problem is that PragmataPro is rendered as bold, always. Whereas PragmataPro Mono has the correct rendering. Here a video demonstrating the problem:

![out](https://cloud.githubusercontent.com/assets/556316/14767905/41440830-0a32-11e6-9689-ef48bbd5b96a.gif)

In the video, I first show that when using PragmataPro (not Mono), the font is rendered as bold the bold option does not matter. Then I switch to PragmataPro Mono, where it behaves as it should.

Could it possibly be a difference in the way fonts are built that would cause this rendering issue?

Thanks,
Cam

**Comment by tuscland** [comment]
It looks like the problem is in IDEA because the problem is absent when I use the font in another Java application.

**Comment by IceMan81** [comment]
@tuscland try new Intellij builds which have custom JDK builds packaged with them. PragmataPro (including ligatures) works well with the custom JDK.

**Comment by tuscland** [comment]
Hi @IceMan81 
Where can you find those builds?

**Comment by IceMan81** [comment]
https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.2+EAP
These EAP builds have 32bit JDKs, but you can get the 64bit JDKs for your OS here.
https://bintray.com/jetbrains/intellij-jdk

**Comment by tuscland** [comment]
So, no the problem is still present in the 2016.2 EAP.
When you switch font ligature on, the font appears bold.

**Comment by fabrizioschiavi** [comment]
I'll investigate about this strange behavior. 
Anyway it seems by the animation of @tuscland was never loaded the right Bold version, it seems a fake Bold of the software

**Comment by IceMan81** [comment]
@tuscland Is this an issue on Linux? I use Intellij 2016.1, 2016.2 and recently been using 2016.3 EAP on Mac and Windows using their Custom JDK (jdk8 b112 build 340) and don't see this issue

**Comment by fabrizioschiavi** [comment]
Using [these](http://www.fsd.it/pragmatapro/IntelliJ_FSD_settings.zip) my settings I don't find this problem. I hope it can helps
