### ISSUE TITLE
Stylistic sets are hard to use in IDEs or terminals

### ISSUE THREAD

**Issue by sgigou** [fabrizioschiavi/pragmatapro#246]
You made awesome stylistic sets for Pragmata Pro – `ss06` and `ss09` are beautiful – but sadly, they are almost unusable in a development environment. Stylistic sets are hard to activate, and even more to activate them in some contexts only – for example, using the script set only for comments.

I know some concurrents use custom downloads to allow to customize the font without having to use stylistic sets – Input does it, MonoLisa too. But it seems like a lot of work.

Those sets only target italic characters; maybe you could include versions with alternates italics in the main download? Like a `PragmataPro Liga Script Regular`?

I'm just so sad not to be able to see those beautiful characters…

**Comment by fabrizioschiavi** [comment]
I know it. It's important to have the possibility of to customize PragmataPro as other fonts. In this field I need help because I can't do it and the programmers I contacted leave me alone. 
**If someone can build this customizer please do not exitate to contact me. Thanks!**

**Comment by buzzlaker** [comment]
@fabrizioschiavi I could build this if you would like to discuss.

**Comment by fabrizioschiavi** [comment]
Could you try to customize PragmataPro using **OT Feature Freezer**?
It seems the solution we waiting.
https://github.com/fabrizioschiavi/pragmatapro/issues/270#issuecomment-1807157407

**Comment by svipas** [comment]
I prepared a simple script if somebody wants to use it instead of OTFeatureFreezer GUI. First you need to download PragmataPro from fsd.it and extract it. Open your terminal and go to the place with `cd` where `.ttf` fonts of PragmataPro are. And, run this script below:

```sh
#!/usr/bin/env bash

# Install - python and pipx
brew install python pipx &> /dev/null
pipx ensurepath &> /dev/null

# Download - OpenType Feature Freezer (https://github.com/twardoch/fonttools-opentype-feature-freezer)
pipx install opentype-feature-freezer &> /dev/null

# Build - Italic stylistic alternates
pyftfeatfreeze -f 'ss09' PragmataProI_liga_0829.ttf PragmataProI_liga_0829_script.ttf
pyftfeatfreeze -f 'ss09' PragmataPro_Mono_I_liga_0829.ttf PragmataPro_Mono_I_liga_0829_script.ttf
echo "Italic stylistic alternates have been built"

# Build - Bold Italic stylistic alternates
pyftfeatfreeze -f 'ss10' PragmataProZ_liga_0829.ttf PragmataProZ_liga_0829_script.ttf
pyftfeatfreeze -f 'ss10' PragmataPro_Mono_Z_liga_0829.ttf PragmataPro_Mono_Z_liga_0829_script.ttf
echo "Bold Italic stylistic alternates have been built"
```

After it's done you will find new `.ttf` files which will end with `_script.ttf`. Install them and you're good to go. Remember to kill and relaunch your IDE or Terminal so it recognizes new font files.
