### ISSUE TITLE
download/use older version of the font?

### ISSUE THREAD

**Issue by nashpatty** [fabrizioschiavi/pragmatapro#247]
I was wondering if there's a way to download an older version of the font. 
I submitted an issue [235 here](https://github.com/fabrizioschiavi/pragmatapro/issues/235), for the comma/semi-colon character and the brace character.
Is there a way for me to use a version of the font before these changes were made, until these changes are resolved?

**Comment by fabrizioschiavi** [comment]
I sent you via email the older version. Thank you!
