### ISSUE TITLE
Strange umlaut scaling at different font sizes

### ISSUE THREAD

**Issue by Kungsgeten** [fabrizioschiavi/pragmatapro#248]
![pragmata_error](https://user-images.githubusercontent.com/3976377/175774240-ddea5bf9-c63b-41f0-949f-42416608c2ef.png)

Hi! I just bought PragmataPro and got buyer's remorse when I saw how hard it was to read the ÄÖäö characters (I'm Swedish so these characters are very common). I could hardly notice the umlaut and when skimming text the characters looked like regular AOao. Then I noticed that zooming in and out (and changing the font size) drastically changed the look of the umlaut!

As can be seen in the image: the left example looks good (the dots have the same shape as over the "i" character), the right example looks bad and the "small" example (regular code size I'd say) looks bad.

**Comment by fabrizioschiavi** [comment]
Hi @Kungsgeten ! I'm sorry about your unsatisfaction.
Which software do you used in this screenshot?

**Comment by Kungsgeten** [comment]
In the screenshot I used LibreOffice Writer (same issues on both Linux and Windows), but I first noticed it in Emacs. I can try some more software if it helps. I'm using the ttf-files.

**Comment by Kungsgeten** [comment]
I got the same result using Notepad and also Notepad++. It looks correct at 15pt, but anything under that looks strange.

**Comment by fabrizioschiavi** [comment]
You've right! Damn referenced glyphs… I'll fix all soon

**Comment by Kungsgeten** [comment]
Update: The problem isn't there when using the otf files instead of ttf.

**Comment by fabrizioschiavi** [comment]
I think to have fixed the issue.
This is Libre Office Mac:

<img width="314" alt="Screenshot 2024-01-03 at 19 49 40" src="https://github.com/fabrizioschiavi/pragmatapro/assets/1576663/76f3318d-c390-4f42-9811-73c1527c61d1">

Please confirm, thanks!
