### ISSUE TITLE
Nerd fonts glyphs for PragmataProMono stopped working for macOS Ventura

### ISSUE THREAD

**Issue by amanvm** [fabrizioschiavi/pragmatapro#250]
I think this is the case for all PUA areas as multiple disjoint areas are not rendered now. Check the screenshot below. On front is the test .txt file with all glyphs you have put on your website. On back (transparency) is the same area that shows some of the glyphs affected.

Font version: 0.829 or 0.828
macOS: 13.0 (22A380), with latest xcode command line tools installed.

Note: I have already cleared and rebuilt the font cache by booting machine in safe mode, and rebooting in normal mode as suggested by: https://glyphsapp.com/learn/eliminating-font-cache-problems

<img width="1350" alt="Screenshot 2022-11-04 at 2 08 08 PM" src="https://user-images.githubusercontent.com/25681815/200076137-b6102c66-0230-47c0-b025-906f621b6816.png">

**Comment by fabrizioschiavi** [comment]
Oh wow! Weird!
I’ll upgrade to MacOS Ventura and I’ll make you know soon.
Thanks to letting me know it

**Comment by Yanior** [comment]
@fabrizioschiavi Hello! Do you have some news about this issue? I have the same problem in iTerm2 (MacOS Ventura)

**Comment by fabrizioschiavi** [comment]
I've searched about the changes applied by Apple at PUA areas but I haven't found nothing. If someone is more lucky than me please let me know here. Thanks!

**Comment by amanvm** [comment]
Not sure if it would be of help to you, but patching pragmatapro files with https://github.com/ryanoasis/nerd-fonts's font-patcher script works. The result from it renders the glyphs totally fine in all applications...

Though it's not a solution as it replaces those nerd font glyphs with its own afaik (so it won't be pragmatapro's glyphs). Am not sure if you could "diff" the font files and see what is going on... I found a difff utility here, though I am not a font expert: https://github.com/source-foundry/fdiff

**Comment by fabrizioschiavi** [comment]
Ah ok, this change the situation. Thank you @amanvm !

**Comment by Yanior** [comment]
@amanvm I have some troubles with patching of fonts. I installed fontforge by using homebrew and after this I have some problems... Can you help me, please? Can you write what did you do step by step?

**Comment by amanvm** [comment]
@Yanior You need font-patcher installed too. Here are the steps:

1. Open url: https://www.nerdfonts.com
2. Scroll to section "Font Patcher Script", it's at the bottom of the page.
3. Download Patcher.
4. Now from terminal ``cd <directory_of_pragmatapro>``
5. 
```
<directory_of_patcher>/font-patcher --fontawesome --fontawesomeextension --octicons --powersymbols --pomicons --powerline --powerlineextra --weather --material -out ./patched PragmataPro_Mono_R_0829.ttf
```
Result will be in ``<directory_of_pragmatapro>/patched``.
6. Repeat step 5. for other font files too.
7. The name of the resulting file can be long, replace with some reasonable name.

There is a ``--careful`` flag to not overwrite a glyph if it exists, but I didn't try if that works well too.

**Comment by Yanior** [comment]
@amanvm Thank you very much!

**Comment by fabrizioschiavi** [comment]
I found time to investigate to this issue. 
Mono versions never included Nerd fonts glyphs, by design, because they are double width glyphs. 
Inserting these glyphs on Mono(spaced) versions they can't be anymore monospaced fonts.
Streching the glyphs takes at terrible and useless results.
<img width="300" alt="Screenshot 2022-11-27 at 17 59 48" src="https://user-images.githubusercontent.com/1576663/204149333-2473d713-3f71-4e6a-ba19-b471eb2d3c04.png">
The solution is to use other versions available on PragmataPro pack
