### ISSUE TITLE
PETSCII C64 Commodore 64 art not rendered correctly

### ISSUE THREAD

**Issue by poetaman** [fabrizioschiavi/pragmatapro#252]
PETSCII art is not rendered correctly with pragmata pro. It does with some fonts dedicated to PETSCII art.
Resources: 
1. Mapping: https://style64.org/c64-truetype
2. Font that works (C64 Pro Mono): https://style64.org/c64-truetype
3. Sample PETSCII art below is from lbs: https://littlebitspace.com

```
┌───────────────┐
|C|
|O|
|M|
|P|
|O▂=|
|S▚|
|I"▎|
|T▎'|
|I╭▌||
|O.▆|
|N▚▎|
|▂▊|
|▄"###▚|
|"▎▎|
|▎'|
|╭▌H||
|.▆|
|▚▎▎|
|▂▊:▊|
▄"###I"###▚
"▎▎▎
▎'
╭▌HH|
.▆▆
▚▎▎▎
▊▊▊
|"###"###"###
||
|L|
|B|
|S|
└───────────────┘
```

This is how it renders with pragmata pro and C64 Pro Mono:
1. Pragmata Pro
<img width="317" alt="Screenshot 2022-11-24 at 2 17 02 AM" src="https://user-images.githubusercontent.com/71736629/203758748-1dcb3c00-8559-4438-888b-194dfb0fd4c6.png">

2. C64 Pro Mono
<img width="419" alt="Screenshot 2022-11-24 at 2 16 24 AM" src="https://user-images.githubusercontent.com/71736629/203758723-7440504d-ba0f-4d58-8d52-4ff859e5b8a0.png">

**Comment by fabrizioschiavi** [comment]
C64 Pro Mono use PUA Unicode areas (Exxx) and must be updated because since years Unicode establish a new area for [Symbols for Legacy Computing](https://www.unicode.org/charts/PDF/U1FB00.pdf) (U1FBxx). PragmataPro follows correctly this new standard.
