### ISSUE TITLE
What is the release date for the new version of PragmataPro ?

### ISSUE THREAD

**Issue by LappA17** [fabrizioschiavi/pragmatapro#255]
Hello :) I really like your font PragmataPro and I'm interested in what date the release of the new version 0.830 is being prepared for or maybe the name of the version will be different ? Please share information with us, thank you !

**Comment by fabrizioschiavi** [comment]
Thanks for your interest in PragmataPro!
I started working at the update months ago but I can't work full time because of some new works under commission.
Don't worry, I can't forget PragmataPro 0.830 project. The new release has already some big improvements.
Keep in touch

**Comment by mkarmona** [comment]
Hello @fabrizioschiavi, I was wondering if the PragmataPro project is still ongoing and if there's a possibility of having the next minor release revision completed. Thank you for your help.

**Comment by fabrizioschiavi** [comment]
Finally I found the time to work at Pragmata Pro update! 
Unfortunately I can't fix all the issues presents in this repo but the must urgents.
Please download the latest release (0.830) from fsd.it
