### ISSUE TITLE
An Open Letter to Fabrizio Schiavi

### ISSUE THREAD

**Issue by anaibol** [fabrizioschiavi/pragmatapro#26]
From https://redlegion.org/2014/04/30/An-open-letter-to-fabrizio-schiavi/

"Mr. Schiavi,

I’ve read your EULA for WOFF/EOT format fonts. Ridiculous. If this is a standard practice, it’s disgusting. This EULA glorifies prostitution. It makes mopping semen at an adult book store seem like a venerable career. I suppose you might’ve garnered that I’m anti-DMCA.

Dropping $26 on a font is borderline acceptable if you enjoy the font enough. To be honest with you, I’m considering dumping your font from my site out of principle. Paying per page-view for a font license is pretty unreasonable.

Honestly, you’re worse than Metallica. If someone sees code on my site and enjoys the font it’s presented in, they can seek you out and pay you. It’s free advertising. Here you are extorting people into advertising for you, and the more advertising they do for you the more you expect them to pay. Does that seem unreasonable to you when presented honestly?

I’ll give you your $26 for your font for personal use, but I won’t give you any more free advertising and I’ll be replacing your font with something that doesn’t use a license that involves exchanging infant souls for currency.

Sincerely,

Red Legion"

**Comment by DeLaGuardo** [comment]
You are the author of this letter? Or just repost it for some reason?

**Comment by anaibol** [comment]
I am not the author and i don't agree completely with the letter, but I think it's a good place here to know the thoughts of people regarding this subject.

**Comment by jibsen** [comment]
I may be wrong here (I am sure @fabrizioschiavi will correct me), but I think the letter refers to the [webfont license on myfonts](https://www.myfonts.com/fonts/fsd/pragmata-pro/licensing.html), which is .. well .. interesting.

The [terms and conditions on fsd.it](http://www.fsd.it/shop/terms/) are much easier to understand, specifically:

> (5) You may use it as a font embedding for web pages (@ font-face) provided it is converted in a way that makes it impossible to recover the original font.

**Comment by msva** [comment]
> I am not the author and i don't agree completely with the letter, but I
> think it's a good place here to know the thoughts of people regarding this
> subject.

1) it would be nice, if you'd attach a link where did you find it
2) while you're completely disagree with it's author, I, actually, can't say 
that he's not right about the idea, that price, which Fabio asking for result 
of his work is... uhm... a bit huge ☺.

And, in my humble opinion, it is not piracy's fault that less and less people 
buying the font, but it's big price and the model of distribution which Fabio 
chosen.

Let's assume, you're baker (no, not that guy from KickStarter/Indiegogo, but 
the chief cook in bakery). You've invented recipe of SUPERMEGADELICIOUS cake. 
You also spent some amount of money for ingridients and some worktime on 
experiments while inventing. Say, 960 golden coins of total ingridients/work 
expenses.

And, *surely*, you deserve your work and expenses to be paid.

Then, you somehow found magic machine, that can create unlimited copies of 
anything you put in it absolutelly for no cost.

And now you decided, that only way for you to be fully paid for your hard work 
is... to sell this free copies for people for 1 golden coin each, and for 0.2 
(20silver coins) it's part. And  also with requirement to eat what they bought 
on your sight.
Some people buying it from you... At first time you're happy: your first time 
profit grows, and so on. But after some time, less and less amount of people 
comes to you to try this cake. And your income expectedly falls.

And you, surely, suspect thiefs, that made people to eat your cake for free 
and not to pay you.

But the truth is...

To be said, many analogs (maby not such MEGASUPERDELICIOUS, but some of them 
is a neat too) cakes are either costs 5 silver coins each, or even free with 
donation model.

And, to be said, those of them which are kinda pretty, and which people like, 
their total income profit is enough even to buy castles, horses and so on.

And also people-buyers decided that they'd better buy not so delicious, but 
less expense cake, or donate some their coins to bakers, which decided to 
share their receipts with all people.


Kinda that ;)

-- 
wbr,
mva

**Comment by abl** [comment]
That letter is needlessly vulgar and unprofessional. That letter also fails to suggest what @fabrizioschiavi should do - other than implying that the font be given away for free.

For your purchase you're getting a license to display the font for up to 500,000 pageviews per month in perpetuity. Multiple licenses stack - 4 licenses = 2MM pageviews per month. I couldn't find another font on myfonts.com that not only receives regular, substantial updates but is under a one-time-purchase license; only Pragmata and Pragmata Pro.

The terms on fsd.it are even friendlier, as @jibsen pointed out.

> I am not the author and i don't agree completely with the letter, but I think it's a good place here to know the thoughts of people regarding this subject.

I think that the terms on the Pragmata family are fair and possibly even too fair at the expense of @fabrizioschiavi when compared to other web font licensing schemes (like TypeKit.)

**Comment by fabrizioschiavi** [comment]
Thanks friends!
The EULA of MyFonts is a standard license for all foundries. I have no control about it.
What I would like to be respected in [my]( http://www.fsd.it/shop/terms/ ) EULA is exactly what highlighted by @jibsen :  

(5) You may use it as a font embedding for web pages (@ font-face) provided it is converted in a way that makes it impossible to recover the original font.

I published a suggestion at [this]( http://www.fsd.it/how-to-protecting-the-webfont-files/ ) page. I hope it can helps.

Thanks once to all for supporting my work

**Comment by anaibol** [comment]
Hi, @msva, the link is attached.
I found very interesting your answers. I have no knowledge about business models in the specific field and work of typefaces. Sure, I would like the font to be cheaper or free. Like the usage of the people in general, it would be personal and not comercial. But I understand It's not the case and I suppose there there was lot of work.
