### ISSUE TITLE
Accented capital Y (Ý) problem

### ISSUE THREAD

**Issue by vancura** [fabrizioschiavi/pragmatapro#260]
Hi,

Please check out this screenshot:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/4982/213695110-8224e0d7-6bac-4c6f-9d40-e161a7242e5c.png">

There is a good pattern in how accented capitals are treated – the cap height is always slightly lower to give more space for the accent. But this rule doesn't apply to the letter `Ý`, as seen in this example. The cap height for this particular letter is the same as for the un-accented `Y`.

All the other Czech locale letters are fine, from what I've tested; it's just `Ý`, which is wrong.

Thanks!

**Comment by fabrizioschiavi** [comment]
You've right! I'll fix it soon. Thanks!

**Comment by fabrizioschiavi** [comment]
Fixed! Please download the latest release (0.830) from fsd.it
