### ISSUE TITLE
Chevron right seems something very different

### ISSUE THREAD

**Issue by alextes** [fabrizioschiavi/pragmatapro#262]
Hi Fabrizio, been loving the font for many years now, thank you, thank you 💛.

Recently when using an editor I noticed one of the icons looks off, they use "chevron right" looking at the chevrons, they all look good, except right! Is this some complicated unavoidable issue? Is it just a small oversight? Curious to hear, and if it makes sense have it fixed to be a right chevron like some programs, like both neovim and kitty (terminal) seem to think. I'm using `PragmataPro_Mono_R_liga_0829`.
<img width="1185" alt="Screenshot 2023-03-22 at 19 22 59" src="https://user-images.githubusercontent.com/2011351/227001282-6ff06d41-c202-44c2-a68c-bb5e2a1ac12d.png">

**Comment by fabrizioschiavi** [comment]
Hi Alex, thank you for your knd feedback!
Attention because `PragmataPro_Mono_R_liga_0829` doesn't includes Nerd fonts. 
Probably the glyphs you see as icons are part of other font. 
If you'll setup `PragmataPro_R_liga_0829` as default font the icons will be replaced by corrected ones

**Comment by alextes** [comment]
Ah okay, they expect nerd fonts, I see. I just saw #231 , running the font patcher fixed everything for me.

Keep on making amazing things people love. If you ever bring out some other amazing design tooling let us know!

**Comment by fabrizioschiavi** [comment]
Thank you very much Alex! Keep in touch. All the best

**Comment by alextes** [comment]
@fabrizioschiavi so nerdfont patching ended up breaking some other glyphs the liga of `~=` for example.

Changing to `PragmataPro_R_liga_0829` not only fixed the chevron issue, it also makes a bunch of stuff just look a little tighter or sharper. Not sure what's going on but loving it! Thanks again.
