### ISSUE TITLE
Very small dev icons on Windows Terminal

### ISSUE THREAD

**Issue by ThisDevDane** [fabrizioschiavi/pragmatapro#263]
When using Pragmata Pro on Windows Terminal 1.16.10261.0 the dev icons are really small compared to other fonts?

Pragmata Pro Liga:
![image](https://user-images.githubusercontent.com/1834353/228683429-14befdc2-58fa-4c6f-a4a8-f2dac190bd5f.png)
FiraCode NF:
![image](https://user-images.githubusercontent.com/1834353/228683587-39c0095d-7953-44cb-8823-ab9ccbe62a3b.png)

**Comment by fabrizioschiavi** [comment]
It seems automatically scaled by Terminal.
Thanks for letting me know, I'll investigate on it

**Comment by fabrizioschiavi** [comment]
I thinked to have fixed this isuue adding Nerd font icons also to Mono versions. 
Please download the latest release (0.830) from fsd.it and confirm. Thanks!
