### ISSUE TITLE
Apply nerfix: nerd font icon code points have changed, and some icons are off

### ISSUE THREAD

**Issue by 0-issue** [fabrizioschiavi/pragmatapro#267]
Apparently [nerdfont](https://github.com/ryanoasis/nerd-fonts) project has moved glyphs to different code points, which means fonts using older codepoints pick incorrect symbols. Here are some relevant links and excerpts:

1. A bug I filed on a vim plugin thinking it's plugin's fault: https://github.com/akinsho/bufferline.nvim/issues/783, relevant comment by the maintainer: https://github.com/akinsho/bufferline.nvim/issues/783#issuecomment-1638759402
2. Link to nerdfix project: https://github.com/loichyan/nerdfix
3. Link to relevant nerdfont update: https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3

Here's an excerpt from [nerdfix](https://github.com/loichyan/nerdfix)'s main page: 

> To ensure that the icons remain in the private use area, Nerd Fonts has changed the codepoints of some icons in recent releases, for example, mdi-* icons (including over 2,000 icons) are deprecated since [v2.3.3](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) and will be removed in v3.

**Comment by fabrizioschiavi** [comment]
Thanks to letting me know about these important changes!
I feel myself responsible of all this (finally!)
https://github.com/ryanoasis/nerd-fonts/pull/609
Surely I'll fix it asap

**Comment by lucabol** [comment]
I think I am seeing this as well. Some icons look fine on Pragmata Pro, but not Pragmata Pro Mono. Is there a workaround, by any chance?

**Comment by fabrizioschiavi** [comment]
You've right, I'm really sorry. 
In these days I'll find time to fix it and release 0.830 version

**Comment by ThorstenRhau** [comment]
Do we know if a fix for this is coming. I will gift myself a font for Christmas and this is one of the fonts that I am really interested in.

**Comment by fabrizioschiavi** [comment]
Fixed! Please download the latest release (0.830) from fsd.it

**Comment by ThorstenRhau** [comment]
I'll give your web store a spin this evening when I get home (early Christmas present to myself). Thank you for reacting so quickly to this.

**Comment by lucabol** [comment]
I'm fixed too. Thx @fabrizioschiavi
