### ISSUE TITLE
Emoji rendering issues (icons cut off)

### ISSUE THREAD

**Issue by MarioRicalde** [fabrizioschiavi/pragmatapro#268]
The cogwheel emoji used in `nnn`, source code here: https://github.com/jarun/nnn/blob/3539e5c1b1e15b32037b2e9c1fb84f3a45ed844b/src/icons.h#L53

Looks like this in a terminal (look at the cogwheel)
![image](https://github.com/fabrizioschiavi/pragmatapro/assets/125900/8008f576-e56d-49ec-863c-71bffbcd1fb8)

It causes rendering artifacts.

The provided emoji text shows several sets of emojis that have this strange scenario with either smaller characters or cut off characters, some examples:

![image](https://github.com/fabrizioschiavi/pragmatapro/assets/125900/a3bb329d-79a6-4c33-b49b-c7bcfba486ce)

![image](https://github.com/fabrizioschiavi/pragmatapro/assets/125900/ac5f4ea5-f82a-4844-b07b-f8341f3d080c)

I can provide more examples if needed.

[unicode.org/Public/emoji/5.0/emoji-test.txt](https://unicode.org/Public/emoji/5.0/emoji-test.txt)

Is this a problem with the font or with the terminal?

**Comment by fabrizioschiavi** [comment]
Thanks @MarioRicalde for letting me know this issue caused by the recently updates of Nerd icons Unicode codepoints.
The new release of PragmataPro will fix it, soon.

**Comment by fabrizioschiavi** [comment]
Please note: if you use PragmataPro Mono versions the icons are taken by other installed fonts because **PragmataPro Mono versions doesn't include Nerd icons**

**Comment by MarioRicalde** [comment]
I have installed the font in termux (liga variant), and glyphs are displayed as emojis but strangely display similar issues ( oddly sized ).

**Comment by neuromagus** [comment]
yep, i use NNN too. W8 a new version of this best font. https://proza.ru/pics/2020/12/28/185.jpg (my old account is 'N1rdeks') And what version included Nerd? Liga? Mono Liga? or just PragmataPro? Before I disable icons...

**Comment by fabrizioschiavi** [comment]
I think to have fixed this issue! Please download the latest release (0.830) from fsd.it

**Comment by neuromagus** [comment]
thanks, please, change the version number on your site [too](https://fsd.it/shop/fonts/pragmatapro/) ;) and name of file in https://fsd.it/my-account/downloads/.

**Comment by fabrizioschiavi** [comment]
Thanks @neuromagus for your help!
