### ISSUE TITLE
How to get PragmataPro updates if I bought it in 2012?

### ISSUE THREAD

**Issue by kvtb** [fabrizioschiavi/pragmatapro#269]
I bought PragmataPro in 2012 at MyFonts.com (the only option at that time) with promised free updates until version 1.0 - the same offer as now.

Recently, MyFonts.com deleted all orders older than 2013, so I have no access to the new versions

Their support replies:

> Since your order is older than 2013, and has not been migrated to the new platform, we unfortunately cannot provide the latest version.
> The latest version is available only for the recent orders.

How can I get the updates?
Obviously, having such an experience I am not going to buy it again.

Is the pirate torrents the only option to get the new versions of font?
Or could it be restored at another shop?

**Comment by fabrizioschiavi** [comment]
Thanks for your support in past!
I suggest you to create an account at [fsd.it](https://fsd.it/) and [send me](mailto:info@fsd.it) your MyFonts receipt so I can make you download the new font files without limitations.
