### ISSUE TITLE
U+02D8 "Breve" is combining

### ISSUE THREAD

**Issue by phantamanta44** [fabrizioschiavi/pragmatapro#272]
U+02D8 "Breve" (`˘`) either combines with the previous latin letter or otherwise has zero width, but this should not be the case, as this character is in the [spacing modifier letters block](https://en.wikipedia.org/wiki/Spacing_Modifier_Letters). For reference, the combining/non-spacing variant of this character is at U+0306 "Combining Breve".

**Comment by fabrizioschiavi** [comment]
Fixed! Please download the latest release (0.830) from fsd.it
