### ISSUE TITLE
[0.30.0] Glyphs are smaller?

### ISSUE THREAD

**Issue by ahmedelgabri** [fabrizioschiavi/pragmatapro#274]
After upgrading to 0.30.0 I see a lot of glyphs becoming much smaller?

Before:

![screenshot](https://github.com/fabrizioschiavi/pragmatapro/assets/63876/a1f34754-8235-489f-824e-4bb5384eaf14)

After:

![Screenshot 2023-12-18 at 10 08 05](https://github.com/fabrizioschiavi/pragmatapro/assets/63876/f2dc51de-70ef-4ab6-a28c-047f76a3f590)

**Comment by mfocko** [comment]
Aren't you using _Pragmata Pro Mono Liga_? In the _Mono_ variant they should take up the same space, so they are “smooshed” into the box.

**Comment by ahmedelgabri** [comment]
@mfocko not following, nothing changed in my set up other than the font, so why would it be "smooshed" now in 0.30.0?

**Comment by fabrizioschiavi** [comment]
The reason behind this phenomenon is that, up to version 0.829, you were able to observe the glyphs of other installed fonts. However, starting from version 0.830 in the Mono version, you now see the authentic built-in Nerd icons of PragmataPro Mono. Notably, the width of these icons is set at 100% of the glyph width.

Admittedly, I share the sentiment that the effect might appear unattractive. Nevertheless, numerous users have expressed a preference for this change. While the optimal solution would involve a case-by-case redesign, the sheer magnitude of such a task would span years.

If you find the old design more preferable, my recommendation would be to opt for the non-Mono versions. I appreciate your understanding in this matter.

**Comment by ahmedelgabri** [comment]
@fabrizioschiavi thanks for the answer, I tried the non-Mono version, and it seems like it doesn't work in Kitty but works in other terminals. So what should I report back to Kitty when I open an issue?

Kitty

![Screenshot 2023-12-19 at 09 19 17](https://github.com/fabrizioschiavi/pragmatapro/assets/63876/05218fa0-cf60-4c0b-96b3-395f45096ec8)

WezTerm

![Screenshot 2023-12-19 at 09 33 04](https://github.com/fabrizioschiavi/pragmatapro/assets/63876/c36ddc56-e795-4e68-8ea1-0e508aea19ea)

Alacritty

![Screenshot 2023-12-19 at 09 53 48](https://github.com/fabrizioschiavi/pragmatapro/assets/63876/60502e68-ef85-4521-9e31-7ca99c3768ce)
