### ISSUE TITLE
emacs prettify symbols with 0830?

### ISSUE THREAD

**Issue by andrew-hm** [fabrizioschiavi/pragmatapro#275]
@fabrizioschiavi is a `pragmatapro-prettify-symbols-v0.830.el` needed for the latest version? I know the nerd fonts are now included so curious, thank you

**Comment by fabrizioschiavi** [comment]
I just uploaded the [pragmatapro-prettify-symbols-v0.830.el](emacs_snippets/pragmatapro-prettify-symbols-v0.830.el).
Is it so necessary to add almost 10 000 names and codepoint of nerd fonts?

**Comment by andrew-hm** [comment]
no, not necessary to add nerd fonts, thanks for update!

**Comment by andrew-hm** [comment]
the nerd fonts included in the 0830 font is brilliant. hated having to go through that process of adding them manually before.
