### ISSUE TITLE
No roman serif stylistic set

### ISSUE THREAD

**Issue by TsavyPrince** [fabrizioschiavi/pragmatapro#282]
So far there is bold serif (ss08), italic serif (ss09), and bold italic serif (ss10). Why not roman serif, with no bold or italics?

**Comment by fabrizioschiavi** [comment]
All these stylistic sets coming from the glyphs Mathematical Alphanumeric Symbols Unicode set that doesn't includes Roman Serif glyphs.
I have devised a plan to create PragmataPro Serif immediately following the release of PragmataPro 1.0. This new design aims to complement and expand upon the existing font.
