### ISSUE TITLE
symbols with backgroud

### ISSUE THREAD

**Issue by hd-deman** [fabrizioschiavi/pragmatapro#288]
<img width="1090" alt="Screenshot 2024-01-28 at 20 46 57" src="https://github.com/fabrizioschiavi/pragmatapro/assets/705532/17e422d3-1627-4312-a962-66a84c942ae3">

Can't use this symbols. I can see them in Font Book but if I copy it nothing happened on paste.  Copy/Paste work for other symbols.

**Comment by hd-deman** [comment]
how to use them and why they not included into [All chars.txt](https://fsd.it/pragmatapro/All_chars.txt)?

**Comment by fabrizioschiavi** [comment]
Symbols with a black background are alphabets specifically crafted for constructing ligatures such as `[BUG]` or `[TODO]`. Additionally, there are other symbols that I've designed, which remain unrecognized by the Unicode Consortium. These designs share characteristics with existing symbols that adhere to current guidelines.

**Comment by fabrizioschiavi** [comment]
I can add these symbols in All Chars.txt the next time but they are practically useless. Please let me know if you really need them.
