### ISSUE TITLE
I paid, but I can not receive email for login

### ISSUE THREAD

**Issue by shenghui0779** [fabrizioschiavi/pragmatapro#298]
I use the `Magic Link` or `Reset Password`, not useful. Now I can not login, and can not download, help!

Account: 847713844@qq.com
OrderNO: 11575448JU762782M

![436468408_776581601127999_759890001394930087_n](https://github.com/fabrizioschiavi/pragmatapro/assets/67535398/ade6da36-34dc-4b4b-a60e-0ac4a32ad6a9)

**Comment by fabrizioschiavi** [comment]
Thanks to buy a license @shenghui0779 ! 
It seems you already downloaded the font files.
Your access is not blocked. It's very strange that you can't access to your account again… 
Could you try again, maybe using a different browser, please?

**Comment by fabrizioschiavi** [comment]
When I try to send you an email Thunderbird show me this:
<img width="490" alt="Screenshot 2024-06-14 at 21 37 31" src="https://github.com/fabrizioschiavi/pragmatapro/assets/1576663/af5432d2-12b2-4900-8672-dd71005f69b6">
Could you check if you are able to receive email please?

**Comment by shenghui0779** [comment]
Thanks! Can you send an email to my other email address: shenghui0779@gmail.com ?

**Comment by shenghui0779** [comment]
> Thanks to buy a license @shenghui0779 !感谢购买许可证！ It seems you already downloaded the font files. 看来您已经下载了字体文件。 Your access is not blocked. It's very strange that you can't access to your account again… 您的访问未被阻止。很奇怪，你无法再次访问你的帐户...... Could you try again, maybe using a different browser, please? 您可以再试一次吗？也许使用不同的浏览器？

If that's the case, I may not be able to download new versions in the future

**Comment by shenghui0779** [comment]
> Thanks to buy a license @shenghui0779 ! It seems you already downloaded the font files. Your access is not blocked. It's very strange that you can't access to your account again… Could you try again, maybe using a different browser, please?

If that's the case, I may not be able to download new versions in the future

**Comment by shenghui0779** [comment]
> When I try to send you an email Thunderbird show me this: <img alt="Screenshot 2024-06-14 at 21 37 31" width="490" src="https://private-user-images.githubusercontent.com/1576663/339885003-af5432d2-12b2-4900-8672-dd71005f69b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MjUwMTksIm5iZiI6MTcxODQyNDcxOSwicGF0aCI6Ii8xNTc2NjYzLzMzOTg4NTAwMy1hZjU0MzJkMi0xMmIyLTQ5MDAtODY3Mi1kZDcxMDA1ZjY5YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMDQxMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDExODE1M2NjZGU2MjM2MWM2ZWExMWY4MmQxOTU0ZTZmNDQxYzhlZGEyZDA3MTQ0OGU4ZTJiZWRiYmU0MmVhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p7x3fQZ6H3xkQYXzxdzJz2PN_ejAlTQKJ6WJUDP_tOk"> Could you check if you are able to receive email please?

I checked my email settings and the domain name blacklist is empty.

**Comment by fabrizioschiavi** [comment]
I changed the email of your account to the one you suggested here. 
Please try to access again and don't forget to change the password.
Please let me know if you can download the font files now.
Thanks!

**Comment by shenghui0779** [comment]
Okay, now I can download it, thank you very much!
