### ISSUE TITLE
All_chars.txt is slightly inaccurate

### ISSUE THREAD

**Issue by kwf** [fabrizioschiavi/pragmatapro#30]
I've been implementing ligature display for Emacs using `prettify-symbols-mode`, and working off the table in `All_chars.txt`. A few characters seem to have shifted locations since when this chart was produced (or perhaps it was erroneous before; I'm not sure).

In particular, the `U+800` line is off by one: it should give the ligatures for the following sequences (presented as an elisp association list out of convenience):

```
             ("<~>"  . #xE800)
             ("<**>" . #xE801)
             ("<<^"  . #xE802)
             ("<!"   . #xE803)
             ("<@"   . #xE804)
             ("<#"   . #xE805)
             ("<%"   . #xE806)
             ("<^"   . #xE807)
             ("<&"   . #xE808)
             ("<?"   . #xE809)
             ("<."   . #xE80A)
             ("</"   . #xE80B)
             ("<\\"  . #xE80C)
             ("<\""  . #xE80D)
             ("<:"   . #xE80E)
             ("<->"  . #xE80F)
```

And then, we should have a (currently missing) line `U+810`, with these mappings:

```
             ("<!--" . #xE810)
             ("<--"  . #xE811)
```

Since these are different, I suspect that there may be other ligatures which have now been added which I haven't yet found, and which I'd definitely like to add if they exist.

Once I've completed this Emacs compatibility layer, I'll certainly publish it, and you can feel free to point people in that direction if they want ligatures in their Emacs. :)

**Comment by fabrizioschiavi** [comment]
@kwf compliments for your smart solution to bypass the Emacs limitation about ligatures!
You've right some ligature was missed in `All_chars.txt` file. I'll fix it.
Could you share with us, please, the file you produced for Emacs `prettify-symbols-mode` use?

**Comment by DeLaGuardo** [comment]
Publish my own solution, just in case
https://gist.github.com/DeLaGuardo/fe1f3d9397d6ef7468460d54d5601156

**Comment by fabrizioschiavi** [comment]
Very good job @DeLaGuardo ! Thanks!

**Comment by fabrizioschiavi** [comment]
I just fixed the `All_chars.txt` file
You can download it from [this](http://www.fsd.it/pragmatapro/All_chars.txt) url

**Comment by kwf** [comment]
Here's my own solution (mostly the same, but with a few tweaks): https://gist.github.com/kwf/dea7bc51101083acb95c875140e2a96d

**Comment by fabrizioschiavi** [comment]
Thank you @kwf !
