### ISSUE TITLE
Ligatures do not show in IntelliJ IDEA 2016.2

### ISSUE THREAD

**Issue by vasily-kirichenko** [fabrizioschiavi/pragmatapro#32]
PragmataPro 0.822:

![image](https://cloud.githubusercontent.com/assets/873919/16901058/a1367dcc-4c40-11e6-9edb-59888052ba80.png)

![image](https://cloud.githubusercontent.com/assets/873919/16901059/b469806a-4c40-11e6-938d-d87582b69576.png)

![image](https://cloud.githubusercontent.com/assets/873919/16901063/e1ae5e1a-4c40-11e6-96ed-3349a4efc7f1.png)

Other fonts, like FiraCode, they works:
![image](https://cloud.githubusercontent.com/assets/873919/16901072/1e89e11a-4c41-11e6-9b50-f46376e4ccda.png)

**Comment by talios** [comment]
I was just about to post a ticket about this, I note that the ligatures also don't show up in BB Edit - but Fira Code's do.

I only discovered the updated release now supported ligatures and was all excited ( even purchased the italic font which I didn't have originally ) - hopefully I can see ligatures in IntelliJ soon!

**Comment by DeLaGuardo** [comment]
Ligatures is available in PragmataPro fontface, not in PragmataPro Mono. [Difference between fontfaces](http://www.fsd.it/wp-content/uploads/2015/12/PragmataPro_PragmataProMono_EssentialPragmataPro.png)

**Comment by talios** [comment]
@DeLaGuardo yep, whilst the screenshot above those using Mono, I'm using the non-mono and not seeing ligatures in IntelliJ ( or BB Edit ).

**Comment by fabrizioschiavi** [comment]
@vasily-kirichenko please use v_0.823. PragmataPro works perfectly in IntelliJ since v_0.823
@talios I'll investigate on BB Edit situation. Keep in touch

**Comment by fabrizioschiavi** [comment]
@talios I have the solution to enable ligatures in BB Edit
Open `Terminal` app and digit
`defaults write com.barebones.bbedit EnableFontLigatures_PragmataPro -bool YES`
Enjoy ligatures!

**Comment by fabrizioschiavi** [comment]
I forgot to update the current version at PragmataPro page. Thanks @talios for letting me know it. 
If you purchased the license from MyFonts you must received an email notification. Anyway you can access at your account and download the new font files.

**Comment by fabrizioschiavi** [comment]
Since version 0.824 all must works fine
Otherwise take a look at my IntelliJ [settings](http://www.fsd.it/pragmatapro/IntelliJ_FSD_settings.zip)

**Comment by Saketme** [comment]
@fabrizioschiavi Are ligatures available in Essential PragmataPro?

**Comment by sliceofcode** [comment]
@Saketme No.

**Comment by Birowsky** [comment]
@fabrizioschiavi how do I get notified when you release new version of PragmataPro?

**Comment by fabrizioschiavi** [comment]
@Birowsky until 15th August 2017 I'll release version 0.826

**Comment by fabrizioschiavi** [comment]
@Birowsky anyway every PragmataPro user will receive a notification via email when the new font files are ready to download

**Comment by DavidWhit** [comment]
Hello,  First @fabrizioschiavi wow I'm impressed with the work! I just bought the full pack and got a little worried about this but I was using material-UI plugin in intellij. I checked your files above and noticed something I forgot about in settings. 

![image](https://user-images.githubusercontent.com/3008424/31135279-1cb7b2b8-a82a-11e7-97ae-19346c525990.png)
 
Now with your test from above they all look amazing
