### ISSUE TITLE
Upgrade Pricing?

### ISSUE THREAD

**Issue by alpha123** [fabrizioschiavi/pragmatapro#33]
Thanks @fabrizioschiavi for my favorite font! I'm a programmer-turned-graphic-designer-turned-programmer and really appreciate the thought and detail that went into PragmataPro. I bought Essential PragmataPro Regular about a week ago and love it. Is it possible to upgrade to the all weights+ligatures version for the difference in cost?

Thank you!

**Comment by fabrizioschiavi** [comment]
Yes @alpha123 is possible. I'll send you an email with a coupon to avoid to pay the difference.
I'm very glad you like PragmataPro 😄

**Comment by alpha123** [comment]
Thank you! I purchased all weights and the coupon worked great.

I deal with a lot of Unicode text (multiple languages, math symbols, etc) and the attention to so many glyphs convinced me to upgrade.

**Comment by fabrizioschiavi** [comment]
Thank you @alpha123 !

**Comment by demon386** [comment]
+1 for this
