### ISSUE TITLE
Ligature for ##

### ISSUE THREAD

**Issue by freebroccolo** [fabrizioschiavi/pragmatapro#34]
Would it be possible to add a ligature for `##`? It's used quite a bit in some OCaml code. Here's an [example](https://github.com/ocsigen/js_of_ocaml/blob/master/examples/webgl/webgldemo.ml#L239-L266).

**Comment by fabrizioschiavi** [comment]
Very interesting typographic mission! I'll add it. Thanks @freebroccolo

**Comment by sliceofcode** [comment]
@freebroccolo This has been added in 0.824

**Comment by freebroccolo** [comment]
Yep, just installed 0.824 and it looks great! Nice work @fabrizioschiavi 👍
