### ISSUE TITLE
Latest update (from 06-09-2016) breaks render on ArchLinux

### ISSUE THREAD

**Issue by DeLaGuardo** [fabrizioschiavi/pragmatapro#37]
![version from 30-06-2016](https://cloud.githubusercontent.com/assets/542042/18425902/7212caa4-78e7-11e6-835d-d1256e28c37e.png)
![version from 06-09-2016](https://cloud.githubusercontent.com/assets/542042/18425910/870a8b5e-78e7-11e6-9986-ab605ff8a352.png)

Looks like gliphs render with wrong baseline

**Comment by ruslanch** [comment]
Ubuntu 16.04 + Sublime Text 3 or Gnome Terminal - there is also I have some problems with the rendering of lines and character height. I rolled back to a previous version.

**Comment by wismill** [comment]
Also confirmed on openSUSE Tumbleweed (Gnome Terminal, Gedit).

**Comment by fabrizioschiavi** [comment]
Freetype was updated https://www.freetype.org/freetype2/docs/subpixel-hinting.html
Rules are changed and I need to understand better how…

**Comment by sliceofcode** [comment]
I'm on 0.824 and on latest FreeType and I am not experiencing these problems

**Comment by jan0sch** [comment]
I also noticed this a while ago but using the font release 0.824 and freetype 2.6.3 under FreeBSD the problems are gone.

**Comment by fabrizioschiavi** [comment]
Thank you to all!

**Comment by bitonic** [comment]
I'm also experiencing problems with gnome-terminal and pragmata 0825, see attached image. does not happen with 0820, I'm on ubuntu 16.04.

![screenshot from 2017-06-23 10-13-16](https://user-images.githubusercontent.com/556090/27473782-9cdbccce-5800-11e7-8dd9-02f02381d33d.png)

**Comment by fabrizioschiavi** [comment]
@vlopezj could you show me a screenshot of what you see, please? 
@bitonic this is fixable. Thanks for let me know!
