### ISSUE TITLE
font-family issue

### ISSUE THREAD

**Issue by CNMan** [fabrizioschiavi/pragmatapro#38]
![2016-09-18_061225](https://cloud.githubusercontent.com/assets/8692234/18611340/a0fea984-7d68-11e6-8120-3f3fb58e443a.png)

![2016-09-18_061657](https://cloud.githubusercontent.com/assets/8692234/18611339/9884a380-7d68-11e6-8a84-c6ecce83fcdb.png)

PragmataPro --> Pragmata Pro Regular
PragmataPro Mono --> Pragmata Pro Mono Regular

previous work config，show Regular,Bold,Italic correctly

``` vim
set guifont=PragmataPro\ Mono:h9:cDEFAULT
```

current work config，show Regular correctly，but can not show Bold,Italic

``` vim
set guifont=Pragmata\ Pro\ Mono\ Regular:h9:cDEFAULT
```

this config do not work

``` vim
set guifont=Pragmata\ Pro\ Mono:h9:cDEFAULT
```

i am using version 0.823.

**Comment by fabrizioschiavi** [comment]
Thanks! This issue are still active on latest release (0.824)?

**Comment by CNMan** [comment]
work
```
set guifont=PragmataPro\ Mono\ Regular:h9:cDEFAULT
```
don't work
```
set guifont=PragmataPro\ Mono:h9:cDEFAULT
```
![2017-02-26_182940](https://cloud.githubusercontent.com/assets/8692234/23338922/c972ffec-fc51-11e6-813e-84ce73a5c0c3.png)

**Comment by Porges** [comment]
FWIW, I have `set guifont=PragmataPro\ Mono:h11` and it works. Vim version is 8.0 (1-69). Font version is 0.824.
