### ISSUE TITLE
<something> gets strange arrow ligatures in shell output

### ISSUE THREAD

**Issue by tsdh** [fabrizioschiavi/pragmatapro#42]
I use Pragmata Pro as font in my shell (gnome-shell).  Since updating to the very recent version, it seems lots of stuff gets "ligaturized" which at least some false positives.

For example, in `hg log` I get strange ligatures for email addresses in the format "Firstname Lastname foo@bar.com".

![ligatures_in_hg_log](https://cloud.githubusercontent.com/assets/103854/18907561/5ff74a3e-856c-11e6-9191-3201a09b2cb9.png)

Oh, it seems it'll produce that with all `<something>` things.  For example, you'll also get garbled output when grepping XML/HTML files.

Oh, wait.  I can see that effect just by typing `<test>` in my terminal.

![test](https://cloud.githubusercontent.com/assets/103854/18907690/f8ae71b2-856c-11e6-9d12-96b1d962aafc.png)

**Comment by freebroccolo** [comment]
It looks like you may have discretionary ligatures enabled. This is the `dlig` opentype font feature. I don't know if `gnome-shell` enables that by default but it should not be used by default for all text with Pragmata Pro because it includes several special purpose symbolic ligatures.

**Comment by tsdh** [comment]
How would I know? Well, I'll ask on the gnome mailing list or IRC channel.

**Comment by fabrizioschiavi** [comment]
It looks like a _gnome-shell_ issue and I suppose it can be fixed by a file like [this](https://gist.github.com/DeLaGuardo/fe1f3d9397d6ef7468460d54d5601156) used for Emacs.

**Comment by tsdh** [comment]
For reference, I've filed this gnome terminal bug for this issue. https://bugzilla.gnome.org/show_bug.cgi?id=772399

**Comment by Nevel** [comment]
@tsdh Have you been able to tackle this issue? I noticed the gnome bug has been closed :(.

**Comment by Nevel** [comment]
BTW: This issue seems to have been fixed by the iterm2 developers (see: https://gitlab.com/gnachman/iterm2/issues/5030), so it probably is a gnome terminal bug indeed.
