### ISSUE TITLE
Better support to accented characters (brazilian portuguese)

### ISSUE THREAD

**Issue by gguimaraesbr** [fabrizioschiavi/pragmatapro#43]
This is the best font ever! The only thing that I miss is the support for accented characters like the ones used in the image attached:

![screen shot 2016-10-24 at 09 57 19](https://cloud.githubusercontent.com/assets/66819/19644781/6d506d96-99d0-11e6-82bc-b6c1d8304b69.png)

**Comment by fabrizioschiavi** [comment]
Thank you @gguimaraesbr for your compliments!
This happens because you bought _Essential PragmataPro_, that works only for English language and doesn’t includes accented letters.
I'll contact you soon via email to make an offer to pass at the complete version.
Thanks again 😉
