### ISSUE TITLE
Enhancement: Power symbols

### ISSUE THREAD

**Issue by fitojb** [fabrizioschiavi/pragmatapro#46]
Ciao, Fabrizio:

I was wondering if you could add the ISO/IEC/IEEE power symbols (standby, on, off…) which have been encoded in this year’s Unicode version (9.0)? 
I find the symbols useful for translating some command-line programs, due to the added length of Spanish words, but I think that there are other use cases for these symbols (such as technical documentation and manuals) that will make these additions useful for other people.

[Proposal](http://www.unicode.org/L2/L2014/14009r-power-symbol.pdf)
[Unicode 9.0’s “Miscellaneous Technical” block](http://www.unicode.org/charts/PDF/Unicode-9.0/U90-2300.pdf)

```
POWER SYMBOL         U+23FB  ⏻
POWER ON-OFF SYMBOL  U+23FC  ⏼
POWER ON SYMBOL      U+23FD  ⏽
HEAVY CIRCLE         U+2B58  ⭘
POWER SLEEP SYMBOL   U+23FE  ⏾
```
TIA for your consideration! :)

**Comment by fabrizioschiavi** [comment]
Absolutely yes! Thanks for your proposal

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
