### ISSUE TITLE
[REJECTED] New year gift

### ISSUE THREAD

**Issue by sergeevabc** [fabrizioschiavi/pragmatapro#47]
Dear Fabrizio,
Where could mere users like me download Pragmata Pro (TTF) for free on New Year’s eve?

**Comment by sliceofcode** [comment]
Here's an excerpt from the website regarding the pricing: 

> Guys, try to put in my place. Probably you have never attempted to draw fonts and, above all, optimize a font for the screen you can not realize the work that is behind such a project.
I tried, and I try, in every way a sponsorship or funding to reduce the price of the license, my dream was to offer it for free, but I don't found that and I have to sell the license at a price at least partially compensate for the effort involved realize PragmataPro.
To reduce the price now would be economic suicide for me and misconduct against those who have believed before you and have already paid the amount required.

**Comment by sergeevabc** [comment]
> My opinion about the pricing…
> It also wouldn't be fair to the people who paid for the font…

Is if fair to [hug for free][1] whereas others buy flowers and quote romantic poetry to deserve one?
Nobody expects you to refuse remuneration on a regular basis, but to [be generous][2] once in a while.
There are places to give away [for a limited time][3] with “private use only” restriction like [Input font][4] does.

[1]: https://en.wikipedia.org/wiki/Free_Hugs_Campaign
[2]: https://www.becomingminimalist.com/generous/
[3]: https://rokket.space/
[4]: http://input.fontbureau.com/download/

**Comment by CNMan** [comment]
https://github.com/be5invis/Iosevka

**Comment by msva** [comment]
Not that Iosevka will be a little close to Pragmata in "L&F". And in features.
Well, if talk about alternatives, there is also [nerd fonts](https://github.com/ryanoasis/nerd-fonts) project, which patches many opensource fonts (incl. iosevka (well, not sure about exactly it), firacode and some more) with additional glyphs.
