### ISSUE TITLE
double quote in 'PragmataPro 9'

### ISSUE THREAD

**Issue by volth** [fabrizioschiavi/pragmatapro#49]
```PragmataPro 9``` has issue with double quote: it is too hard to distinguish it from a single quote.

```Pragmata Pro 9```, version 2016.09.19:
![](http://i.imgur.com/RtMNvM4.png)

There is no issue with smaller and bigger font sizes:

```Pragmata Pro 8```, version 2016.09.19:
![](http://i.imgur.com/WB5oyw6.png)
```Pragmata Pro 10```, version 2016.09.19:
![](http://i.imgur.com/1tjCJda.png)

There is no issue with old (2015 and earlier) versions:

```Pragmata Pro 9```, version 2015.07.08:
![](http://i.imgur.com/yLx0fkR.png)

**Comment by fabrizioschiavi** [comment]
I’ll fix it soon as possible. Thanks for letting me know!

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
