### ISSUE TITLE
Add symbol :<: for Scala?

### ISSUE THREAD

**Issue by 4lex1v** [fabrizioschiavi/pragmatapro#50]
Just bought your fonts, amazing work! Thank you.

I've noticed that there's no ligature for `:<:`, would it be hard to add one? I'm using it in various projects, e.g there's an [alias](https://github.com/typelevel/cats/blob/master/free/src/main/scala/cats/free/package.scala#L12) defined in a library, but i't would be awesome to see it in the font

**Comment by fabrizioschiavi** [comment]
I'll add `:<:` with pleasure in the next release. Thanks for supporting my project!

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
