### ISSUE TITLE
Intellij IDEA */ << >> ligature issue

### ISSUE THREAD

**Issue by jkramr** [fabrizioschiavi/pragmatapro#51]
I have a problem with rendering some ligatures in Intellij IDEA like */ and >> or <<
But only in "no antialiasing mode". Also, the problem is solved by turning off the ligatures, but it kills the whole point.

Examples below:

No antialiasing, ligatures enabled
![screen shot 2017-03-07 at 2 18 06 am](https://cloud.githubusercontent.com/assets/1822434/23636169/97ac0008-02dc-11e7-8bb1-be32c4efa0ee.png)
No antialiasing, ligatures disabled
![screen shot 2017-03-07 at 2 18 27 am](https://cloud.githubusercontent.com/assets/1822434/23636191/af01c224-02dc-11e7-990a-e2cc45415a31.png)
Greyscale, ligatures enabled
![screen shot 2017-03-07 at 2 18 59 am](https://cloud.githubusercontent.com/assets/1822434/23636207/bed2092a-02dc-11e7-9f1d-4220c95b4aa8.png)

**Comment by fabrizioschiavi** [comment]
This is really strange. Are you on Mac or Windows?

**Comment by jkramr** [comment]
On Mac. Haven't tried other editors, though. This strange offset is also present in a terminal. The ligature immediately jumps a half it's width to the right.

**Comment by jkramr** [comment]
Reproducing only with <<, >>, ***, */. Haven't tested more than those though:

![screen shot 2017-03-07 at 8 58 04 pm](https://cloud.githubusercontent.com/assets/1822434/23672872/d54ff738-0378-11e7-8709-fe68d4c7406b.png)

![screen shot 2017-03-07 at 8 58 18 pm](https://cloud.githubusercontent.com/assets/1822434/23672882/d7e9d518-0378-11e7-89aa-f80c97c5259b.png)

**Comment by fabrizioschiavi** [comment]
Do you use PragmataPro 0.824?

**Comment by jkramr** [comment]
Yes. Last version. 0.824
![screen shot 2017-03-07 at 9 02 55 pm](https://cloud.githubusercontent.com/assets/1822434/23673046/7bdb1b14-0379-11e7-9bee-84e22bbfd749.png)

**Comment by fabrizioschiavi** [comment]
Thank you Julia for letting me know this issue. I hope to find the solution very soon.

**Comment by fabrizioschiavi** [comment]
I thinks to fixed it since [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) 0.826 version. Could you confirm please? Thanks!
