### ISSUE TITLE
Be more conservative for ligatures on long repeated groups

### ISSUE THREAD

**Issue by zxaos** [fabrizioschiavi/pragmatapro#52]
Lines of ligature-enabled characters sometimes look pretty strange:

<img width="587" alt="screen shot 2017-03-08 at 13 00 18" src="https://cloud.githubusercontent.com/assets/891202/23719344/9bb0c4e8-0400-11e7-8a43-fe0690a5ad20.png">

Fira code also had this issue and somehow disabled ligatures for >3 groups of equals: https://github.com/tonsky/FiraCode/issues/110

**Comment by fabrizioschiavi** [comment]
This is the first issue I fixed working at the next release (0.825). Thanks for letting me know.

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
