### ISSUE TITLE
Add support for vim-devicons

### ISSUE THREAD

**Issue by xguerin** [fabrizioschiavi/pragmatapro#53]
Hey there,

Would it be possible to add support for https://github.com/ryanoasis/vim-devicons ?

There is always patching, but the patcher somehow screws up the font properties and ligatures are not available anymore.

Thanks for such a great font,

**Comment by fabrizioschiavi** [comment]
I would like to add these icons but in Unicode PUA (Private Use Area) I have already positioned a lot of useful glyphs, and it is very difficult to move another area keeping all working.
I’ll try it.

**Comment by ryanoasis** [comment]
@xguerin Alternatively you can attempt to patch the font via [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts)

**Comment by xguerin** [comment]
@ryanoasis Yes, this is what I did, but as I mentioned in my OP, I somehow lose the ligatures, even when I use the `--careful` flag.

To be even more accurate, the latest nightly of `iTerm` recognizes that the original font has ligatures and offers to enable them. However, after patching the font, `iTerm` somehow does not recognize it as having ligatures and therefore does not offer to enable them.

TBH I did not try with other tools, like MacVim for instance.

**Comment by ryanoasis** [comment]
Thanks for the info. Aware of the ligatures being lost... hopefully we can do something for that.

**Comment by xguerin** [comment]
I just saw that you added the fonts in 0.825. This is **awesome**. Thanks so much for this !

**Comment by pkazmier** [comment]
Just discovered that my favorite font has had support for devicons! I don’t know how I missed this before! Thanks again for a great font! Best purchase I’ve made in recent years!
