### ISSUE TITLE
Macvim clips some symbols

### ISSUE THREAD

**Issue by jordwalke** [fabrizioschiavi/pragmatapro#54]
<img width="638" alt="screen shot 2017-04-03 at 10 54 08 pm" src="https://cloud.githubusercontent.com/assets/977348/24643151/e1b529dc-18c0-11e7-8bfd-63d3db1fa868.png">

Here's what happens with pragmatapro (and the mono version).

Setting `ambiwidth=double` solves a couple of them, but I notice that other fonts don't require setting `ambiwidth` to correctly render these symbols. Setting `macligatures` on/off doesn't help.

They render fine on the terminal (iTerm).

**Comment by fabrizioschiavi** [comment]
Thanks Jordan to letting me know. 
[Here](https://github.com/macvim-dev/macvim/issues/267) is explained the reason of this issue

**Comment by jordwalke** [comment]
So it is unsolveable?

**Comment by fabrizioschiavi** [comment]
Ligatures works?

**Comment by jordwalke** [comment]
Yes, Ligatures work well, but don't solve this problem.

**Comment by fabrizioschiavi** [comment]
No, but I can solve the problem using the method behind ligatures programming. This is a very good news!

**Comment by jordwalke** [comment]
Oh great! So PragmataPro would use ligatures to render these double width glyphs?

**Comment by fabrizioschiavi** [comment]
Yes, but it represent another **BIG** amount of work to add at the already **BIG** todo list

**Comment by jordwalke** [comment]
Understood!

**Comment by jordwalke** [comment]
Is there something MacVim could/should do to make this easier? Why does the terminal and other apps have no problem? Should MacVim be more like them?

**Comment by jordwalke** [comment]
Pragmata is not the only one with the problem in Macvim, so it might not be your battle to fight anyways!
