### ISSUE TITLE
Main website has a JS error

### ISSUE THREAD

**Issue by liamgriffiths** [fabrizioschiavi/pragmatapro#55]
Visiting: https://www.fsd.it/shop/fonts/pragmatapro/

<img width="486" alt="screenshot 2017-04-06 10 36 38" src="https://cloud.githubusercontent.com/assets/179645/24759902/f3a8bc80-1ab4-11e7-87b2-88f2058cb1c1.png">

**Comment by fabrizioschiavi** [comment]
Thanks @liamgriffiths !
I updated some files of my site and now it must be all ok. 
Can you confirm?

**Comment by liamgriffiths** [comment]
@fabrizioschiavi maybe it will take a moment to update - but at least for now I'm still getting the same error.

**Comment by fabrizioschiavi** [comment]
Could you try again now please?

**Comment by liamgriffiths** [comment]
hell yeah 🎈 looking good!

**Comment by fabrizioschiavi** [comment]
Fantastic! Thank you to let me know!

**Comment by liamgriffiths** [comment]
great! going to give it a whirl 💃
