### ISSUE TITLE
Missing powerline symbol

### ISSUE THREAD

**Issue by jalaziz** [fabrizioschiavi/pragmatapro#57]
It seems that PragmataPro Regular font is missing a powerline symbol.

The symbol is a lock icon with value U+E0A2. The other styles appear to contain the symbol.

I believe that's the only missing symbol according to https://github.com/powerline/fontpatcher/blob/develop/fonts/powerline-symbols.sfd.

PragmataPro
![PragmataPro](https://cloud.githubusercontent.com/assets/247849/24891821/2bcf9a2c-1e2d-11e7-9679-4f2a73a48bd5.png)

Fira Code
![Fira Code](https://cloud.githubusercontent.com/assets/247849/24891815/20e5b2c2-1e2d-11e7-9892-1989fda340f1.png)

**EDIT**: I just checked all the styles (including Mono). It appears that all the Mono styles have all the symbols, PragmataPro Regular is missing  one symbol, and PragmataPro Italic is missing 3 (E0A0-E0A2).

**Comment by fabrizioschiavi** [comment]
Soon I’ll release version 0.825 where this and other Powerline symbols will be included. Thanks!

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
