### ISSUE TITLE
☴ (U+2634) and ☶ (U+2636) have the same glyph

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#58]
These glyphs are the same but they should be different (as in the issue title):

![image](https://cloud.githubusercontent.com/assets/12575/25302119/4f9f0ed2-277a-11e7-80d9-5831a5c52495.png)

**Comment by fabrizioschiavi** [comment]
I’ll fix it soon. Thanks for your notification!

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
