### ISSUE TITLE
⧢ (U+29E2 SHUFFLE PRODUCT) glyph is broken

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#59]
Looks like there's an incorrect coördinate here:
![image](https://cloud.githubusercontent.com/assets/12575/25302151/14fa37ce-277b-11e7-832e-0130ceb23adc.png)

**Comment by fabrizioschiavi** [comment]
I’ll fix it soon. Thanks for your notification!

**Comment by fabrizioschiavi** [comment]
Fixed since [v_0.825](https://www.fsd.it/shop/fonts/pragmatapro/). Thank you!
