### ISSUE TITLE
Powerline Support?

### ISSUE THREAD

**Issue by jimzhan** [fabrizioschiavi/pragmatapro#6]
As far as I'm concerned, the only missing one is powerline (glyph) supports for shell, any plans?

**Comment by myshov** [comment]
@jimzhan Did you read help of airline? Please read costumization section of the help file. There are some additional instructions to get glyphs working. For example you need to set additional variables in your .vimrc or somewhere, like that:

`let g:airline_left_sep = ''`

and so on.

P.S. @fabrizioschiavi by the way I didn't buy your font yet. I just want to know in which version of the font pack (essential or complete) I can get powerline glyphs and cyrrilyc glyphs?

**Comment by jibsen** [comment]
I use airline as well, and setting the encoding to utf-8 made it work for me;

    set guifont=PragmataPro:h10
    set encoding=utf-8
    let g:airline_powerline_fonts=1

**Comment by fabrizioschiavi** [comment]
@myshov the [Complete](http://www.fsd.it/fonts/pragmatapro/all_mac_18.htm) pack includes also cyrillic glyphs 
[Essential](http://www.fsd.it/fonts/pragmatapro/essential_pragmatapro.htm) pack includes essential glyphs for english coding 
Thanks for the interest!
@jibsen @myshov Thanks also for this help to identify the issue (still unclear to me)
