### ISSUE TITLE
Asymmetric digits in PragmataPro 10 v0.825

### ISSUE THREAD

**Issue by volth** [fabrizioschiavi/pragmatapro#61]
2015.07.08:
![](http://i.imgur.com/519Idxw.png)
2016.09.19:
![](http://i.imgur.com/Nen5Jcu.png)
2017.05.05 (v0.825):
![](http://i.imgur.com/OMdukXE.png)

You see, in the last version the digits are strange.
```0``` is not symmetric, other digits are worse than in the older versions
The letters are not so bad, but in comparison with the older version some of them (B, X, ...) look worse than before

The problem is only with size 10.
8, 9, 11, 12 are ok

**Comment by fabrizioschiavi** [comment]
I’ll fix this soon. Thanks!

**Comment by fabrizioschiavi** [comment]
Fixed since [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) 0.826 version
