### ISSUE TITLE
PragmataProMono has different smiley ligature.

### ISSUE THREAD

**Issue by jordwalke** [fabrizioschiavi/pragmatapro#62]
<img width="754" alt="screen shot 2017-05-26 at 5 07 49 pm" src="https://cloud.githubusercontent.com/assets/977348/26516105/38a6540c-4236-11e7-8781-4ca63627df68.png">

<img width="757" alt="screen shot 2017-05-26 at 5 08 13 pm" src="https://cloud.githubusercontent.com/assets/977348/26516107/39f0da80-4236-11e7-9d29-8d1315bcdd34.png">

I believe that the Mono version of the font should still match the non-Mono version, right?

**Comment by fabrizioschiavi** [comment]
So we’ll have 2 non-Mono versions. 
I’m sorry but this is no possible
(Smile isn’t a ligature and this symbol is 2 times wide than a regular glyph)

**Comment by jordwalke** [comment]
Is it not possible to make a smiley face that looks similar to the round smiley face in the mono font?

**Comment by freebroccolo** [comment]
Looking at those screenshots, the mono smiley could be made rounder but it would probably look too small in single-width in comparison to the double-width character in the first image.

**Comment by fabrizioschiavi** [comment]
Exact! @freebroccolo has reason. Anyway I’ll find a better solution. 
Thanks to all!

**Comment by jordwalke** [comment]
I think a scaled down rounded smiley would be just perfect.

**Comment by jordwalke** [comment]
Maybe it's worth auditing a bunch of the double wide glyphs to make sure the mono versions look somewhat similar even if scaled. I noticed some others are dramatically different as well.

**Comment by fabrizioschiavi** [comment]
Smile pictogram was improved in Mono version, obviously they can’t be the same of PragmataPro non Mono but now are more compatible and recognizable
