### ISSUE TITLE
The APL symbol ○ (25CB) does not render properly

### ISSUE THREAD

**Issue by abrudz** [fabrizioschiavi/pragmatapro#63]
It seems to fall back on another font, causing misalignment. Being that you officially support APL, this glyphs should be included. See 13th character on the first line in the screenshot.

![image](https://user-images.githubusercontent.com/10961427/26903585-d6bf28c8-4bd5-11e7-8899-7c56cfc51e84.png)

**Comment by fabrizioschiavi** [comment]
I’ll adjust the weight of this and other geometric shapes. Thanks for this notification

**Comment by fabrizioschiavi** [comment]
Fixed since [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) 0.826
