### ISSUE TITLE
<|| ligature is broken

### ISSUE THREAD

**Issue by MadPitman** [fabrizioschiavi/pragmatapro#65]
Hi,

<|| ligature is shown as |||. I'm on Mac. I tried with iTerm2 (3.1.x) and IntelliJ IDEA. 

Thanks

**Comment by fabrizioschiavi** [comment]
Ops! Sorry, I’ll fix it. Thank you

**Comment by fabrizioschiavi** [comment]
Fixed since [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) 0.826
