### ISSUE TITLE
Ligature for monadic map

### ISSUE THREAD

**Issue by xguerin** [fabrizioschiavi/pragmatapro#66]
Hello !

The font has ligatures for monadic bind `>>=` and `=<<`, but none for monadic map `>>|` and `|<<`.

Would it be possible to add them ? Even though they seem to be mostly used in `OCaml` (https://ocaml.janestreet.com/ocaml-core/109.11.00/doc/core/Monad.Infix.html) ?

Thanks,

**Comment by fabrizioschiavi** [comment]
I’ll add them. Thanks!

**Comment by fabrizioschiavi** [comment]
Added since [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) 0.826

**Comment by xguerin** [comment]
Thanks !
