### ISSUE TITLE
Dimential issues with freetype 2.8

### ISSUE THREAD

**Issue by volth** [fabrizioschiavi/pragmatapro#68]
freetype 2.8 unable to determine correct height of Pragmata Pro font:

```
pango-view --font='Pragmata Pro 14' --markup --text '
╟─────────────────────────────────────────┴──────╢
║font             20 user   users  02/07/17 18:13║
╚═════════════ 150 bytes in 3 files ═════════════╝
'
```

![](http://i.imgur.com/P5hZXvx.png)

Github blurred the image, here the direct link: http://i.imgur.com/P5hZXvx.png

It happens with all version Pragmata Pro from 2015 to 2017 year (I have not tested the older versions) and with almost all sizes (there is no issue only with font size 8, 12 and 20)
There is no issue with freetype 2.7.1

**Comment by fabrizioschiavi** [comment]
I thinks to fixed it since PragmataPro 0.826 version. Could you confirm please? Thanks!

**Comment by volth** [comment]
Yes, that works.
Sorry for the delay, I just downgraded ```freetype``` back then and so had no problem.
freetype 2.9 + PragmataPro 0.826 have no this problem

**Comment by volth** [comment]
oops.
No problem with "PragmataPro Mono" only.
"PragmataPro" still has the issue

**Comment by volth** [comment]
No, still an issue :(

**Comment by volth** [comment]
It seems very per-program.
For example there is no issue at all in ```xterm``` but almost always in ```xfce4-terminal``` (and in ```pango-view```).
So it could be fixed in those programs

**Comment by fabrizioschiavi** [comment]
Ah ok. Thank you for your investigation!
