### ISSUE TITLE
C# logo and C# ?. operator

### ISSUE THREAD

**Issue by dsaf** [fabrizioschiavi/pragmatapro#69]
C# is a major language on par with Java.
Could you please add:

* C# logo glyph
* ```?.``` C# conditional navigation ligature

**Comment by dhouck** [comment]
The `C#` logo replaces the `#` with a `♯` (sharp sign).

I think other places use `?.`, but what would it look like?

**Comment by dsaf** [comment]
You are right, there might not even be an official C# logo beyond that...

I assumed all other things like ```??``` and ```&&``` just put characters closer to each other?
![image](https://user-images.githubusercontent.com/3845650/28989681-e76b6968-796e-11e7-9dac-e7a3ba9e1326.png)

**Comment by dsaf** [comment]
Fira Code seems to have it. I guess it would be nice to match the missing ones from there:

https://github.com/tonsky/FiraCode/raw/master/showcases/all_ligatures.png

**Comment by fabrizioschiavi** [comment]
No problem, I'll add the ligatures with pleasure. Thanks for your suggestion and help!

**Comment by Porges** [comment]
Just checking, we're not talking about making "C#" a ligature, but providing an additional Private Use codepoint? I think this would be best achieved by pushing one into the "upstream" *[devicons](https://vorillaz.github.io/devicons)* font (which is aggregated by [Nerd Fonts](http://nerdfonts.com/) and included in Pragmata Pro).

**Comment by fabrizioschiavi** [comment]
Ladies and gentlemen, I just created the required ligatures. It’s all ok?
![screen shot 2017-08-08 at 11 53 38](https://user-images.githubusercontent.com/1576663/29066769-88c53ab4-7c30-11e7-8aea-b34c5de18dea.png)

**Comment by dsaf** [comment]
@fabrizioschiavi ```C#``` should probably _not_ be added as a ligature at this point as @Porges mentioned (though it looks cool!). It's more of an font-icon rather than a true practical ligature. Sorry about my confusion - I am new to fonts!

The ```?.``` looks pretty good - thank you!
