### ISSUE TITLE
Connect the |> ligature

### ISSUE THREAD

**Issue by rvlzzr** [fabrizioschiavi/pragmatapro#71]
Is is possible to get the `|>` ligature modified to be a full triangle without the small gap between the two characters? This would make it more consistent with the `<>` ligature which is connected and looks great.

The gap looks ok at large font sizes, but at smaller sizes it looks kind of bad compared to the fira code gapless triangle.

**Comment by wismill** [comment]
@fabrizioschiavi +1 to keep the current symbol
