### ISSUE TITLE
Bad hinting of some letters at 12 pt in macOS

### ISSUE THREAD

**Issue by Tekl** [fabrizioschiavi/pragmatapro#72]
I'm using PragmataPro 0.826 in the Terminal of macOS High Sierra with 12 pt. I've disabled LCD font smoothing (because I need screenshots for printing). The top line in the following image shows the actual rendering, the bottom line is how I think it should look alike.
![pragmata_m_hinting](https://user-images.githubusercontent.com/3667947/29750389-3b859c58-8b3f-11e7-85c3-fe2ed6d1fe3b.png)

The bold m has also issues:
![pragmata_boldm_hinting](https://user-images.githubusercontent.com/3667947/29750574-3c9f20ca-8b42-11e7-9c12-f94beae6c413.png)

Well, the character I and l are also not so sharp like the 1:
![pragmata_il_hinting](https://user-images.githubusercontent.com/3667947/29750430-c20bbc4e-8b3f-11e7-8cf6-0c294b5261de.png)

The same goes for the single pipe symbol | which is much sharper in the double ligature:
![pragmata_ _hinting](https://user-images.githubusercontent.com/3667947/29750456-2178f0ac-8b40-11e7-9acf-d29414df7e27.png)

The letters w and i are rendered somewhat darker then the others. I don't know if my suggestion would break the characterisics of the font. 
![pragmata_wi_hinting](https://user-images.githubusercontent.com/3667947/29750539-ac092222-8b41-11e7-8636-6639a1a4a096.png)

**Comment by fabrizioschiavi** [comment]
Unfortunately this can't be fixed.
![screen shot 2017-08-28 at 17 32 14](https://user-images.githubusercontent.com/1576663/29780866-a1504fe6-8c17-11e7-930b-df1ec8f3505c.png)
When the designer meet a grid of 6 column of pixels and the three stems of the letter falls in the middle of the column separation, there is nothing he can do :frowning_face:

**Comment by Tekl** [comment]
Oh, that's sad. I thought hinting is exactly made for correcting these cases, so you can move A and B 0,5 pixels left and right. Maybe I understand it wrong.

> Type and web designers usually think of “hinting” as instructions built into digital fonts to improve their rendering on a grid of pixels. Hinting pushes the points of a font’s Bézier curves around according to contextual conditions, such as the font’s rendering size. Though it’s now associated with type on screens, hinting was first used in the 1980s to improve rendering on low-resolution printers.

https://alistapart.com/column/font-hinting-and-the-future-of-responsive-typography

**Comment by fabrizioschiavi** [comment]
What I would like to explain you is just wrote in the article you submitted me at this sentence:

> “yes, Apple—whose rendering engines now all but ignore hinting data”

For this we have this non fixable situation.
Pixels are already in their right position, believe me, but Apple ignore this.

![screen shot 2017-08-30 at 13 17 58](https://user-images.githubusercontent.com/1576663/29870369-635dd78c-8d87-11e7-81b3-1750d7be2445.png)

**Comment by Tekl** [comment]
Thanks. That's really awkward. I thought Apple is doing different but I didn't know they ignore hinting completely. 

As I don't take screenshots from Terminal I could change the font smoothing to LCD for the Terminal only, that makes the font more readable in small sizes:

`defaults write com.apple.Terminal AppleFontSmoothing -int 1`
