### ISSUE TITLE
Documenting what the PUA codeblocks are

### ISSUE THREAD

**Issue by scw** [fabrizioschiavi/pragmatapro#74]
Hello,

Thanks for all your work on Pragmata Pro, it's great. Would it be possible to label the values in the [Private Use Area](https://www.fsd.it/pragmatapro/All_chars.png) section of the table? Some of these I recognize from other projects, but for many it'd be great to have some context to know what these glyphs are intended to be used for.

Thanks,
Shaun

**Comment by fabrizioschiavi** [comment]
This is a good idea. I'll do it. Thanks!

**Comment by fabrizioschiavi** [comment]
I have open [this](https://github.com/fabrizioschiavi/pragmatapro-semiotics) git repo with the **semiotics of all the symbols and signs of Pragmata Pro typeface**. To complete the files with informations is not so easy but I hope to find time to complete it soon.
Can this repo be useful to you?

**Comment by scw** [comment]
@fabrizioschiavi The semiotics site is perfect, thank. you!
