### ISSUE TITLE
List of iOS Editors and Terminal Apps which support PragmataPro

### ISSUE THREAD

**Issue by Tekl** [fabrizioschiavi/pragmatapro#75]
***Look at this [wiki page](https://github.com/fabrizioschiavi/pragmatapro/wiki/List-of-iOS-Apps-which-support-PragmataPro) for an updateded list of Apps.***

---

PragmataPro is a fantastic font for writing mobile, especially on the iPhone. There are a lot of Apps out there, but only some of them allow you to change the font.

## Two ways to get the font into your App

1. **In-App-Install**: You directly open the font with your App via the share sheet.

2. **Profile**: You can install fonts globally in iOS with [AnyFont](https://itunes.apple.com/us/app/anyfont/id821560738?mt=8) or [Fonteer](https://itunes.apple.com/us/app/fonteer/id1065830434?mt=8). Those Apps creates an iOS configuration profile with the selected fonts. 

## Text editors for iOS which support custom fonts

App                  | In-App-Install  | Profile
-------------- | -------------- | --------------
Bear | – | –
Boostnote | – | –
Buffer Editor | – | –
Byword | – | –
Coda | ✓ [instructions](https://library.panic.com/coda-ios/cios-custom-font/) | –
Drafts  | – | ✓
Editha | – | ✓
Editorial | – | –
GoCoEdit | – | –
iA Writer | – | –
Koder | – | –
MWeb | – | –
Notes | – | –
Pages | – | ✓
Pythonista | ✓ [complicated](https://forum.omz-software.com/topic/3419/share-code-custom-editor-font) | –
Textastic 6 | – | –
Ulysses | ✓ | ✓
Working Copy | – | –

## Terminal Apps for iOS which support custom fonts

App                  | In-App-Install  | Profile
-------------- | -------------- | --------------
Terminus | – | –

**Comment by fabrizioschiavi** [comment]
Thanks for this precious information! I never tested PragmataPro with iOS editors but I’ll do.
I'll keep you informed. Thanks again

**Comment by Tekl** [comment]
I created a [wiki page](https://github.com/fabrizioschiavi/pragmatapro/wiki/List-of-iOS-Apps-which-support-PragmataPro) for the list, you could close this task.

**Comment by fabrizioschiavi** [comment]
You are an angel @Tekl ! 
Thank you very much!!
