### ISSUE TITLE
Mono version does not work with vim-devicons.

### ISSUE THREAD

**Issue by Reisen** [fabrizioschiavi/pragmatapro#77]
I noticed that all the symbols from NERD fonts were brought into Pragmata to support vim-devicons and others (issue #53). It seems that they only work with `PragmataPro` though, and not `PragmataPro Mono`. Terminals such as mintty which can't use non mono-space fonts display all these characters as empty boxes.

**Comment by fabrizioschiavi** [comment]
Unfortunately all the Nerd font symbols are double width, so they aren’t compatible with Mono version. The solution is maybe to compress these symbols but do you really like stretched symbols?

**Comment by Reisen** [comment]
There are single width nerd font's, but you are right. After quickly trialing them, they look squashed and horrible:

![image](https://user-images.githubusercontent.com/158967/30806741-d9230ad4-a1ee-11e7-9a7e-0ca16b24580c.png)

I suppose usage in terminals on Windows for now is just a no go.

**Comment by nomasprime** [comment]
Wish I'd seen this before purchasing but then I switched to the non-mono version and everything still seems to work OK, i.e., glyphs that should be monospaced are and the rest aren't. Is this correct @fabrizioschiavi?

**Comment by kaspergrubbe** [comment]
The patching script from nerdfonts does have an option to patch only with single width (but I'm not sure how that works):

```
  -s, --mono, --use-single-width-glyphs
                        Whether to generate the glyphs as single-width not double-width (default is double-width)
```

Can that be used here @fabrizioschiavi ?

**Comment by fabrizioschiavi** [comment]
Fixed! I've added vim-devicons in Mono versions too.
Please re-download the font files from fsd.it

**Comment by kaspergrubbe** [comment]
That's awesome, thanks! :)
