### ISSUE TITLE
Change the name of the non-ligature fonts?

### ISSUE THREAD

**Issue by johnhamelink** [fabrizioschiavi/pragmatapro#78]
Hey there,

I'm both an Emacs and a Linux user - I wanted to use PragmataPro in Emacs with @DeLaGuardo's ligature configuration as well as the non-ligature version of PragmataPro in termite, my VTE-based terminal editor (because libVTE doesn't support ligatures yet). However, it seems that the non-ligature version of the font has the same name as the ligature version. I had to edit the non-ligature version in font forge to change its name so I could install them both at the same time.

I was wondering if this should be considered a bug?

**Comment by fabrizioschiavi** [comment]
Thanks @johnhamelink ! Yes, the next release will includes different names to make possible to use all the fonts without conflicts

**Comment by x-ji** [comment]
Any update on this? This would be very helpful for all Linux users.

**Comment by fabrizioschiavi** [comment]
Since 0.827 the naming will be the following:
![screen shot 2018-09-07 at 18 29 04](https://user-images.githubusercontent.com/1576663/45231327-f26af080-b2cb-11e8-93d2-073e6e3a23b4.png)
