### ISSUE TITLE
Cursive styleset for italic

### ISSUE THREAD

**Issue by SimonMeskens** [fabrizioschiavi/pragmatapro#79]
Someone showed me this combination of Operator Mono for italic text, with Fira Code for regular text:

![example](https://i.imgur.com/x1aeeIV.png)

I think this is a really interesting visual style, but the fonts showcased don't mash perfectly (it's better than expected though). I was thinking something like this might be a really cool addition for PragmataPro, maybe as a styleset for PragmataPro Italic.

What are your thoughts?

**Comment by freebroccolo** [comment]
I think stylistic set 6 already does this.

**Comment by SimonMeskens** [comment]
Ah yes, I seem to have missed that one. I'll give that a try, thanks.
