### ISSUE TITLE
Position of dash

### ISSUE THREAD

**Issue by jibsen** [fabrizioschiavi/pragmatapro#8]
The dash character is positioned so it does not align with the middle of greater than and equal. This means thinks like `->` and `-=` look a bit odd (at least to me). Here is a screenshot:

![ppro_dash_z](https://cloud.githubusercontent.com/assets/1367512/5606345/a1820afe-942b-11e4-9c79-115b15627d59.png)

And for comparison, here is a screenshot where I moved the dashes down one pixel:

![ppro_dash_aligned_z](https://cloud.githubusercontent.com/assets/1367512/5606359/f8226e6c-942b-11e4-9e6c-44625f33a029.png)

In computations it does not align vertically with `+` either. I can see that the `*` is positioned similar to the dash though.

I was just wondering if there is a reason for the position of the dash?

**Comment by jibsen** [comment]
Btw, it looks like the dash is in the "right" position in the italic and bold styles.

**Comment by rwmpelstilzchen** [comment]
What OS and PragmataPro version do you use?

On my system (gVim 7.4.537 running on Arch Linux with GTK+ 2 2.24.25-1 and PragmataPro version 0.817) it works fine on all reasonable sizes (see below a screenshot with `set guifont=PragmataPro\ 13`).
As this looks like something that can be caused by wrong hinting configuration, here is the relevant part of my `.gtkrc-2.0`:

    gtk-xft-antialias=1
    gtk-xft-hinting=1
    gtk-xft-hintstyle="hintfull"
    gtk-xft-rgba="rgb"

![PragmataPro on gVim](https://cloud.githubusercontent.com/assets/3979978/5608169/30520be2-9483-11e4-9d4e-1ea08e3390ec.png)

**Comment by rwmpelstilzchen** [comment]
What system do you use (OS, windowing system, toolkit, editor)? It looks like you use PragmataPro 0.820 but without ligatures. For some reason the `-` in this version is a little bit higher; @fabrizioschiavi, is this deliberate?

**Comment by jibsen** [comment]
The screenshots are from Sublime Text 3 running on Win7 64. I have `font_options` set to `directwrite`, but I am seeing the same position of the dash with `subpixel_antialias`. I am not aware of any options to control the hinting.

It looks the same in gvim and atom on this machine.

**Comment by fabrizioschiavi** [comment]
Thanks @jibsen and @rwmpelstilzchen  for let me know this my fault!
I forgot to change a basic command to truetype hinting, now is fixed
You'll see correct aligment from the next release. Thanks again!!

**Comment by jibsen** [comment]
That sounds great, thanks!

Is there some way to control the use of ligatures? perhaps turn them off? On Windows it seems like some apps use them and some do not. Here is Notepad2:

![ppro_ligatures_notepad2](https://cloud.githubusercontent.com/assets/1367512/5628726/83b7db62-95ab-11e4-834c-983318dca5bc.png)

and Total Commander's Lister:

![ppro_ligatures_dnlister](https://cloud.githubusercontent.com/assets/1367512/5628731/928450c6-95ab-11e4-9442-df363e58c360.png)

I guess it is something in the way the application loads the font that chooses what features to use, but without user control, I think I would prefer them turned off for consistency.

**Comment by fabrizioschiavi** [comment]
You've right. From the next release I'll include two kind of font families: PragmataPro with ligatures and PragmataPro without ligatures
Editors are always retarded respect OpenType features — unfortunately — so to avoid this kind of inconveniences I must take this way

**Comment by jibsen** [comment]
Thanks again :+1:

**Comment by fabrizioschiavi** [comment]
Fixed since v0.821
