### ISSUE TITLE
Upgrading License

### ISSUE THREAD

**Issue by automaticlightyears** [fabrizioschiavi/pragmatapro#80]
Hi Fabio,

I recently purchased "PragmataPro Regular with PP Mono Regular" option from your website.  I wanted to "demo" the version with ligatures without pirating your font and compare it to the current fonts that I used (Fira Code and Hasklig).

I am very satisfied with my purchase and would like to purchase the "All" version for desktops which comes with the bold, italic and bold/italic variants.  I was wondering if there is a way to "upgrade" my current purchase to get the additional weights without having to purchase a completely new license at full price?

**Comment by fabrizioschiavi** [comment]
No problem, [contact](https://www.fsd.it/contact-me/) me directly and I'll send you a coupon to order the `PragmataPro complete pack` without paying twice the `Regular` weight license
