### ISSUE TITLE
Ligatures that has `|` character are too high.

### ISSUE THREAD

**Issue by DeLaGuardo** [fabrizioschiavi/pragmatapro#81]
![Bouncing line](https://media.giphy.com/media/xT9IgkPzpT2WDxAsRG/giphy.gif)
I hope this gif is able to describe the issue. I can reproduce this issue with any ligatures that contain `|` character.

**Comment by fabrizioschiavi** [comment]
Thanks @DeLaGuardo for letting me know this. I'll fix it soon

**Comment by dop** [comment]
Having the same issue, 0.826 in Emacs. Maybe there's something wrong with Emacs font rendering here?
