### ISSUE TITLE
:: intermittently renders as ' :'

### ISSUE THREAD

**Issue by wezm** [fabrizioschiavi/pragmatapro#83]
I'm running Arch Linux with GNOME desktop environment. I've configured the system + Firefox to use PragmataPro for monospaced text, which is in general nothing short of glorious. I have noticed a strange ligature issue when viewing code on GitHub though. When `::` should appear, sometimes the first : is missing. E.g. note that that one of them has `::` the other ` :`:

![screenshot from 2017-10-17 10-02-23](https://user-images.githubusercontent.com/21787/31639192-31328ed0-b323-11e7-9b92-49a72c9c10b4.png)

Any thoughts? Not sure if it's the font, Firefox, or pango that's to blame (if it's not expected behaviour).

**Comment by fabrizioschiavi** [comment]
I checked again with the latest version and I didn’t see this. Do you use version 0.826?

**Comment by wezm** [comment]
You're right, I wasn't running the latest version. I upgraded to 0.826 and it's working now. Thanks for your help and sorry for the noise.
