### ISSUE TITLE
Making a sylistic set the main font option

### ISSUE THREAD

**Issue by CodeMonkeyMike** [fabrizioschiavi/pragmatapro#84]
Hi there, I am looking to use the Pragmatapro Mono Italic with Stylistic Set 6 (ss06) as my main Italic font. This may not be a Pragmata only solution I really don't know how one would go about making a stylistic set the main font style for a font. It should be noted I use Pragmata in a text editor that does not have options to change the stylistic set much like microsoft word does.

**Comment by fabrizioschiavi** [comment]
You gave me a good idea: to create a open source page in GitHub to explain how to enable Stylistic Sets and other OpenType features in the numerous text editors and apps. In some editor this is impossible but to know it behind use a font can be useful. 

About PragmataPro Cursive that replace main Italic alphabet in a optional version: all depends by the number of requests. If it’s high enough I can release it.

Thank you!

**Comment by DeLaGuardo** [comment]
Also, it would be nice if this site would allow corrections in the font itself. For example, use for italic Stylistic Set 6 etc. Like for input font from FontBureau - [Input](http://input.fontbureau.com/)

**Comment by fabrizioschiavi** [comment]
Thanks @DeLaGuardo for the suggestion but how to create something like that? :slightly_smiling_face:

**Comment by DeLaGuardo** [comment]
I can help you with the website.

**Comment by CodeMonkeyMike** [comment]
@fabrizioschiavi Do you know how to change a stylistic set in Iterm2 on OSX? I couldn't find a way to do it.

**Comment by voronoipotato** [comment]
I could use stylistic sets on VSCode and Visual Studio. It may not be possible.

**Comment by fabrizioschiavi** [comment]
This issue can be fixed with the use of [OTFeatureFreezer GUI](https://github.com/twardoch/fonttools-opentype-feature-freezer) or with a command-line script as suggested here: https://github.com/fabrizioschiavi/pragmatapro/issues/246#issuecomment-1817905284
