### ISSUE TITLE
Medieval superscript letter diacritics

### ISSUE THREAD

**Issue by mxpiotrowski** [fabrizioschiavi/pragmatapro#85]
Hi,

Would you consider adding the combining characters in the Unicode range U+0363–U+036F to PragmataPro? This would help a lot with using it for code and markup involving historical text.

PragmataPro already supports most of the characters and diacritics required by the Collection of Swiss Law Sources (a critical edition of historical legal texts), with the exception of these combining characters (the other exceptions are much rarer). When teaching I often show examples of XML markup of historical texts, and it's always a compromise—use a font containing the required characters, but unsuitable for code, or a font suitable for code, but not containing the characters...

Thanks and best regards

**Comment by fabrizioschiavi** [comment]
I’ll add them with pleasure. Thanks for suggested me this!

**Comment by mxpiotrowski** [comment]
Awesome!

Many thanks in advance!

**Comment by fabrizioschiavi** [comment]
Medieval superscript letter diacritics are been added since version .827
![combined_letters](https://user-images.githubusercontent.com/1576663/45231678-1844c500-b2cd-11e8-8c40-70a115da41c8.png)

**Comment by mxpiotrowski** [comment]
Magnifico, grazie mille!
