### ISSUE TITLE
Italic configuration on windows?

### ISSUE THREAD

**Issue by kwonoj** [fabrizioschiavi/pragmatapro#86]
I've been using regular and just purchased italic and installed it and found italic falls back to different fontface on editor I'm using. 

![image](https://user-images.githubusercontent.com/1210596/33223225-8317fd40-d112-11e7-88bf-f5cd4913f5cb.png)

you can see above italic is not font set I applied. I checked editor's behavior (VS Code), what it does is simply apply `font-style: italic`, like below: 

![image](https://user-images.githubusercontent.com/1210596/33223251-a35e15b2-d112-11e7-8897-115d8260207c.png)

and my config for editor fontface is `PragmataPro`. 
![image](https://user-images.githubusercontent.com/1210596/33223269-bf143944-d112-11e7-9691-019e1099520d.png)

I tried to expand to specify italic as well such as `"editor.fontFamily": "PragmataPro, 'PragmataPro-Italic'",` and vice versa but it didn't work. I maybe doing something dumb, but is there any specific configuration for fontfaces to enable italic correctly?

**Comment by freebroccolo** [comment]
In your screenshot that actually looks correct for the italics. For comparison, here is how it looks in wordpad. You can also double click on the Italic font file in the file explorer to see a sample. Were you expecting it to look different?

![font](https://user-images.githubusercontent.com/151197/33223854-f537d0f4-d120-11e7-81c8-82a571dcbb5a.png)

**Comment by kwonoj** [comment]
Oh wait, you are correct @freebroccolo 🤔 I was confused by fontface of `g`, thought it'd be equal.

**Comment by kwonoj** [comment]
I feel some differences between, but guess I need to reconfirm it on my end - closing for now. Thx, @freebroccolo .
