### ISSUE TITLE
Checkbox ligatures vor Markdown checklists

### ISSUE THREAD

**Issue by Tekl** [fabrizioschiavi/pragmatapro#89]
Hi,

The Github flavored markdown has a cool checklist feature:
https://github.com/blog/1825-task-lists-in-all-markdown-documents

What about a ligature for `- [ ]` and `- [x]` with a stylish box and checkmark?

**Comment by fabrizioschiavi** [comment]
I love your suggestion! I'll add them with pleasure

**Comment by bogwonch** [comment]
Can I suggest if you're doing those you also add the checkboxes for Org mode, since they're similar!

`- [X]` for done
`- [-]` for partially done
`- [ ]` for not done

**Comment by jordwalke** [comment]
Could this interact with code content?

**Comment by xguerin** [comment]
Yes. This is particular: [ ], as it is often used to define empty arrays/lists in many programming languages.

**Comment by jordwalke** [comment]
That was my concern. And the subtraction sign could represent list difference ( - [x] )

**Comment by fabrizioschiavi** [comment]
Isn't better this combination to avoid interactions with the code
`  [x]`
`  [-]`
`  [v]`
`  [ ]`
?
Always two spaces before the combinations

**Comment by bogwonch** [comment]
For org-mode at least it has to be: `- [ ]`.  You could do `-  [ ]` but as soon as you toggle it resets it to the single spaced variant, and we're back to square one.  

I guess the proper solution (for me in Emacs at least) is to add the unicode ballot boxes at U+2610–U+2612 to the prettify-symbols list, but it seems a shame they couldn't work as proper ligatures everywhere tho...

Not sure empty checkbox `[ ]` with a space in the middle is an issue so much (do people add the redundant space for arrays?), the `[x]` is more troublesome…

**Comment by fabrizioschiavi** [comment]
Since version 0.827 Markdown Checklist is included in OpenType feature Stylistic Set 12
![markdown_checklist](https://user-images.githubusercontent.com/1576663/45231412-29d99d00-b2cc-11e8-895f-eab3ba762078.gif)

**Comment by Tekl** [comment]
Is there a trick to select a system wide default Feature Set for Pragmata Pro on macOS? In some Editors like TextEdit or CotEditor I can select the stylistic stylesets in the Typography panel of the Font selection (via cog menu). But the setting is not saved and Editors like TextMate or Ulysses even don't respect the stylistic settings. So I can't use it anymore with v0.827. Maybe there is a tool to modify font files to activate a default set.

**Comment by Tekl** [comment]
Btw. using SS12 seems to have bug. When I type Check the Ch will be transformed into C with a ♥ below.

**Comment by lcpichette** [comment]
> Since version 0.827 Markdown Checklist is included in OpenType feature Stylistic Set 12 ![markdown_checklist](https://user-images.githubusercontent.com/1576663/45231412-29d99d00-b2cc-11e8-895f-eab3ba762078.gif) [ ![markdown_checklist](https://user-images.githubusercontent.com/1576663/45231412-29d99d00-b2cc-11e8-895f-eab3ba762078.gif) ](https://user-images.githubusercontent.com/1576663/45231412-29d99d00-b2cc-11e8-895f-eab3ba762078.gif) [ ](https://user-images.githubusercontent.com/1576663/45231412-29d99d00-b2cc-11e8-895f-eab3ba762078.gif)

I feel a little silly for asking, but how do you enable this? Is there a particular font you have to use? (e.g. PragmaticPro Liga vs PragmaticaPro) Trying to use it on wezterm, which supports ligatures (and other ligatures like <> work), but I just can't seem to use the - [ ] styling.
