### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by jordwalke** [fabrizioschiavi/pragmatapro#9]
- How does this other project have a copy of PragmataPro free for download?
  https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher
- Why doesn't that version have the ligatures for functional languages?
- If that isn't supposed to be available for free, how can I try the version with ligatures to make sure it actually works in my editor?
- If not open sourced, how can people modify it to include all the new file icons in nerd-filetype-glyphs project?

**Comment by abl** [comment]
* Pretty sure it's unauthorized; actually, all of the fonts being distributed there are in violation of their respective licenses.
* 0.820 is the version with ligatures. That repo has version 0.8.
* Which editor do you use and on which platform?
* Distributing a script that modifies PragmataPro is fine; the license doesn't (and can't, really) prevent you from modifying your own copy.

**Comment by jordwalke** [comment]
Hmm, someone should reach out to the developer of that repo then and ask them to take that down.

I use MacVim. I'd *really* like to get the ligatures working, even if that means forking MacVim, but I don't know if it will work, so it's kind of disappointing that there's no way to try out a font before purchasing a license.

**Comment by abl** [comment]
Already reached out.

Conveniently, I have a 10.10 machine and a copy of 0.820. Screenshots incoming. :)

**Comment by abl** [comment]
Hmm. Found https://github.com/i-tu/Hasklig - looks like ligatures are explicitly disabled in MacVim due to rendering issues:

https://github.com/b4winckler/macvim/commit/8c8db3cd4cb094535ecb0254a7fb2e15be31d4fd

Building MacVim from HEAD right now to see what happens.

**Comment by jordwalke** [comment]
Note that there are two different rendering modes in MacVim accessible via the preferences panel. Try both - I believe you must restart MacVim after switching modes.

**Comment by abl** [comment]
Tried both with a MacVim restart. No difference. I'll try again with that commit reverted later on.

**Comment by jordwalke** [comment]
Sounds good. I guess I would even use a forked version of MacVim if it meant I could use the ligatures!

**Comment by abl** [comment]
Success...ish. I tweaked the MacVim homebrew formula to revert the relevant commit, built, disabled the CoreText renderer, and...

![screen shot 2015-04-04 at 4 59 57 pm](https://cloud.githubusercontent.com/assets/167740/6995173/116bd262-daec-11e4-8a95-b099494684df.png)

Note the weird spacing. The raw text displayed is:

    !! object
    d != 0
    false !== true
    ***numeric
    mapAccum *= height

I'd personally find this obnoxious. :(

**Comment by jordwalke** [comment]
Ah, thanks for checking! It's too bad that doesn't work. It seems like many editors need to step up their game. Now, even MacVim has no official maintainer, and I'm not sure who would fix it (or how).

**Comment by jordwalke** [comment]
Poking around the web, it looks like there's a setting `defaults write org.vim.MacVim MMAtsuiRenderer 1`. I don't know what it does.

**Comment by jordwalke** [comment]
I also just found the `ambiwidth` property of Vim. It might make that render a bit better.

**Comment by abl** [comment]
```MMAtsuiRenderer ``` appears to be a legacy setting.

```ambiwidth=double``` doesn't help either. :(

**Comment by jordwalke** [comment]
I see. That's really too bad that MacVim doesn't work with ligatures. Vim's "conceal" feature really leaves much to be desired as well.

**Comment by fabrizioschiavi** [comment]
First thanks @abl for the help! Very appreciated

Some softwares can interpreter PragmataPro as monospaced  because all "simple" glyphs has the same width (1060em)  but "ligature" glyphs has multiple widths (1060x2=2120em and 1060x3=3180em)
To avoid issues with some issues with more scrupolous softwares I released PragmataPro Mono deleting "ligatures", since version 0.821

![pp_ppm_epp](https://cloud.githubusercontent.com/assets/1576663/8594651/47406e00-2643-11e5-8ae2-35a639000a3d.png)

**Comment by jordwalke** [comment]
Cool. How does it work in software like MacVim? There's no way for me to try it out without first purchasing it. (Obviously the ligatures no longer work in that case, right?)

**Comment by abl** [comment]
@fabrizioschiavi happy to help!

@jordwalke PragmataPro Mono contains only monospaced glyphs so it'll work fine in MacVim et al - and yes, no ligatures will be displayed, but there will be no graphical/alignment issues.

**Comment by rafaelrinaldi** [comment]
@fabrizioschiavi @abl I currently have my copy of `Essential PragmataPro` and my code editor is Vim (throught the Terminal, not MacVim). I also wanted to try ligatures before actually buying it, is there any chance? Thanks,

**Comment by jordwalke** [comment]
Good news: You can check out the progress in MacVim here - https://github.com/macvim-dev/macvim/issues/36

Accompanied by pull request https://github.com/macvim-dev/macvim/pull/122

It needs some work (works best with `:set cursorline`), but it's a good start. Atom editor just added support for ligatures as well!

**Comment by fabrizioschiavi** [comment]
@jordwalke very good news!! 
Thanks for sharing!

**Comment by rafaelrinaldi** [comment]
FYI Neovim also plans to support font ligatures in the future: https://github.com/neovim/neovim/issues/1408

**Comment by alextes** [comment]
I think this can be closed. The regular version works great in MacVim. The Mono Liga version works great in NeoVim. I also think jordwalke's original questions were answered a long long time ago 😉 .
