### ISSUE TITLE
Readme graphic has typo

### ISSUE THREAD

**Issue by davmillar** [fabrizioschiavi/pragmatapro#90]
The file https://www.fsd.it/pragmatapro/PP_PPM_EPP.png featured in the readme file has a typo where the word 'Arabic' is misspelled as 'Aarbic'. The full context is the phrase 'Aarbic Required Ligatures' under the heading 'OpenType Features'.

**Comment by fabrizioschiavi** [comment]
Thank you @davmillar ! I’ll fix soon

**Comment by davmillar** [comment]
It's still showing as incorrect in the latest 0.827 version of the graphic
![screenshot from 2018-10-12 11-54-35](https://user-images.githubusercontent.com/576958/46882892-d4863380-ce15-11e8-89e2-e1511c10c8fc.png)
