### ISSUE TITLE
Only "ⓟ" presents in the font

### ISSUE THREAD

**Issue by inflation** [fabrizioschiavi/pragmatapro#91]
I don't know why "ⓟ"(U+24DF) is the only circled letter appearing in the font, but it's very annoying when using Emacs with Spacemacs, while other symbols falling back to Arial:
<img width="66" alt="image" src="https://user-images.githubusercontent.com/2375962/36509656-59424892-172e-11e8-85eb-ef624cb5878a.png">

I would like to ask if you could either add other symbols, or allow me to modify the font (Since it's not stating clearly in the License). Thank you.

**Comment by fabrizioschiavi** [comment]
Thanks for this request! I’ll add the circled letters soon. 
You can also modify the font you prefer but you can’t resell or distribute it.

**Comment by inflation** [comment]
Good to hear that, looking forward to them.

**Comment by sondr3** [comment]
Sadly it seems like this isn't working correctly in Emacs, as you can see from my screenshot. Would it also be possible for you to update the Emacs snippets for 0.827? 

![screen shot 2018-09-07 at 16 33 22](https://user-images.githubusercontent.com/2280539/45225120-0e669600-b2bc-11e8-9a7b-f9378dd8e010.png)

**Comment by fabrizioschiavi** [comment]
All the letters and numbers are enclosed in circles since version .827
For both Mono and Modular version

![enclosed_alphanumerics](https://user-images.githubusercontent.com/1576663/45285696-16088380-b4e4-11e8-93fa-3589f40a81fd.gif)

**Comment by sondr3** [comment]
Ah, okay, in that case. I still heavily prefer the modular version compared to the mono ones. If anyone else than me uses the PragmataPro Mono version as the default font in Emacs you can set the font for the mode line to be the regular Pragmata Pro like this:

```elisp
(set-face-attribute 'mode-line nil
                    :family "PragmataPro Liga"
                    :height 140)
```
