### ISSUE TITLE
Character '∷' (U+2237) renders incorrectly in italic font

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#94]
Above in non-italic, below in italic (after the hyphens):

![image](https://user-images.githubusercontent.com/12575/37503473-cbf85bb4-292c-11e8-8df0-94dd75f1fb60.png)

**Comment by fabrizioschiavi** [comment]
Thanks for letting me know it! I'll fix it soon

**Comment by Porges** [comment]
I think this is the same as #96, as it's just a missing character?

I only just realized that that's a face 🙂

**Comment by fabrizioschiavi** [comment]
Since version .827 my face disappeared as substitution character in Italic
