### ISSUE TITLE
No “ị” (U+1ECB) in bold or italic font

### ISSUE THREAD

**Issue by Porges** [fabrizioschiavi/pragmatapro#96]
This is a Vietnamese character.

Above is bold, below is normal. It is also missing from italic.

![image](https://user-images.githubusercontent.com/12575/37751011-13dfd392-2de4-11e8-9c95-2c7bfc350512.png)

Thanks!

**Comment by fabrizioschiavi** [comment]
Please consider that at the moment (v_0.826)
Regular has 9315 glyphs 
Italic 5900
Bold 5900
Bold Italic 5888
The next release has the principal goal to add a lot of new glyphs to Italic, Bold and Bold Italic weights, surely will includes Vietnamese characters. 
Thank you George!

**Comment by Porges** [comment]
Ah, I didn't realize that they were intended to be different at the moment.

**Comment by fabrizioschiavi** [comment]
No, the intention is always been to reach the same number of  glyphs for all the weights. It’s a lot of work I hope to see the end, always if can exist the end for a project like this 🧐

**Comment by fabrizioschiavi** [comment]
Driven by your request, I completed not only the glyphs of the Vietnamese alphabet but completed all the set Latin Extended A and B in all the weights. Since v_0.828

**Comment by Porges** [comment]
Thanks!
