### ISSUE TITLE
U+21D8 and U+21D9 are swapped in PragmataPro Mono

### ISSUE THREAD

**Issue by curtmack** [fabrizioschiavi/pragmatapro#97]
U+21D8 is SOUTH EAST DOUBLE ARROW, and U+21D9 is SOUTH WEST DOUBLE ARROW. PragmataPro Mono swaps these characters, so that U+21D8 points to the south west and U+21D9 points to the south east. PragmataPro renders them correctly.

PragmataPro Mono:
![south-east-ppmono](https://user-images.githubusercontent.com/10149319/39392871-9c45f11a-4a83-11e8-959d-dda0e25aa42b.png)
![south-west-ppmono](https://user-images.githubusercontent.com/10149319/39392872-9c589eb4-4a83-11e8-982b-2ca3552a3b63.png)

PragmataPro:
![south-east-pp](https://user-images.githubusercontent.com/10149319/39392875-a4c86cbe-4a83-11e8-8b9c-3b909e3328b8.png)
![south-west-pp](https://user-images.githubusercontent.com/10149319/39392876-a4d894c2-4a83-11e8-99ab-424785ecae2f.png)

**Comment by fabrizioschiavi** [comment]
Thank you @curtmack ! I’ll fix this soon.
