### ISSUE TITLE
Shop not working because of an old Stripe key

### ISSUE THREAD

**Issue by renstrom** [fabrizioschiavi/pragmatapro#98]
Not sure where to report this, but your shop isn't working because of an old Stripe API key:

>IntegrationError: It looks like you're using an older Stripe key. In order to use this API, you'll need to use a modern API key, which is prefixed with 'pk_live_' or 'pk_test_'. You can roll your publishable key here: https://dashboard.stripe.com/account/apikeys

**Comment by fabrizioschiavi** [comment]
I’m just working at this in this moment.
Thank you very much for this report, precious as gold!

**Comment by fabrizioschiavi** [comment]
I just updated the API key. @renstrom can you confirm it works now?

**Comment by renstrom** [comment]
>precious as gold

Literally 😉 

>I just updated the API key. Can you confirm it works now?

Yes, it seems like it's working now. I didn't _actually_ buy, but at least now I can get as far as the checkout page. So I think it's safe to assume it's working. Previously the whole flow was broken.

**Comment by fabrizioschiavi** [comment]
No problem, thank you again!
